### ISSUE TITLE
Problems with Lifetimes - Explicit annotation

### ISSUE THREAD

**Issue by observant2** [rust-lang/rust-by-example#1023]
I thought a lot about this and don't understand it.

```rust
// A function which takes no arguments, but has a lifetime parameter `'a`.
fn failed_borrow<'a>() {
    let _x = 12;

    // ERROR: `_x` does not live long enough
    let y: &'a i32 = &_x;
    // Attempting to use the lifetime `'a` as an explicit type annotation 
    // inside the function will fail because the lifetime of `&_x` is shorter
    // than that of `y`. A short lifetime cannot be coerced into a longer one.
}
```

Why is the lifetime of &_x shorter? Aren't y and _x both dropped at the end of the function? What lifetime does &_x get, when you don't annotate it?

I'm using Rust since a few months for toy projects and I thought that I understood lifetimes, but this I really don't understand.

**Comment by leodasvacas** [comment]
The first thing to notice is that lifetimes parameters such as `'a` are determined by the caller of the function, not by the function body.

The lifetime parameter `'a` is unbounded, which means it could be as large as the caller wants it to be so in practice it should be considered as large as `'static`. In your code `_x` has the lifetime of the function body and therefore cannot outlive and arbitrary `'a` given as input. Does that make sense?

[The nomicon has more on unbounded lifetimes.](https://doc.rust-lang.org/nightly/nomicon/unbounded-lifetimes.html)

**Comment by itmuckel** [comment]
Yes! Totally! Thanks a lot!

The last thing I don't understand here is: How would I specify a lifetime as a caller. Normally the lifetime specifier specified in a function definition corresponds to a function parameter or return value. So when I pass a value with a specific lifetime I implicitly specify the lifetime of `'a`. But with no value present I cannot do that.

If this is right, wouldn't an example with an actual parameter or return value (bounded by `'a`) make more sense here? :smile:

**Comment by leodasvacas** [comment]
Indeed the caller cannot explicitly specify the lifetime, but it can make that lifetime as long as it wants. Which in this case doesn't make sense because `'a` isn't used at all by the caller! You're right that this example is confusing and doesn't make much sense.

**Comment by marioidival** [comment]
@itmuckel hey, you can make a PR to given us a good example?

**Comment by itmuckel** [comment]
As @leodasvacas already said, there is no good example. The `failed_borrow<'a>()` makes no sense, because there is no way to specify `'a` from the caller's perspective. Therefore there is also no way to make this function work. That may be the source of my confusion. 

I'm not a rust expert, but in my opinion functions like this should be a compiler error. I cannot see any use case where a lifetime parameter that can't be specified is ever useful. 😄

**Comment by optevo** [comment]
> The first thing to notice is that lifetimes parameters such as `'a` are determined by the caller of the function, not by the function body.
> 
> The lifetime parameter `'a` is unbounded, which means it could be as large as the caller wants it to be so in practice it should be considered as large as `'static`. In your code `_x` has the lifetime of the function body and therefore cannot outlive and arbitrary `'a` given as input. Does that make sense?
> 
> [The nomicon has more on unbounded lifetimes.](https://doc.rust-lang.org/nightly/nomicon/unbounded-lifetimes.html)

I had the same reaction/experience as @itmuckel - it wasn't clear based on the current explanation why the lifetime of y is longer and there isn't any way of fixing this (other than removing the lifetime annotation).

It would be useful if this explanation were added directly to the page - I think it is useful to keep the example but only if you add the points you make above. If these aren't explained explicitly it will confuse a lot more people.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
