### ISSUE TITLE
Don't use the terms r-value and l-value

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust-by-example#1028]
Currently used in src/expression.md and src/types/inference.md

These terms are compiler jargon at best and [not great for explaining things to users](https://twitter.com/Gankro/status/935999297874812929), and even inside the compiler we've been moving away from them (e.g., https://github.com/rust-lang/rust/pull/47837).

**Comment by steveklabnik** [comment]
We did this for the reference: https://github.com/rust-lang-nursery/reference/pull/167

RBE should follow that example.

**Comment by steveklabnik** [comment]
This is a dup of https://github.com/rust-lang/rust-by-example/issues/988
