### ISSUE TITLE
Activity: Tuples

### ISSUE THREAD

**Issue by buckle2000** [rust-lang/rust-by-example#1029]
The [2. activity here](https://rustbyexample.com/primitives/tuples.html#activity) is hard to write. The concept of "borrowing" and functions must be introduced first to write `transpose`.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
