### ISSUE TITLE
TODO suggestion in std_misc/threads/testcase_mapreduce seems incorrect

### ISSUE THREAD

**Issue by tahsmith** [rust-lang/rust-by-example#1032]
One of the suggestions in std_misc/threads/testcase_mapreduce does not seem in fact possible.
The TODO:

```
// collect each thread's intermediate results into a new Vec
let mut intermediate_sums = vec![];
for child in children {
    // collect each child thread's return-value
    let intermediate_sum = child.join().unwrap();
    intermediate_sums.push(intermediate_sum);
}

// combine all intermediate sums into a single final sum.
//
// we use the "turbofish" ::<> to provide sum() with a type hint.
//
// TODO: try without the turbofish, by instead explicitly
// specifying the type of intermediate_sums
let final_result = intermediate_sums.iter().sum::<u32>();
```

Adding an explicit type to the declaration of `intermediate_sums` in place of the turbofish does not have the same effect. Or is the point of this suggestion to show that it is not possible?

See also, https://stackoverflow.com/questions/49250494/why-cant-rust-infer-the-result-of-sum-when-given-an-explicit-type-of-a-sequence/49250749
https://stackoverflow.com/questions/41017140/why-cant-rust-infer-the-resulting-type-of-iteratorsum

**Comment by vitvakatu** [comment]
Yes, this is a typo, definitely.
The correct version would be `specifying the type of final_result`

**Comment by frewsxcv** [comment]
opened a pr for this https://github.com/rust-lang/rust-by-example/pull/1038
