### ISSUE TITLE
Add examples for TryFrom/TryInto

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust-by-example#1037]
~These traits just stabilized~

Tracking issue: https://github.com/rust-lang/rust/issues/33417

**Comment by frewsxcv** [comment]
The traits were destabilized, so #1039 was reverted in https://github.com/rust-lang/rust-by-example/pull/1077. If and when they restabilize, we can revert the revert

**Comment by marioidival** [comment]
#1247 closed
