### ISSUE TITLE
Arc chapter

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#104]
Add information about Arc<T> to https://rustbyexample.com/std.html

**Comment by brson** [comment]
Closing because old.

**Comment by brson** [comment]
Similar to https://github.com/rust-lang/rust-by-example/issues/105, come up with an example that focuses on `Arc`, in various common patterns, just add it under the "Std misc" chapter.

**Comment by steveklabnik** [comment]
(meta: deleted a comment and moved it into the description)

I'm happy to mentor anyone who wants to fix this issue!

**Comment by justohdezromera** [comment]
> 
> 
> (meta: deleted a comment and moved it into the description)
> 
> I'm happy to mentor anyone who wants to fix this issue!

Hi @steveklabnik, I would like to work on this. Would you be available for mentoring?

**Comment by steveklabnik** [comment]
Hey @justohdezromera !

So, yes and no. That is, I can help mechanically, but I am not sure if a chapter on arc fits into the current structure or not, nor where. Maybe @marioidival has opinions.

**Comment by justohdezromera** [comment]
In my opinion, I would find it coherent since I see that Arc is a struct type. Even it is a Thread related type, still a type. Furthermore, it could be placed just after the Rc chapter, since they are kind of counter-elements.

**Comment by steveklabnik** [comment]
Ah yes, if there's already stuff about RC, honestly, adding arc to it would probably make the most sense.

**Comment by justohdezromera** [comment]
Hi @steveklabnik, I do have this repo modified to solve this issue but I am not aware of how to upload it here, I mean mechanically. I am not sure if I have to make a push to the master branch or how it is really done, may I have some clarification here, please?

**Comment by justohdezromera** [comment]
I think I did the request by now, I forked the repo and updated it privately, then requested the merge to the original repo. Was that OK? :)

**Comment by steveklabnik** [comment]
Looks like you got the mechanics right, yep! I don't have time to review right now, but I or someone else will get to it. Thank you!

**Comment by justohdezromera** [comment]
May be this issue can now be closed?
