### ISSUE TITLE
Code blocks conflict with search keybinding

### ISSUE THREAD

**Issue by AntonLee** [rust-lang/rust-by-example#1040]
Pressing 's' while editing code block opens search bar instead of adding 's' symbol.

**Comment by frewsxcv** [comment]
filed a bug upsream on mdbook https://github.com/rust-lang-nursery/mdBook/issues/654

**Comment by AntonLee** [comment]
Thanks.

**Comment by AntonLee** [comment]
It's probably better to keep it open until issue is resolved, for people to see that it is already reported.

**Comment by steveklabnik** [comment]
Since there's nothing to do in this repo, we'd prefer to keep it closed; that way we can track what work we actually have to do. Thanks!
