### ISSUE TITLE
update for immovable types

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-by-example#1058]
This issue tracks inclusion of the new pin types into the Book. This will happen in the 2018 edition.

Tracking issue: rust-lang/rust#49150

**Comment by RalfJung** [comment]
I'd prefer if we wouldn't call them "immovable types", that has already [lead to confusion](https://github.com/rust-lang-nursery/rust-bindgen/issues/1286).

**Comment by steveklabnik** [comment]
Given that this is a stdlib change, I don't think we'll be including it directly in RBE.
