### ISSUE TITLE
Topics for the "args" chapter

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#106]
- [ ] ~~~`os::args`~~~: return type, first arg is the program name, number of arguments
- [x] ~~~matching on `os::args`~~~
- [x] `getopts`

---

@vks is working on this

**Comment by steveklabnik** [comment]
I'd be happy to mentor anyone who wants to work on this!

**Comment by vks** [comment]
I think `getopts` was moved out of the standard library. Maybe hint at `clap` and friends instead?

**Comment by steveklabnik** [comment]
Or, maybe referring to the Cookbook for "real" argument parsing.

**Comment by maccoda** [comment]
In the initial issue comment, does `os::args` now refer to the `ArgsOs` iterator?

**Comment by steveklabnik** [comment]
Yup! https://doc.rust-lang.org/stable/std/env/fn.args.html and its return type

**Comment by steveklabnik** [comment]
I'm not sure what the second checkbox is, so I just checked it off.

**Comment by maccoda** [comment]
@steveklabnik awesome, thanks will work on the next PR! :smile:

**Comment by maccoda** [comment]
@steveklabnik Having a look at the current [args page](https://rustbyexample.com/std_misc/arg.html) it looks like the issue has already been addressed... It describes how to get the first argument and the number of arguments. Is there something else we should be adding?

**Comment by steveklabnik** [comment]
You're totally right, looks great to me. Thanks for closing this out!
