### ISSUE TITLE
update for `impl Trait`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-by-example#1060]
This issue tracks inclusion of information about impl Trait into the Book. This will happen in the 2018 edition.

Tracking issue: rust-lang/rust#34511

**Comment by palotasb** [comment]
I'm going through the book and I wanted to post an issue about this. [Closures as output parameters](https://github.com/rust-lang/rust-by-example/blob/d2a64395a5210a61d3512a3a5c615f5c47699443/src/fn/closures/output_parameters.md) says that
> returning closure types are problematic because Rust currently only supports returning concrete (non-generic) types

I've been able to change the examples from `Box<Fn*()>` to returning `impl Fn*()` so I guess the information above is obsolete.
