### ISSUE TITLE
update for main with non-`()` return types

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-by-example#1062]
This issue tracks inclusion of information about main with non-() return types into the Book. This will happen in the 2018 edition.

Tracking issue: rust-lang/rust#48453

**Comment by maccoda** [comment]
I wouldn't mind picking this one up. Did we have any ideas for where this would be located in the book?

**Comment by frewsxcv** [comment]
Maybe as a sub-section of `Result`?

https://doc.rust-lang.org/stable/rust-by-example/error/result.html

```
18.3.5 Using `Result` in `main`
```
