### ISSUE TITLE
update for generators

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-by-example#1064]
This issue tracks inclusion of information about generators into the Book. This will happen in the 2018 edition.

Tracking issue: rust-lang/rust#43122

**Comment by adamchalmers** [comment]
Generators didn't make it into Rust 2018, should we remove the "Blocking Rust 2018" label?

**Comment by steveklabnik** [comment]
Absolutely!

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
