### ISSUE TITLE
rustbyexample.com is down

### ISSUE THREAD

**Issue by ctsrc** [rust-lang/rust-by-example#1071]
The server responds to ping but https://rustbyexample.com does not load.

**Comment by steveklabnik** [comment]
Please see https://users.rust-lang.org/t/rustbyexample-com-is-down/16632/9

TL;DR: DNS is being weird. https://doc.rust-lang.org/stable/rust-by-example/ is the correct link now anyway.

**Comment by steveklabnik** [comment]
Yes. Sorry about that! Still workin' on it.

**Comment by Ekleog** [comment]
Currently what I'm getting is HSTS mismatch: rustbyexample.com appears to point directly to github servers, and these force HSTS and give out a certificate for github.com, except it doesn't match rustbyexample.com.

Anyway, thanks for all you do! :)

**Comment by ZanderBrown** [comment]
But it's [still down](https://downforeveryoneorjustme.com/rustbyexample.com)?

**Comment by steveklabnik** [comment]
Keeping it open isn't exactly helpful; It's being dealt with regardless of this issue. I'll leave a comment when it's back up.

**Comment by jBugman** [comment]
I think this might help to get it back easier https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by steveklabnik** [comment]
That is actually what was causing the issue; I had private access to this feature and was trying to use it to accomplish this. I'm hoping to have it resolved for real very soon.

**Comment by steveklabnik** [comment]
It should be back up now.

**Comment by ZanderBrown** [comment]
Confirmed, I get swiftly redirected
