### ISSUE TITLE
trait definition with where clause

### ISSUE THREAD

**Issue by MajorBreakfast** [rust-lang/rust-by-example#1074]
Apparently `where` clauses are also a thing for `trait` definitions, not just for `impl`s.

```Rust
trait Foo {}

trait Bar : Foo {}
trait Baz where Self: Foo {} // <-- With where clause

fn main () {}
```

- There should be an example for it
- The example should illustrate any differences between the two (If they exist)

I first saw this in this comment by @nikomatsakis https://github.com/rust-lang/rfcs/pull/2395#issuecomment-380909608

**Comment by MajorBreakfast** [comment]
I just see that there isn't an example for supertraits in general https://github.com/rust-lang/rust-by-example/issues/90

Supertraits are mentioned in the book. https://doc.rust-lang.org/book/second-edition/ch19-03-advanced-traits.html#using-supertraits-to-require-one-traits-functionality-within-another-trait

I could provide a PR for both. To do so, however, I'd need some assistance as I've no idea what the differences between the two are.

**Comment by MajorBreakfast** [comment]
So, I can define a supertrait using either notation and there is no difference?

Only the `where` clause could do more:
```Rust
trait Foo {}
trait Bar where Self: Sized, Option<Self>: Foo {}

struct Baz {}
impl Bar for Baz {}
impl Foo for Option<Baz> {}
```
https://play.rust-lang.org/?gist=f7791185db6b3ec61fc1161bf3656674&version=stable

**Comment by marioidival** [comment]
Yes, he can, and that is point, you can use `where` to thing more complex than `basic: bounds`.

**Comment by marioidival** [comment]
@MajorBreakfast has some news?

**Comment by MajorBreakfast** [comment]
Damn these two weeks flew past quickly. I created a post-it note back then. I'll create the PR in the next two days :-)

**Comment by marioidival** [comment]
@MajorBreakfast :thinking: has some news?
