### ISSUE TITLE
Code editor menu broken

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-by-example#1078]
The text at https://rustbyexample.com/hello.html says that I should be able to press "Run" and execute the code directly from my browser, but there is no such button. When I hover the top-right corner of the text field, the cursor turns into a hand, as if there was an invisible button there -- but pressing it does not do anything. I tried both FF and Chromium.

**Comment by steveklabnik** [comment]
Ugh, so, apparently somehow the redirect broke. I will investigate. https://doc.rust-lang.org/stable/rust-by-example/hello.html is what the URL should be, and we have the little arrow, not a literal "run" button. Maybe the text should be changed to fix this.

**Comment by steveklabnik** [comment]
Okay, I forgot to tell travis to stop building things :( that aspect is fixed. the wording could be better though.

**Comment by RalfJung** [comment]
Now https://rustbyexample.com/hello.html is a 404 error?

**Comment by steveklabnik** [comment]
Yes, the redirect for sub-pages hasn't been fixed. It will happen Monday or Tuesday.

**Comment by adamchalmers** [comment]
This is fixed and can be closed - @marioidival or @steveklabnik?

**Comment by marioidival** [comment]
@adamchalmers yeah!
