### ISSUE TITLE
URLs from Google search results are redirect looping

### ISSUE THREAD

**Issue by vladikoff** [rust-lang/rust-by-example#1081]
Search for `iterator find rust` in Google, click on `Iterator::find - Rust By Example` result, that goes to 

![image](https://user-images.githubusercontent.com/128755/40032326-b06171b0-57c1-11e8-9c4a-08394cefd5a4.png)

and later redirect loops
![kapture 2018-05-14 at 21 57 08](https://user-images.githubusercontent.com/128755/40032344-c4d51a2a-57c1-11e8-8663-9e272198c279.gif)

**Comment by steveklabnik** [comment]
This should be fixed by https://github.com/rust-lang/rust-by-example/pull/1082, sorry about that!
