### ISSUE TITLE
Code/Editor font size too small / different from the book

### ISSUE THREAD

**Issue by Eyenseo** [rust-lang/rust-by-example#1087]
The font size of the code (`ace_*`) is too small (12px). The normal font is 17px and I see no reason why the code is small if the page is actually about _the code_. 

The book uses the same font size for text and code which works very well in my opinion.

**Comment by Eyenseo** [comment]
`ace_*` is the css class, sorry for the confusion. All editors / runable code elements are affected as far as I know. 


![foo](https://user-images.githubusercontent.com/3954885/41221021-4ef3c146-6d63-11e8-948a-ae99599a027e.png)

**Comment by steveklabnik** [comment]
This is an upstream issue, would you mind filing it at https://github.com/rust-lang-nursery/mdbook please? We don't, as far as I know, customize anything here. It'd be editable vs non-editable examples.
