### ISSUE TITLE
Running examples results in "Undefined"

### ISSUE THREAD

**Issue by jackcmay** [rust-lang/rust-by-example#1094]
When attempting to run any of the rust-by-example examples the only output generated is the string "Undefined".  The example on the rust home page works and the rust playground works.

Tried on safari and firefox with macos Yosemite.

**Comment by Arnavion** [comment]
Playground responds with HTTP 500 `{"error":"Unable to deserialize request: Can't parse body to the struct"}` because it's missing a `backtrace: false` property in the POST body. Adding that to the `params` object used in `fetch()` makes it work.

**Comment by frewsxcv** [comment]
Relevant issues: https://github.com/rust-lang-nursery/mdBook/pull/751 https://github.com/rust-lang/rust/issues/52871

**Comment by Arnavion** [comment]
Playground made the parameter optional to unbreak existing docs, and mdBook has updated to use the proper endpoint for new docs, so this can be closed now.
