### ISSUE TITLE
Split current "macro_rules" chapter ", cover more topics

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#110]
This chapter needs splitting:
- [ ] intro: `macro_rules` is behind a feature gate + simple example (no arguments)
- [ ] arguments and designators: `$foo:expr`
- [ ] variable number of arguments: I would like to use @vks [range!](https://github.com/japaric/rust-by-example/issues/75) example here
- [ ] commas are not needed to separate the arguments: `do!($this and $that)`
- [ ] `+` and `*` expansion
- [ ] stay DRY: generating test suite / trait implementations using macros

---

We also want to cover:
- [ ] How to link "macro" crates `#[phase(plugin)]`

**Comment by steveklabnik** [comment]
I'm going to close this issue as stale; there are improvements to be made here, but most of this ticket isn't relevant in today's Rust.
