### ISSUE TITLE
The code theme in the website needs updating

### ISSUE THREAD

**Issue by donaldnevermore** [rust-lang/rust-by-example#1109]
1. The colors are so similar and hard to read.

![tim 20181026225857](https://user-images.githubusercontent.com/29004603/47575005-98091a80-d973-11e8-8ac7-c4ee5cba68a9.png)

2. It's inconsistent with the rust book's code theme. 

![tim 20181026225843](https://user-images.githubusercontent.com/29004603/47575186-0d74eb00-d974-11e8-96f1-18d0f5b96a39.png)

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
