### ISSUE TITLE
Broken theme

### ISSUE THREAD

**Issue by Sebi2020** [rust-lang/rust-by-example#1114]
The book can not be displayed locally:
![grafik](https://user-images.githubusercontent.com/1862664/48217538-eeb92000-e387-11e8-8f06-a3a67322f495.png)

**Comment by steveklabnik** [comment]
Are you using the correct version of mdbook? It doesn’t build with the latest versions.

**Comment by Sebi2020** [comment]
I just typed `cargo install mdbook` as proposed by the Readme.md of rust-by-example. I wouldn't have thought that mdbook really publish failing packages to crates.io

**Comment by steveklabnik** [comment]
Ah, the readme is incorrect then. You need the last 0.1.z release of mdbook, currently.
