### ISSUE TITLE
Split current "unsafe" chapter, cover more topics

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#112]
The current chapter needs to be split:
- [ ] intro: What does the `unsafe` block means? (can't be proved safe by the compiler), should be used sparingly, first suspect in case of a segfault, should be treated as a red flag by the code reviewer
- [ ] Dereferencing raw pointers
- [ ] `std::mem::transmute` raw pointers -> references
- [ ] `asm!`

We probably want to add:
- [ ] `static mut`

**Comment by steveklabnik** [comment]
I'd be happy to mentor anyone who wants to work on this!

**Comment by crazystylus** [comment]
Hi @steveklabnik ,
Are you still willing to mentor someone one this?
I want to give it a shot!!

**Comment by steveklabnik** [comment]
Sadly, I am not. @marioidival is the only person left working on rust by example. He may, or he may not. Good luck!

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
