### ISSUE TITLE
The "task" chapter is a stub

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#113]
Considering that concurrency is the main selling point of Rust.

These topics should also be covered:

- [ ] How to reap failing tasks
- [ ] `Barrier`
- [ ] `Future`

Consider merging the channels chapter into the task chapter.
Consider adding an example about **unsafe** fork join parallelism. (unsafe because there is no library support for it at the moment)

**Comment by mdinger** [comment]
This seems out of date and is probably invalid
