### ISSUE TITLE
Small language mistake probably - in generics/bounds

### ISSUE THREAD

**Issue by bartsmykla** [rust-lang/rust-by-example#1130]
Hi Rustaceans! :-)

I'm creating this issue because I'm not a native english speaker and I'm not sure if I'm right, but inside https://github.com/rust-lang/rust-by-example/blob/master/src/generics/bounds.md in lines 52-53 we can see:
> // `T` must implement `HasArea`. Any **function** which meets
> // the bound can access `HasArea`'s function `area`.

Actually the parameter is not a function, so I think that there should be something like `structure` or other word. Am I correct?

**Comment by steveklabnik** [comment]
I'd say `type`, yes. Thanks for this! i'd happily take a PR to fix it :)

**Comment by bartsmykla** [comment]
@steveklabnik done: https://github.com/rust-lang/rust-by-example/pull/1132
