### ISSUE TITLE
"To and from Strings"-section recommends ToString in conflict with the book

### ISSUE THREAD

**Issue by Japanuspus** [rust-lang/rust-by-example#1131]
The "To and from Strings"-section recommends implementing the `ToString`-trait directly [1](https://doc.rust-lang.org/rust-by-example/conversion/string.html).  According to the [docs](https://doc.rust-lang.org/std/string/trait.ToString.html), best practice is to not implement this trait directly, but rather to implement the `fmt::Display` trait.

Related, the section on the `fmt::Display` trait does not mention that implementing `fmt::Display` gives `ToString` for free. 

I suggest to replace the "To String" section in "To and from Strings" with an example of this approach, and to include a link to this section from the existing section on `fmt::Display`.

Should I submit a pull-request to this effect, or have I missed something?

**Comment by frewsxcv** [comment]
You hit the nail on the head – feel free to submit a pull request with these changes! Thanks for pointing this out!
