### ISSUE TITLE
Example of enum's use seems outdated

### ISSUE THREAD

**Issue by PumpkinSeed** [rust-lang/rust-by-example#1134]
Currently I'm reading/learning the [enum_use](https://doc.rust-lang.org/rust-by-example/custom_types/enum/enum_use.html#use) section where I got the following error for the use inside the main function:

```
imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130) 
```

Please guide me if I missed something. Thank you.

**Comment by xftroxgpx** [comment]
Since https://github.com/rust-lang/rust-by-example/pull/1136 was merged (albeit manually) maybe this can be closed now?
