### ISSUE TITLE
Split current "FFI" chapter, cover more topics

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#114]
The current chapter needs to be split:
- [ ] `#[link]` attribute, ffi functions are unsafe
- [ ] safe wrappers

These topics also need to be covered:
- [ ] `repr(C)` attribute for structs
- [ ] callbacks
- [ ] exposing rust functions `extern fn` to C (does this belong here?)

**Comment by steveklabnik** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust-by-example/issues/643
