### ISSUE TITLE
Borrowing -> Freezing example works in 2018 edition but text says it shouldn't compile

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-by-example#1140]
Seen on Discord.

In the [freezing](https://doc.rust-lang.org/rust-by-example/scope/borrow/freeze.html) example, it says that the example should not compile. And it doesn't with the 2015 edition. However, when it's executed with the 2018 edition, it compiles. Probably because of NLL? Since the 2018 edition is the default for new projects, I think the example needs to be updated.

[Playground with Rust 2018](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=10e90263bf47bda76a5f7be28a56ad88)
[Playground with Rust 2015](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=10e90263bf47bda76a5f7be28a56ad88)

**Comment by chandu0101** [comment]
also this : [alias](https://doc.rust-lang.org/rust-by-example/scope/borrow/alias.html)

**Comment by yous** [comment]
Now it compiles with the 2015 edition, too.

**Comment by yous** [comment]
Accesing `_large_integer` after modifying `_mutable_integer` gives me an error on the both 2015 and 2018 edition, so the example can be updated to do so.

**Comment by rusty-snake** [comment]
Fixed by #1226?
