### ISSUE TITLE
No `open_mode` method

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-by-example#1147]
[The chapter on File I/O][file_io] mentions the `open_mode` method, but there aren't any
methods like that in the Rust Std documentation. Maybe it should be [OpenOptions struct][oo_struct].

[file_io]: https://doc.rust-lang.org/stable/rust-by-example/std_misc/file/create.html
[oo_struct]: https://doc.rust-lang.org/std/fs/struct.OpenOptions.html

**Comment by mikong** [comment]
For reference, the removal of `open_mode` function in favor of `OpenOptions` struct is described in:

https://rust-lang.github.io/rfcs/0517-io-os-reform.html#files

We can see `open_mode` being marked as deprecated back in February 2015 for the reason "replaced with `std::fs::OpenOptions`":

rust-lang/rust@95d9046
