### ISSUE TITLE
From/Into section 6.1 introduction confusing

### ISSUE THREAD

**Issue by mitchblevins** [rust-lang/rust-by-example#1149]
The introductory text of section 6.1 suggests that the reciprocal Into trait for a From trait does the conversion in the opposite direction.  (type A to B, type B to A).

This is confusing because the conversion is always type A to B, but the From/Into difference is which type it is initiated by.

**Comment by jonmccune** [comment]
I'm a random Rust n00b going through rust-by-example, and I also noticed this. After staring at it for a while, I actually think it would be an improvement if the first two sentences were simply deleted. I.e., just drop:

"The From and Into traits are inherently linked, and this is actually part of its implementation. If you are able to convert type A from type B, then it should be easy to believe that we should be able to convert type B to type A."

**Comment by jakehemmerle** [comment]
Hi, I thought this was confusing too and I came to open an issue.

The example in the book only shows how to convert A to B (using both `B::from(a)` and a.into()`), but it very well suggests we can convert A to B as well as B to A.

These two points should be emphasized:
1. The `From` implementation is preferred to Into
2. `Into` is **automatically** implemented on the destination type,

There was a third claim on the above, closed, PR:
> 3.`Into` must be implemented instead of `From` when both types are not defined by the current crate.

3 appears to be not true, according to this error I got today:

```rust
error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
  --> crypto/shared/src/constraints.rs:27:1
   |
27 | impl Into<sp_core::H160> for H160 {
   | ^^^^^-------------------^^^^^----
   | |    |                       |
   | |    |                       `primitive_types::H160` is not defined in the current crate
   | |    `sp_core::H160` is not defined in the current crate
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead

```

If someone elaborate on the idiomatic way to allow for type conversion between types in different crates, I will open a new PR with these changes. Using a new arbitrary trait seems dirty.

**Comment by jakehemmerle** [comment]
cc @marioidival for visibility
