### ISSUE TITLE
Wrong return types on 14.8 - Associated Items

### ISSUE THREAD

**Issue by flaxed** [rust-lang/rust-by-example#1154]
I'm still reading the book online, but it seems that section both 14.8.1 and 14.8.2 have the wrong code.

Atm the code is as such:
``` rust
trait Contains<A, B> {
    fn contains(&self, &A, &B) -> bool; // Explicitly requires `A` and `B`.
    fn first(&self) -> i32; // Doesn't explicitly require `A` or `B`.
    fn last(&self) -> i32;  // Doesn't explicitly require `A` or `B`.
}
```
but shouldn't the return types for first() and last() also be generic, as in the following example?
``` rust
trait Contains<A, B> {
    fn contains(&self, &A, &B) -> bool; // Explicitly requires `A` and `B`.
    fn first(&self) -> A // Doesn't explicitly require `A` or `B`.
    fn last(&self) -> B;  // Doesn't explicitly require `A` or `B`.
}
```
If this is the case, I assume 14.8.2 also needs to be updated.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
