### ISSUE TITLE
Incorrect use of "either" in section 2.1 

### ISSUE THREAD

**Issue by mikong** [rust-lang/rust-by-example#1155]
The second paragraph of section 2.1 reads:

(original)
> Integers can, alternatively, be expressed using hexadecimal, octal or binary notation using either of these prefixes: `0x`, `0o` or `0b`.

The use of "either" seems inappropriate given the 3 options. "any" is typically used for 3 options but I wouldn't replace "either" with "any" in this case since you can't just use any of the prefixes if you need a specific notation. It seems better to just remove "either of" and then add "respectively":

(revision 1)
> Integers can, alternatively, be expressed using hexadecimal, octal or binary notation using these prefixes respectively: `0x`, `0o` or `0b`.

I would like to move "alternatively" to the start as well, although this is just a matter of preference:

(revision 2)
> Alternatively, integers can be expressed using hexadecimal, octal or binary notation using these prefixes respectively: `0x`, `0o` or `0b`.

I can make a pull request if people agree with these changes.

**Comment by jonmccune** [comment]
I'm a random Rust n00b going through rust-by-example, and also noticed this incorrect use of "either". Both of your suggestions seem like improvements to me.
