### ISSUE TITLE
borrow/ref: Update "The ref pattern" for pattern-binding-modes RFC

### ISSUE THREAD

**Issue by nickolay** [rust-lang/rust-by-example#1166]
As far as I can see, all the use-cases listed in https://doc.rust-lang.org/rust-by-example/scope/borrow/ref.html can avoid using `ref` when the "match ergonomics" feature from https://github.com/rust-lang/rfcs/pull/2005 is available.

It would be good to mention that and to clarify when/if the "ref pattern" is still useful (I couldn't find the answer to that quickly).

**Comment by dschrempf** [comment]
The same applies to https://doc.rust-lang.org/rust-by-example/custom_types/enum/testcase_linked_list.html

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
