### ISSUE TITLE
Cover string escaping and raw strings in the "literals" chapter

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#117]
Add this as a "strings" topic.

Might as well cover the new byte literals.

**Comment by vks** [comment]
This should also cover multi-line strings, i.e.

```rust
let s = "Hello, \
         World!";
```

**Comment by steveklabnik** [comment]
This should go under https://rustbyexample.com/std/str.html

**Comment by jansol** [comment]
I'm interested in working on this.

**Comment by steveklabnik** [comment]
Great! Do you have an idea of what you need to do, or do you need any help? 😄

**Comment by jansol** [comment]
I have some ideas ^
