### ISSUE TITLE
19.2 Vectors Error in Code Example

### ISSUE THREAD

**Issue by sebadoh** [rust-lang/rust-by-example#1171]
https://doc.rust-lang.org/1.29.2/rust-by-example/std/vec.html 

Code contain an error in the following places:

Line number 3: let collected_iterator: Vec<i32> = (0..10).collect();
Should be: let mut collected_iterator: Vec<i32> = (0..10).collect();
Or else Line number16 can't borrow mutably

**Comment by marioidival** [comment]
@sebadoh please, create a PR fixing this :)

**Comment by sebadoh** [comment]
Done (Hopefully) :-)

**Comment by marioidival** [comment]
closes #1178
