### ISSUE TITLE
std/result/question_mark.html confusing due to incompleteness

### ISSUE THREAD

**Issue by peter-kehl** [rust-lang/rust-by-example#1181]
https://doc.rust-lang.org/rust-by-example/std/result/question_mark.html is confusing. Why?
1. It doesn't say that the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`).
2. "where the Err(err) branch expands to an early Err(From::from(err))" is unclear.
3. The example is long, hence complicated and not explanatory enough.

Suggest an example like
```
#[derive(Debug)]
enum OneTwoThree {ONE, TWO, THREE}
type OneTwoThreeResult= Result<OneTwoThree, &'static str>;

impl OneTwoThree {
    fn inc(&self) -> OneTwoThreeResult {
        match self {
            OneTwoThree::ONE => Ok(OneTwoThree::TWO),
            OneTwoThree::TWO => Ok(OneTwoThree::THREE),
            OneTwoThree::THREE => Err("Overflown")
        }
    }
}

fn inc_ok() -> OneTwoThreeResult {
    OneTwoThree::ONE.inc()?.inc()
}

fn inc_overflow() -> OneTwoThreeResult {
    OneTwoThree::ONE.inc()?.inc()?.inc()?.inc()?.inc()?.inc()
}

fn main() {
    println!( "{:?}", inc_ok());
    println!( "{:?}", inc_overflow());
}
```

Please share your thoughts. I'd be happy to incorporate your ideas into a pull request.

**Comment by peter-kehl** [comment]
Or an alternative example: https://github.com/peter-kehl/rust/blob/master/question_mark_operator/increment_sized.rs

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
