### ISSUE TITLE
The Associated Items example is really confusing

### ISSUE THREAD

**Issue by jakubadamw** [rust-lang/rust-by-example#1231]
The "Associated Items" subchapter follows through writing an example in which there is a trait called `Contains` that in its original form has the following definition:

```rust
// A trait which checks if 2 items are stored inside of container.
// Also retrieves first or last value.
trait Contains<A, B> {
    fn contains(&self, _: &A, _: &B) -> bool; // Explicitly requires `A` and `B`.
    fn first(&self) -> i32; // Doesn't explicitly require `A` or `B`.
    fn last(&self) -> i32;  // Doesn't explicitly require `A` or `B`.
}
```

I think this example is a very confusing one. First, it's unclear to me why a trait named as generally as `Contains` would provide a method that would take two values and check them *both*. Second, it's totally unclear to me why the two other methods use a specific type and not the `A` and `B` parameters or, really, why they are there at all. 🙂 It would seem to me a `Contains` trait would only provide a `contains` method and if it were to provide any other method, it'd be a derivative of the `contains` method, say, a `contains_all` method that takes an iterator of values? Whereas the method `first` and `last` do not seem to be even vaguely related to what it means for a *thing* to contain another *thing*.

The subchapter's part that describes associated types has the same definition, just that it showcases the use of associated types for `A` and `B`. As a side note, I think while it's a de facto standard to use single letters for type parameters, the guideline for naming associated types is to use full nouns.

I think we could come up with a much better example of how to use associated items that's more intuitive and conforms to good practices. Traits should not be used as a container for *freely hanging* methods – well, with a notable exception for `Ext`-family traits, which by definition are loose collections of *combinators* – but rather correspond to a specific *capability* that is provided with the means of a method or a number of methods, or a specific *characteristic* (like *Sync*) that describes a specific property of the type (in that case: that it's shareable between threads).

The `Graph` example in the first edition of the Rust Book is quite alright: https://doc.rust-lang.org/1.30.0/book/first-edition/associated-types.html.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
