### ISSUE TITLE
flow_control/for & instead of iter()

### ISSUE THREAD

**Issue by rusty-snake** [rust-lang/rust-by-example#1232]
[flow_control/for](https://github.com/rust-lang/rust-by-example/blob/9dfb263258514a30cbc29d646dba85afa9c588a9/src/flow_control/for.md) only talk about `for U in T.iter()` to get a Iterator with references, but I think it should also talk about `for U in &T`. Same for `iter_mut()`.

current code:
```rust
fn main() {
    let names = vec!["Bob", "Frank", "Ferris"];

    for name in names.iter() {
        match name {
            &"Ferris" => println!("There is a rustacean among us!"),
            _ => println!("Hello {}", name),
        }
    }
}
```
example of what should be added:
```rust
for name in &names {
    match name {
        &"Ferris" => println!("There is a rustacean among us!"),
        _ => println!("Hello {}", name),
    }
}
```
and a explanation.

<details><summary>

BTW: maybe `&"Ferris"` should be changed.

</summary>

Destructuring:
```rust
for name in &names {
    match name {
        "Ferris" => println!("There is a rustacean among us!"),
        _ => println!("Hello {}", name),
    }
}
```
Or

Dereferencing:
```rust
for name in &names {
    match *name {
        "Ferris" => println!("There is a rustacean among us!"),
        _ => println!("Hello {}", name),
    }
}
```

</details>

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
