### ISSUE TITLE
Out of date example in aliasing

### ISSUE THREAD

**Issue by malaire** [rust-lang/rust-by-example#1291]
The following example is out of date:
https://doc.rust-lang.org/rust-by-example/scope/borrow/alias.html

In current Rust references go out of scope at last use, not at block end, so following is incorrect:

>        // Error! Can't borrow `point` as mutable because it's currently
>        // borrowed as immutable.
>        //let mutable_borrow = &mut point;
>        // TODO ^ Try uncommenting this line
>
>        // Immutable references go out of scope

**Comment by marioidival** [comment]
@malaire Fix this for us?! 💃

**Comment by dalance** [comment]
@marioidival This issue seems to be fixed at https://github.com/rust-lang/rust-by-example/commit/d5b61effcb4219c914cbf15e50c894bed6ed7b46.
