### ISSUE TITLE
Don't reset Table of Contents sidebar when going to a new page.

### ISSUE THREAD

**Issue by dacut** [rust-lang/rust-by-example#1294]
When skimming through later chapters (anything below 6.2 on my screen), I have to scroll the table of contents down to get to the items. Once I click on the item of interest, however, the table of contents resets to the top, making skimming through a chapter tedious.

If I'm skimming through chapter 14 (Generics), for example, I have to scroll down, select a page, see it's not quite what I wanted, scroll back down, select another page, etc. If I were skimming sequentially, I could just use the left/right arrows; if I knew the exact text I'm looking for, I could search; but sometimes, there's something I'm looking for "that I remember seeing, but don't recall the exact words for, but remember seeing it in the Rust by Example book and it looked like X".

Is there an option to the HTML renderer you could set to enable this so it doesn't refresh the TOC sidebar each time it jumps to a page?

Thanks.

**Comment by steveklabnik** [comment]
Hi; this is a function of mdbook, our upstream project. I believe there's a bug open for this, but I cannot look it up right now. Regardless, you may want to go to their tracker. Thank you!

**Comment by dacut** [comment]
Thanks @steveklabnik -- looks like this is https://github.com/rust-lang/mdBook/issues/850
