### ISSUE TITLE
"TODO" suggestion doesn't seem to illustrate the point in types/alias

### ISSUE THREAD

**Issue by robstarling** [rust-lang/rust-by-example#1296]
In https://doc.rust-lang.org/rust-by-example/types/alias.html , it says

```
// Use an attribute to silence warning.
#[allow(non_camel_case_types)]
type u64_t = u64;
// TODO ^ Try removing the attribute
```
but removing the attribute does not result in the expected warning about a non-CamelCase type.

What should this page say and/or what would be a better example of this?

**Comment by ErikSwan** [comment]
I believe this is a duplicate of #1328.

**Comment by robstarling** [comment]
Agreed. Thanks!
