### ISSUE TITLE
testing/doc_testing: change markdown to commonmark

### ISSUE THREAD

**Issue by mvuets** [rust-lang/rust-by-example#1298]
The [Documentation testing](https://github.com/rust-lang/rust-by-example/blob/master/src/testing/doc_testing.md) page reads "Documentation comments are written in markdown". I believe it's been [replaced with CommonMark](https://doc.rust-lang.org/edition-guide/rust-2018/rustdoc/rustdoc-uses-commonmark.html) now.

**Comment by steveklabnik** [comment]
CommonMark *is* markdown, but sure, we could be more explicit about which form of markdown we support.
