### ISSUE TITLE
Implicit conversion and Inference - Requesting example

### ISSUE THREAD

**Issue by srikwit** [rust-lang/rust-by-example#1315]
In section 5.1 - Casting, it is mentioned that:
"Rust provides no implicit type conversion (coercion) between primitive types."

However, in section 5.3 - Inference, the following is mentioned:
"The type inference engine is pretty smart. It does more than looking at the type of the value expression during an initialization. It also looks at how the variable is used afterwards to infer its type."

Even though a vector is not a primitive type, it seems a bit unclear to me where a line is drawn between inference and then the actual casting. I would like to request an example explaining the same.

**Comment by steveklabnik** [comment]
They're just two completely different operations; casting turns one type into another type, inference figures out "what type is this".

**Comment by srikwit** [comment]
I'll use the same example as in the docs:

When a new Vector is created, 
`let mut vec = Vec::new();`
At that point, it's type inferred by the compiler is: `Vec<_>` 

When an unsigned integer: `let elem = 5u8;vec.push(elem);` is pushed into this vector.
The compiler now knows that it is a vector of unsigned integeres: `Vec<u8>`

I was trying to request for an explanation of this transition from `Vec<_>` to `Vec<u8>` (Inferring initially that it is a Vector (without a type) to finally casting it as an Vector of unsigned integers) and also why this implicit conversion worked for a non-primitive type but it might fail in case of primitive types.

**Comment by steveklabnik** [comment]
So the thing is, the compiler *always* has to know what the type of `T` in `Vec<T>` is. If you only have that first line, it'll fail to compile, saying it doesn't know.

None of this behavior at all has anything to do with casting.

**Comment by srikwit** [comment]
@steveklabnik request you to give me some time to close this issue.
