### ISSUE TITLE
Ch 8.5 match - incorrect reference to C switch

### ISSUE THREAD

**Issue by rimutaka** [rust-lang/rust-by-example#1353]
The opening statement in Ch. 8.5 match says:

> Rust provides pattern matching via the match keyword, which can be used like a C switch.

That comparison is incorrect - C-style switch/case requires _constant expressions_ available at compile time. See https://docs.microsoft.com/en-us/cpp/c-language/switch-statement-c

What would be helpful is to introduce the concept of "pattern match" first and then make a comparison with switch/case emphasizing the differences.

Any confusion about how pattern matching works blocks understanding of `if let` in the next section.

I am happy to attempt a re-write of https://doc.rust-lang.org/rust-by-example/flow_control/match.html.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
