### ISSUE TITLE
Ch. 8.6 `if let` doesn't mention assignment

### ISSUE THREAD

**Issue by rimutaka** [rust-lang/rust-by-example#1354]
An important part of `if let` statement is the assignment. E.g.

```
let some_u8_value = Some(3u8);
if let Some(i) = some_u8_value {
    println!("assigned {} to i", i);
}
```
outputs
```
assigned 3 to i
```

The assignment part is somewhat demonstrated in https://doc.rust-lang.org/rust-by-example/flow_control/if_let.html, but is buried deep in the code snippet

```
    // The `if let` construct reads: "if `let` destructures `number` into
    // `Some(i)`, evaluate the block (`{}`).
    if let Some(i) = number {
        println!("Matched {:?}!", i);
    }
```
and since no output is provided with the snippet the concept goes unnoticed and misunderstood.

The reference (https://doc.rust-lang.org/reference/expressions/if-expr.html) does not mention the assignment part at all.

I am happy to re-phrase that section if there is consensus on what needs to be done.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
