### ISSUE TITLE
Explain how patterns work in `match` and `if let`

### ISSUE THREAD

**Issue by rimutaka** [rust-lang/rust-by-example#1355]
Neither Rust Book nor Rust by Example explain how patterns work in `match` and `if let` sections.

The detailed explanation is provided in https://doc.rust-lang.org/reference/patterns.html

A summary of how patterns work and a link to the reference page from inside `match` and `if let` sections would help.

I am happy to give it a try if there is consensus on this issue.

**Comment by marioidival** [comment]
Yes, of course!

**Comment by Arpeet007** [comment]
May I work on this issue

**Comment by Arpeet007** [comment]
II'L Take that as a yes

**Comment by Arpeet007** [comment]
I Have Proposed The Necessary Changes please check into it and thanks

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
