### ISSUE TITLE
Drop extern crate

### ISSUE THREAD

**Issue by butlermatt** [rust-lang/rust-by-example#1358]
Hi Folk,

I'm still new to Rust, and when looking at Rust by Example section 11.2 it indicates that:

> To link a crate to this new library, the extern crate declaration must be used. This will not only link the library, but also import all its items under a module named the same as the library. The visibility rules that apply to modules also apply to libraries.

However I was under the impression that as of Rust 2018, the extern crate functionality was no longer _required_ (eg: the "must" key word here is no longer valid, and perhaps "may" is more applicable). Since 2015 and older syntax still use the extern crate, it is probably important to mention this functionality but perhaps demonstrate how it has now been superseded by the ability to import with use statements. In fact "The Book" now specifically states that it is "unidiomatic" to use extern crate. (https://doc.rust-lang.org/reference/items/extern-crates.html in the "Edition Differences" aside).

I feel these two areas should be brought in alignment with each other.

**Comment by steveklabnik** [comment]
Yes, this should be done. I'd happily accept a PR to do it.

**Comment by xiaochuanyu** [comment]
@steveklabnik I opened a PR to address this issue. I'm somewhat new to Rust so I would really appreciate your feedback on the PR if anything is wrong.
