### ISSUE TITLE
When are changes reflected the website

### ISSUE THREAD

**Issue by pdietl** [rust-lang/rust-by-example#1360]
I came here looking to make a PR, but the issue was already fixed. So when do the fixes here end up on https://doc.rust-lang.org/rust-by-example?

**Comment by mautamu** [comment]
It appears that rust-by-example rides the "release train" like other Rust tools and books: something on this repository is pushed to nightly generally every [~two weeks](https://github.com/rust-lang/rust/search?q=Update+books&type=commits) and then rides the beta until it makes it to stable (the link you posted) according to the usual Rust release schedule: https://forge.rust-lang.org/#current-release-versions .
