### ISSUE TITLE
Chapter 11 : Crates  ---- On the understanding of the concept of crate

### ISSUE THREAD

**Issue by Bert-King** [rust-lang/rust-by-example#1374]
In this book(Rust By Example),Chapter 11:
> A crate is a compilation unit in Rust. Whenever rustc some_file.rs is called, **some_file.rs is treated as the crate file**.

According to this book,   what about the source file ? 

[The Rust Reference | Crates and source files ](https://doc.rust-lang.org/reference/crates-and-source-files.html#phase-distinction)

>The compilation model centers on artifacts called crates. Each compilation processes a single crate in source form, and if successful, produces a single crate in binary form: either an executable or some sort of library.

>The Rust compiler is always invoked with a single source file as input, and always produces a single output crate. The processing of that source file may result in other source files being loaded as modules. Source files have the extension .rs.

According to this statement， I think: 
> Source file(.rs file) --> corresponding crate 
>
> Just like : .java --> .class

[How to better understand Crate in Rust?](https://stackoverflow.com/questions/63515853/how-to-better-understand-crate-in-rust/63516458#63516458)

**Comment by Bert-King** [comment]
@xiaochuanyu Thanks for your reply. In terms of the range , Crate > .rs files > modules

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
