### ISSUE TITLE
vec cant compile

### ISSUE THREAD

**Issue by samrrr** [rust-lang/rust-by-example#1376]
https://doc.rust-lang.org/stable/rust-by-example/std/vec.html
Code from this page have compile errors.

**Comment by steveklabnik** [comment]
This is on purpose, see for example:

```
    // Error! Immutable vectors can't grow
    collected_iterator.push(0);
    // FIXME ^ Comment out this line

```

you are intended to interact with the example.

Thanks!

**Comment by samrrr** [comment]
Exsample should compile. Because its example, not my not working program. 

Now i try run by press play and its cant be compiled. Because critical errors in code.

If example really need some not compilable code so not place its first on page.

I am come to this page for get some example code. I want compile and run its. I am not want see errors as in my program.

Watch cppreference for vector. Its have example. And its compiled sucessfull.
https://en.cppreference.com/w/cpp/container/vector

**Comment by samrrr** [comment]
Its still cant compile by press play on page.
