### ISSUE TITLE
non_exhaustive enum / struct

### ISSUE THREAD

**Issue by elpiel** [rust-lang/rust-by-example#1387]
It would be great if there are examples for both `enum` and `struct` for `non_exhaustive`.

What are your thoughts?

**Comment by skade** [comment]
Sure, feel free to send a pull request. It's a language feature worth documenting - sending an initial proposal makes the discussion easier on how it can be made worthwhile and clear!

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
