### ISSUE TITLE
Use of `use` declaration seems contradicting the rust lang book

### ISSUE THREAD

**Issue by ejez** [rust-lang/rust-by-example#1390]
Quoting from https://doc.rust-lang.org/rust-by-example/mod/use.html :

The `use` declaration can be used to bind a full path to a new name, for easier
access. **It is often used like this**:

```rust,editable,ignore
use crate::deeply::nested::{
    my_first_function,
    my_second_function,
    AndATraitType
};
```
================================================================
Now quoting from https://doc.rust-lang.org/stable/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html :

Although both Listing 7-11 and 7-13 accomplish the same task, Listing 7-11 is
the idiomatic way to bring a function into scope with `use`. **Bringing the
function’s parent module** into scope with `use` so we have to specify the parent
module when calling the function makes it clear that the function isn’t locally
defined while still minimizing repetition of the full path. The code in Listing
7-13 is unclear as to where `add_to_waitlist` is defined.

On the other hand, when bringing in structs, enums, and other items with `use`,
it’s idiomatic to specify the full path.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
