### ISSUE TITLE
Add an example of converting a string to an int

### ISSUE THREAD

**Issue by nham** [rust-lang/rust-by-example#140]
The Rust cheatsheet was recently removed (see [here](https://github.com/rust-lang/rust/issues/14380)) in favor of Rust by Example. One thing I used the cheatsheet for repeatedly, because I can never remember it for some reason, is how to convert a string to an int. Rust by Example does not appear to have such an example, or at least I was not able to find it by searching both on the site and on Github.

**Comment by maccoda** [comment]
@steveklabnik Just wanted to check did we need anything else to close this one off? :smile:

**Comment by steveklabnik** [comment]
We're good!
