### ISSUE TITLE
Interior Mutability

### ISSUE THREAD

**Issue by Lutetium-Vanadium** [rust-lang/rust-by-example#1403]
Interior Mutability is a somewhat obscure topic specific to rust (from what I know) and is not mentioned anywhere in this book. It is [briefly mentioned in the rust reference](https://doc.rust-lang.org/reference/interior-mutability.html), but I feel its an important topic that requires a better explanation that goes into why it came about and the problem it solves. When I discovered, the concept of interior mutability and `Cell` and `RefCell` while watching the [crust of rust video on it](https://youtu.be/8O0Nt9qY_vo), I found it really useful and wish I knew about it from the beginning. I personally think its a very important and uniquely rust concept, and while the [`std::cell` docs](https://doc.rust-lang.org/std/cell/index.html) has a good (somewhat technical) explanation for it, beginners (at least me) don't delve into the standard library docs to learn things...

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
