### ISSUE TITLE
squash `gh-pages` branch

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust-by-example#1407]
Currently, `rust-by-example` takes up over 146 MB just for the git history. It would be nice to reduce this so contributors to rust-lang/rust don't have to download as much data (https://github.com/rust-lang/rust/issues/76653#issuecomment-691696545).

You can squash the branch with (https://stackoverflow.com/questions/1657017/how-to-squash-all-git-commits-into-one/1661283#1661283)
```sh
git checkout gh-pages
git update-ref -d refs/heads/gh-pages
git commit -m "Redirect to doc.rust-lang.org"
```
then squash the history with `git gc --aggressive`. I verified locally that this reduces the size of .git to 84 MB. I'm not sure how to get github to run gc, I think you may have to wait for them to do it automatically (https://stackoverflow.com/a/9138899/7669110).

**Comment by jyn514** [comment]
@marioidival I saw you added a +1 - does that mean you squashed the branch? Can I make it easier somehow?

**Comment by jyn514** [comment]
bump - who should I talk to about this?

**Comment by jyn514** [comment]
Actually it looks like the `gh-pages` branch has been unused for a while, the last pages deploy was in 2018: https://github.com/rust-lang/rust-by-example/deployments/activity_log?environment=github-pages. I think just deleting the branch altogether should be fine.

**Comment by Mark-Simulacrum** [comment]
Pushed, I believe, the squashed version of gh-pages. Seems to have cut the size down to ~4.7MB on a fresh clone.

**Comment by jyn514** [comment]
Thank you!

**Comment by jyn514** [comment]
That worked like a charm, thank you so much!
```
$ x check
Updating only changed submodules
Updating submodule src/doc/rust-by-example
Submodule 'src/doc/rust-by-example' (https://github.com/rust-lang/rust-by-example.git) registered for path 'src/doc/rust-by-example'
Cloning into '/home/joshua/src/rust/rustc2/src/doc/rust-by-example'...
remote: Enumerating objects: 12809, done.        
remote: Counting objects: 100% (119/119), done.        
remote: Compressing objects: 100% (110/110), done.        
remote: Total 12809 (delta 59), reused 13 (delta 8), pack-reused 12690        
Receiving objects: 100% (12809/12809), 3.06 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (6985/6985), done.
Submodule path 'src/doc/rust-by-example': checked out 'c80f0b09fc15b9251825343be910c08531938ab2'
Submodules updated in 1.98 seconds
```
