### ISSUE TITLE
Wording in Unsafe, Option, Compatibility

### ISSUE THREAD

**Issue by wkarshat** [rust-lang/rust-by-example#1421]
https://doc.rust-lang.org/rust-by-example/unsafe.html
 (including calling a [function over](https://doc.rust-lang.org/rust-by-example/std_misc/ffi.html) FFI)

https://doc.rust-lang.org/rust-by-example/error/option_unwrap.html
In the _next_ example, we _show inducing_ program failure at will. Our program _panics_ if the royal received an inappropriate gift - a snake. But what if the royal expected a gift and didn't receive one? That case would be just as bad, _and_ needs to be handled!

https://doc.rust-lang.org/rust-by-example/compatibility.html
The Rust language is evolving _rapidly_, so certain compatibility issues _may_ arise, despite efforts to ensure _backward_ * compatibility.

* My understanding is that a later version of the compiler introducing a new keyword breaks [backward compatibility](https://en.wikipedia.org/wiki/Forward_compatibility), and raw identifiers is a workaround.

My apologies for recording an Issue rather than submitting a PR, but not being familiar with how things are done in this project, simply wanted to capture some nits, lest I forget.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
