### ISSUE TITLE
6.3 To and from Strings: a misspelling

### ISSUE THREAD

**Issue by ygidtu** [rust-lang/rust-by-example#1444]
I found a misspelling of `automatically` in https://doc.rust-lang.org/rust-by-example/conversion/string.html.

The last word of second row: automagically .

![image](https://user-images.githubusercontent.com/29178828/123044042-bdec6300-d42b-11eb-9548-9b841771f787.png)

**Comment by jbiason** [comment]
"Automagical" is a jargon word for something that's so awesome that feels magical. [Wikitionary has an entry for it](https://en.wiktionary.org/wiki/automagical).

But yeah, dunno if it is a good idea to use a word whose meaning is not widely know these days...

**Comment by ygidtu** [comment]
Ohh, learning somthing new everyday.  Sorry to borther, maye you could label the meaning next to it.
