### ISSUE TITLE
Three types of structs

### ISSUE THREAD

**Issue by valentinoli** [rust-lang/rust-by-example#1445]
In the section about [Structures](https://github.com/rust-lang/rust-by-example/blob/805e016c5792ad2adabb66e348233067d5ea9f10/src/custom_types/structs.md), *three* types of structs are introduced and only two of them are explained in the following bullet points.

**Comment by alexfertel** [comment]
I noticed this too yesterday. It was a bit confusing to me. I can try to fix this if someone helps me!

**Comment by colejohnson66** [comment]
This appears to have been fixed in 1ff687f, and just hasn’t been built and pushed to the server yet.
