### ISSUE TITLE
404 when opening https://rustbyexample.com 

### ISSUE THREAD

**Issue by memoryruins** [rust-lang/rust-by-example#1454]
Previously https://rustbyexample.com/ would redirect to https://doc.rust-lang.org/rust-by-example (as well as desired paths since #1083), but now it leads to a 404. Is this expected?

**Comment by yvt** [comment]
`rustbyexample.com` is now deployed from a seemingly unrelated repo [invisiblethings/demowp](https://github.com/invisiblethings/demowp/blob/80e9111c0b2e4692a145e3a146703fe94a540efb/CNAME#L1), which looks like a case of domain hijacking.

**Comment by yvt** [comment]
Commit a4b2516e525f48a1967e3077e58deea01784cdd9 introduced a publish-to-GHP CI step, which pushed commit 30066efd0a36f73f1f97187f2a5374ffd3ec0b46 to `gh-pages`, erasing `CNAME`. The new CI step was  immediately removed by commit ba6647c8a67fc010510c34c7bac6b1bbc5e04454, but the damage made to `gh-pages` wasn't undone. I think this is why we lost the redirection page.

**Comment by yvt** [comment]
It looks like ✨our new shiny sponsor✨ fixed the issue for us:

<img width="954" alt="Screen Shot 2021-11-10 at 12 32 39" src="https://user-images.githubusercontent.com/5253988/141044955-729e4dba-6d54-41a5-b515-7e8b6f520fb8.png">
