### ISSUE TITLE
Explain how to implement `Error` trait for custom error types

### ISSUE THREAD

**Issue by Kiiyya** [rust-lang/rust-by-example#1455]
I have noticed that the [Defining an error type](https://doc.rust-lang.org/rust-by-example/error/multiple_error_types/define_error_type.html) docs do not implement the `Error` trait, and so I assumed that it is unusual to implement the `Error` trait for your custom errors. Until someone pointed out to me that custom errors should implement `Error`.

Can we explain why / why not to implement `Error` for custom types, either on that page, or on a new page? And can we show a canonical way of implementing `Error` (since there seems to be a few deprecated functions in the trait), and maybe explain how error handling libraries like `snafu` etc use `Error`?

Kthxbai.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
