### ISSUE TITLE
Documentation example contains non-standard `Arguments` section

### ISSUE THREAD

**Issue by Skepfyr** [rust-lang/rust-by-example#1457]
The documentation example is `src/meta/doc.md` on `Person::new` looks like:
```rust
    /// Returns a person with the name given them
    ///
    /// # Arguments
    ///
    /// * `name` - A string slice that holds the name of the person
    ///
    /// # Examples
    ///
    /// ```
    /// // You can have rust code between fences inside the comments
    /// // If you pass --test to `rustdoc`, it will even test it for you!
    /// use doc::Person;
    /// let person = Person::new("name");
    /// ```
```
As far as I am aware the `Arguments` section is non-standard (and recommended against?), I've definitely never seen it in the standard library or any of the most popular crates. I think it could just be removed, maybe even replaced by an example with the headings suggested by [RFC 1574](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#using-markdown-1): Examples, Panics, Errors, Safety, Aborts, Undefined Behavior. (Maybe not all at once!)

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
