### ISSUE TITLE
9.2.6.1 Iterator::any

### ISSUE THREAD

**Issue by 2moe** [rust-lang/rust-by-example#1460]
https://github.com/rust-lang/rust-by-example/blob/master/src/fn/closures/closure_examples/iter_any.md
```
 // `into_iter()` for arrays unusually yields `&i32`.
    println!("2 in array2: {}", array2.into_iter().any(|&x| x == 2));
```
It is wrong.
___
It should be **x**, not **&x**.

Since `fn into_iter(self) -> Self::IntoIter`,
 please change it to look like this.

```
 // `into_iter()` for arrays unusually yields `i32`.
    println!("2 in array2: {}", array2.into_iter().any(|x| x == 2));
```

**Comment by 2moe** [comment]
There is a similar error in [9.6.2.2](https://doc.rust-lang.org/rust-by-example/fn/closures/closure_examples/iter_find.html).
Original:
```
 println!("Find 2 in array2: {:?}", array2.into_iter().find(|&&x| x == 2));
```
The correct one is this:
```
 println!("Find 2 in array2: {:?}", array2.into_iter().find(|&x| x == 2));
```

**Comment by marioidival** [comment]
This one was fixed, thank you!
