### ISSUE TITLE
Replace Option::map_or to Option::transpose to pull result from option

### ISSUE THREAD

**Issue by artslob** [rust-lang/rust-by-example#1475]
In [Pulling Results out of Options](https://github.com/rust-lang/rust-by-example/blob/e9d45342d7a6c1def4731f1782d87ea317ba30c3/src/error/multiple_error_types/option_result.md) pulling result is achived using `map_or`, but same can be achieved using `transpose` method in more simple and convenient way.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
