### ISSUE TITLE
Error in 9.2.6.1: mismatched types

### ISSUE THREAD

**Issue by euberdeveloper** [rust-lang/rust-by-example#1491]
In the example of https://doc.rust-lang.org/rust-by-example/fn/closures/closure_examples/iter_any.html

I have this error:

![image](https://user-images.githubusercontent.com/33126163/148565993-ff2157cd-e5ae-4136-9ff4-d415859f2baa.png)

```
mismatched types

expected integer, found reference

note:   expected type `{integer}`
      found reference `&_`rustc(E0308)
```

That can be solved by removing the last `&` on `|&x|`

**Comment by euberdeveloper** [comment]
A very similar issue is in 9.2.6.2 (https://doc.rust-lang.org/rust-by-example/fn/closures/closure_examples/iter_find.html)

**Comment by marioidival** [comment]
@euberdeveloper this one was fixed and today we didn't get error anymore
