### ISSUE TITLE
Testcase: List - Playground Communication Timeout

### ISSUE THREAD

**Issue by Kaszanas** [rust-lang/rust-by-example#1492]
Dear maintainers,

While checking out the resources on Rust language I have stumbled upon the error that is mentioned in the title of the issue.

Attempting to run the code that is here:
https://github.com/rust-lang/rust-by-example/blob/master/src/hello/print/print_display/testcase_list.md

Ends up in:
```Playground Communication: timeout```

**Comment by marioidival** [comment]
Hi @Kaszanas how are you? Thank you for reporting this. I'd tried, but I didn't get this error. Could you try again please?

**Comment by Kaszanas** [comment]
Hello @marioidival 

I am unable to reproduce the error. I have no idea what caused it in the first place.
The issue seems to have resolved itself.

**Comment by marioidival** [comment]
@Kaszanas thank you!
