### ISSUE TITLE
alias: mention how to actually create new types

### ISSUE THREAD

**Issue by vks** [rust-lang/rust-by-example#151]
I'm not sure whether the current example is a good idea, because it exercises a `bad practice` that results in something you would not want to do. (That is adding quantities in wrong units.)

At least it should be mentioned how the unit example can actually be implemented correctly (I think the idiomatic way is to use one-field structs).

Also see https://blog.mozilla.org/research/2014/06/23/static-checking-of-units-in-servo/.

**Comment by steveklabnik** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust-by-example/issues/174
