### ISSUE TITLE
"Freezing" seems confusing

### ISSUE THREAD

**Issue by marcoow** [rust-lang/rust-by-example#1516]
I'm just going through Rust by example and was wondering about ["Freezing"](https://doc.rust-lang.org/rust-by-example/variable_bindings/freeze.html) when I got to that. It seems what happens in the example

```rust
fn main() {
    let mut _mutable_integer = 7i32;

    {
        let _mutable_integer = _mutable_integer;

        _mutable_integer = 50;
        // FIXME ^ Comment out this line
    }

    // Ok! `_mutable_integer` is not frozen in this scope
    _mutable_integer = 3;
}
```

is that in the block a **new** variable is introduced that's initialized with the **value** of another one. The fact that the `_mutable_integer` in the outer scope is mutable seems irrelevant?

So essentially when reading this I was wondering whether "freezing" was even a concept of its own in Rust or what's being described is just behavior that results out of other concepts in the language?

Please not I'm still relatively new to Rust and might just be missing something here (which could mean though that if the example was changed to make the point clearer, people like me would be less likely to be missing the point here :) )

**Comment by niklaslong** [comment]
I think it's just meant to be a demonstration of how "scoped shadowing" works. Consider an example where the inner variable is made mutable:
```rust
fn main() {
    let mut _mutable_integer = 7i32;

    {
        let mut _mutable_integer = _mutable_integer;

        _mutable_integer = 50;
        
        println!("{_mutable_integer}");
        // Prints 50.
        
    }
    
    println!("{_mutable_integer}");
    // Prints 7. 
}
```

They may have called it freezing because while the variable in the outer scope is shadowed by the one in the inner scope, its value can't be accessed or modified, but it can be once the scope is closed. 

If you assign an exclusive reference to the inner var, you get this however: 

```rust
fn main() {
    let mut _mutable_integer = 7i32;

    {
        // Note that you don't need the `mut` because you're storing the pointer and not the value.
        let _mutable_integer = &mut _mutable_integer;

        *_mutable_integer = 50;
        
        println!("{_mutable_integer}");
        // Prints 50.
        
    }
    
    println!("{_mutable_integer}");
    // Prints 50. 
}
```

**Comment by marcoow** [comment]
Yes, that's what I mean – nothing ever seem to get _"frozen"_ at any point and it's just implications of the shadowing mechanism? So I think that's what I found confusing: the introduction of _"freezing"_ as a concept of its own seems to imply that there's somehow more to it than what you describe above and it remains unclear what that could me which makes you think you're missing something (while it seems like there just isn't anything beyond variable shadowing at play here in reality).

**Comment by Spoonbender** [comment]
It seems that the concept / idiom of "freezing" / "frozen data" / "frozen values" etc. isn't common among (yet), but it does seem to appear outside of RBE:
- [The Frozen data structure](https://doc.rust-lang.org/beta/nightly-rustc/rustc_data_structures/frozen/index.html)
- [The elsa crate of frozen collection types](https://github.com/Manishearth/elsa)
- [rust issue: Request: Make std::marker::Freeze pub again](https://github.com/rust-lang/rust/issues/60715)
- [rust issue: add share kind](https://github.com/rust-lang/rust/issues/11781) - contains a discussion about the previously-present Freeze

And while the discussed Freeze is different than the "freezing" technique in this page, it does imply that "freezing" as a concept exists, at least in some minds. [See this comment in particular](https://github.com/rust-lang/rust/issues/11781#issuecomment-36231482).

And it does seem there is such an idiom in other programming languages or ecosystems:
- [example 1](https://baites.github.io/computer-science/idioms/2019/08/16/constant-and-frozen-variable-in-python.html)
- [example 2](https://www.freecodecamp.org/news/javascript-immutability-frozen-objects-with-examples/)
- [example 3](https://www.educative.io/answers/how-to-freeze-objects-in-ruby)

All of this is to say that perhaps freezing in Rust isn't a common or very well defined concept, but I do think there is room for it in our vocabulary and exemplar.

**Comment by marcoow** [comment]
@Spoonbender "Freezing" definitely exists as a concept in general which is why I found this extra confusing – all of the examples you share are very different from what's explained in the above example (as you say).

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
