### ISSUE TITLE
slice needs length 

### ISSUE THREAD

**Issue by Masber** [rust-lang/rust-by-example#1531]
Hi,

this page https://doc.rust-lang.org/rust-by-example/primitives/array.html says:

> Slices are similar to arrays, but their length is not known at compile time. Instead, a slice is a two-word object, the first word is a pointer to the data, and the second word is the length of the slice

I don't understand why we need to specify the length of a slice since its length is unknown during compilation time?

I believe this is a typo since I can see in the example:

```
slice: &[i32]
```

**Comment by balroggg** [comment]
@Masber This is just a brief explanation. You don't need to specify the length of a slice. Slices are just represented as a pointer and a length.
