### ISSUE TITLE
Std misc> Threads> Testcase: map-reduce> See also: Wrong link

### ISSUE THREAD

**Issue by es-repo** [rust-lang/rust-by-example#1533]
`Std misc> Threads> Testcase: map-reduce> See also` section has wrong link for `turbofish notation`.

**Comment by dineshUmasankar** [comment]
Will this link suffice for turbofish notation?
https://doc.rust-lang.org/book/appendix-02-operators.html?highlight=turbofish

From the Appendix of The Rust Book,
| **Symbol** 	| **Explanation** 	|
|:---:	|---	|
| `path::<...>`, <br>`method::<...>` 	| Specifies parameters to generic type, function, or method in an expression; often referred to as turbofish (e.g., `"42".parse::())` 	|
