### ISSUE TITLE
Guards example may be confusing

### ISSUE THREAD

**Issue by skade** [rust-lang/rust-by-example#1539]
In https://doc.rust-lang.org/rust-by-example/flow_control/match/guard.html, it is stated that:

> Note that the compiler does not check arbitrary expressions for whether all possible conditions have been checked. Therefore, you must use the _ pattern at the end.

I was teaching a class today where someone interpreted this sentence as `_` being mandatory when using guard expressions. They were weirded out because of an example where I bound to a variable instead (bc. the guards weren't covering) and didn't know that was possible.

**Comment by balroggg** [comment]
@skade In this case the compiler can not guarantee a matching pattern. Maybe the example should be
```
_ => unreachable!("Negative number is not supported"),
```
to indicate error case

**Comment by xiaochuanyu** [comment]
@skade / @balroggg I made a [PR ](https://github.com/rust-lang/rust-by-example/pull/1550) to try address this.
Take a look and let me know what you think.

**Comment by balroggg** [comment]
@xiaochuanyu LGTM
