### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by chinhnotional** [rust-lang/rust-by-example#1546]
Hi Rust community,
I am a Cosmos blockchain engineer from Vietnam. I'm using Rust to develop many Cosmwasm smart contract for real projects. Translate this book while also learning it at the same time sound good for improving our skill on Rust. Now, there's no translation to the Vietnamese language yet so I’d like to translate the book into the Vietnamese.
I create my repo as [EyesCrypto-Insights/rust-by-example-vn](https://github.com/EyesCrypto-Insights/rust-by-example-vn) to be a source and cooperation place for translating the book.

Any help is always welcome!

**Comment by marioidival** [comment]
Hello @chinhnotional, how are you? It's awesome! Can you create a PR add this version on README file?

**Comment by chinhnotional** [comment]
Hello @marioidival, I'm very happy to receive your feedback, I will make a pull request to add this version. <3

**Comment by chinhnotional** [comment]
Hey, this is my PR. Thank you.
https://github.com/rust-lang/rust-by-example/pull/1561

**Comment by marioidival** [comment]
Thanks
