### ISSUE TITLE
Arc example rarely executes all threads

### ISSUE THREAD

**Issue by c-antin** [rust-lang/rust-by-example#1557]
Running the example of [Arc](https://doc.rust-lang.org/stable/rust-by-example/std/arc.html) results in a variing number of prints.

Is this a bug in rust or is `thread::spawn` not used correctly/up-to-date? Sometimes there are even incomplete prints:
![image](https://user-images.githubusercontent.com/38494182/174658529-53418994-ca48-4052-99af-4bd0414aa4bb.png)

**Comment by c-antin** [comment]
This way all threads are waited for:
```Rust
use std::sync::Arc;
use std::thread;

fn main() {
    // This variable declaration is where its value is specified.
    let apple = Arc::new("the same apple");

    let mut threads: Vec<thread::JoinHandle<()>> = vec![];

    for _ in 0..10 {
        // Here there is no value specification as it is a pointer to a reference
        // in the memory heap.
        let apple = Arc::clone(&apple);

        threads.push(thread::spawn(move || {
            // As Arc was used, threads can be spawned using the value allocated
            // in the Arc variable pointer's location.
            println!("{:?}", apple);
        }));
    }

    for handle in threads {
        handle.join().unwrap();
    }
}
```

**Comment by Rqnsom** [comment]
Hi c-antin,

I've updated this just recently, but without using `join` function, but with `sleep` instead:

> Joining threads could be used, but that concept is later introduced in 20.1. Threads, so I prefer simple sleep here. 

See my PR for more:
https://github.com/rust-lang/rust-by-example/pull/1552#discussion_r898139126

**Comment by Rqnsom** [comment]
Should we then close this issue?

**Comment by marioidival** [comment]
Yes! Thanks for that @Rqnsom and @c-antin
