### ISSUE TITLE
Extra curly braces on line 12 to 17 on the example website?

### ISSUE THREAD

**Issue by saikatdas0790** [rust-lang/rust-by-example#1605]
https://github.com/rust-lang/rust-by-example/blob/d1db42ff02be274dd387448f9f9ab605206d9338/src/macros/variadics.md?plain=1#L12-L17

The double curly braces on line 12 and 17 are not present in the source code but is present in the example on the website [here](https://doc.rust-lang.org/stable/rust-by-example/macros/variadics.html)

Maybe the site deployment isn't current?

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
