### ISSUE TITLE
obsolete entry about "playpen"

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust-by-example#1621]
https://doc.rust-lang.org/stable/rust-by-example/meta/playpen.html

It refers to it as "playpen", but the playpen project is now deprecated (https://github.com/rust-lang/rust-playpen), and now the Rust Playground is based on an entirely different repo (https://github.com/integer32llc/rust-playground).

You should remove references to Playpen, and link to the new repo instead. Consider altogether eliminating the term "playpen" and replacing every occurrence thereof with "Rust Playground" and then check to make sure that it doesn't sound awkward and make any adjustments to fulfil that end.

**Comment by marioidival** [comment]
No more references to playpen!
