### ISSUE TITLE
[Examples 2.3 Arrays and Slices] Comment error

### ISSUE THREAD

**Issue by DanWillans** [rust-lang/rust-by-example#1627]
On the arrays and slices page https://doc.rust-lang.org/rust-by-example/primitives/array.html the final `println!` statement says `Out of bound indexing causes compile error` but the program compiles fine. Instead, the programs main thread panics with an `index out of bounds: the len is 5 but the index is 5`. 

```
    // Out of bound indexing causes compile error
    // println!("{}", xs[5]);
```

Should this comment be corrected?

**Comment by marioidival** [comment]
Hi, thanks for pointing out. This was fixed https://github.com/rust-lang/rust-by-example/pull/1626/files

**Comment by majdus** [comment]
Sorry to comment on closed issue.
In fact the given example didn't cause a compile time error.
However rust compiler is supposed to be able to detect out of bound error.
By the way the following example causes a compile error:
`fn main() {
    // Fixed-size array (type signature is superfluous)
    let xs: [i32; 5] = [1, 2, 3, 4, 5];

    println!("{}", xs[5]);
}
`
