### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by adrian5** [rust-lang/rust-by-example#1653]
Hello @marioidival, I saw that you're the [sole](https://www.rust-lang.org/governance/wgs/wg-rust-by-example) maintainer of this repo. I'm interested in joining and taking care of some of the backlog, as well as handling future PRs. Let me know how to proceed. Thanks!

**Comment by marioidival** [comment]
@adrian5 hey, nice! I'll chat about that and I'll let you know. But for sure you can start from now
