### ISSUE TITLE
RBE is not deployed to production recently

### ISSUE THREAD

**Issue by mdu-alt** [rust-lang/rust-by-example#1670]
Hello,

Unless I'm mistaken, it looks like that RBE has not been deployed to production (i.e., to https://doc.rust-lang.org/rust-by-example) since commit 03491f33375c5a2a1661c7fa4be671fe95ce1249 (Oct 21, 2022), after which (chronologically) I started to find some discrepancies...

Thanks,
-Matthieu

**Comment by marioidival** [comment]
@mdu-alt hello, how are you? It's not true. The RBE is deployed just when a new release of Rust is released.

I'll close this issue, but if you have more question, just let me know!

Best

**Comment by mdu-alt** [comment]
Hi @marioidival, thanks for your quick reply.

For the sake of completeness, I'll just point out below one diff I found between website content and repo content.

Take for instance the file https://github.com/rust-lang/rust-by-example/src/hello/print.md, lines 34 to 40:
```rust
    // Different formatting can be invoked by specifying the format character
    // after a `:`.
    println!("Base 10:               {}",   69420); // 69420
    println!("Base 2 (binary):       {:b}", 69420); // 10000111100101100
    println!("Base 8 (octal):        {:o}", 69420); // 207454
    println!("Base 16 (hexadecimal): {:x}", 69420); // 10f2c
    println!("Base 16 (hexadecimal): {:X}", 69420); // 10F2C
```

Those lines are different from the ones in the website (https://doc.rust-lang.org/rust-by-example/hello/print.html) -- notice the first comment flow, and the spaces between `//` and the literal values:
```rust
    // Different formatting can be invoked by specifying the format character after a
    // `:`.
    println!("Base 10:               {}",   69420); //69420
    println!("Base 2 (binary):       {:b}", 69420); //10000111100101100
    println!("Base 8 (octal):        {:o}", 69420); //207454
    println!("Base 16 (hexadecimal): {:x}", 69420); //10f2c
    println!("Base 16 (hexadecimal): {:X}", 69420); //10F2C
```

Those changes were brought in 81c7b520459ee0e49708d013c3969dd4e597bbce (merged Dec 8, 2022), so I'd expect they are on the website, and are not.

Also, what do you mean by "new release of Rust is released"? Is it for major, minor or patch version update? Because last minor one (https://github.com/rust-lang/rust/blob/master/RELEASES.md) was on 2022-12-15, so it should have included previous commit.

Thanks again!
