### ISSUE TITLE
Incorrect indicating comment

### ISSUE THREAD

**Issue by woofyzhao** [rust-lang/rust-by-example#1671]
### File
src/types/cast.md

### Problematic Lines
```rust
// -100.0 as u8 is 156
println!("-100.0 as u8 is : {}", (-100.0_f32).to_int_unchecked::<u8>());
```

### Actual Output
```
-100.0 as u8 is : 0
```

### Environment
cargo 1.65.0
Apple M1 Pro / macOS Monterey 12.5.1

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
