### ISSUE TITLE
The "Efficient method" and "Beginner friendly method" seem essentially the same here.

### ISSUE THREAD

**Issue by woofyzhao** [rust-lang/rust-by-example#1677]
https://doc.rust-lang.org/rust-by-example/std_misc/file/read_lines.html

They are actually the same except that the "Efficient method" wraps the ```Lines``` object in a ```Result```...

**Comment by woofyzhao** [comment]
@FritteX14  Please take a look at this. It does not seem to have anything to do with _efficiency_.

**Comment by FritteX14** [comment]
Hey,
The reason for this change was to give Rust beginners code that's simple to understand. I use 'efficient' here to mean things like good code organization, readability, and being in line with how Rust is usually written, not how fast it runs. If it's bugging you, you can change it to "This method is NOT idiomatic." or something similar, but I still reckon using 'efficient' makes it easiest to explain to someone new to Rust, or programming in general. Hope this helps ;)

**Comment by woofyzhao** [comment]
> Hey, The reason for this change was to give Rust beginners code that's simple to understand. I use 'efficient' here to mean things like good code organization, readability, and being in line with how Rust is usually written, not how fast it runs. If it's bugging you, you can change it to "This method is NOT idiomatic." or something similar, but I still reckon using 'efficient' makes it easiest to explain to someone new to Rust, or programming in general. Hope this helps ;)

Thank you for your explanation.
