### ISSUE TITLE
15.4.1 wrong wording?

### ISSUE THREAD

**Issue by OBorce** [rust-lang/rust-by-example#1684]
```Rust
fn failed_borrow<'a>() {
    let _x = 12;

    // ERROR: `_x` does not live long enough
    let y: &'a i32 = &_x;
    // Attempting to use the lifetime `'a` as an explicit type annotation 
    // inside the function will fail because the lifetime of `&_x` is shorter
    // than that of `y`. A short lifetime cannot be coerced into a longer one.
}
```
Shouldn't it say:
"because the lifetime of `&_x` is shorter than that of `a` " instead of `y` ?

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
