### ISSUE TITLE
Unfortunate example in Lifetime Bounds chapter

### ISSUE THREAD

**Issue by Mingun** [rust-lang/rust-by-example#1686]
The following example does not show any special properties of `Trait + 'a` construct, because code is compile even when you remove `+ 'a`:
https://github.com/rust-lang/rust-by-example/blob/af0998b7473839ca75563ba3d3e7fd0160bef235/src/scope/lifetime/lifetime_bounds.md?plain=1#L29-L35

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
