### ISSUE TITLE
Run rust code in the web client

### ISSUE THREAD

**Issue by tdelmas** [rust-lang/rust-by-example#1689]
Would it be possible to run the exercises directly in the client using WebAssembly? (both the rust compilation and running the compiled code)

It's now wildly available https://caniuse.com/wasm (and the back-end compilation/run could be kept as a fall-back)

It would improve the privacy or the users. 

Related: #314

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
