### ISSUE TITLE
Improve offline usability by using relative links?

### ISSUE THREAD

**Issue by kaycebasques** [rust-lang/rust-by-example#1691]
There are a lot of links to the official Rust API docs throughout RBE. Example:

```
// ...

Printing is handled by a series of [`macros`][macros] defined in
[`std::fmt`][fmt] some of which include:

// ...

[fmt]: https://doc.rust-lang.org/std/fmt/

// ...
```

https://github.com/rust-lang/rust-by-example/blob/master/src/hello/print.md?plain=1#L109

The fact that RBE works offline is a great feature. But all of the full URL paths to the API docs are broken for offline readers.

If we convert these to relative paths it should still work for online readers, while also providing a better experience for offline readers:

```
// ...

Printing is handled by a series of [`macros`][macros] defined in
[`std::fmt`][fmt] some of which include:

// ...

[fmt]: ../../../std/fmt/index.html

// ...
```

I can help out with this but I will wait for a confirmation from you all first.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
