### ISSUE TITLE
Change prefix to suffix

### ISSUE THREAD

**Issue by anorakk8** [rust-lang/rust-by-example#1708]
On this page [https://doc.rust-lang.org/rust-by-example/primitives/literals.html](url) of the Rust By Example section, it is mentioned, 

> Integers can, alternatively, be expressed using hexadecimal, octal or binary notation using these prefixes respectively: 0x, 0o or 0b.

I believe prefixes should be changed to suffixes since the integer notations are using x, o and b after the integer not before it.

**Comment by Spoofardio** [comment]
@anorakk8 The doc doesn't seem to have an example but term prefix is correct. As an example `let a = 0x12;` (aka 18) would represent a hexadecimal number because the prefix 0x is present before the number.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
