### ISSUE TITLE
github-pages Jul 13, 2021 later not deploy is this normal?

### ISSUE THREAD

**Issue by MABIY** [rust-lang/rust-by-example#1722]

**Comment by marioidival** [comment]
Yes, RBE is deployed by another approach.

**Comment by MABIY** [comment]
how to know what is deploy, looks master branch commit not  trigger deploy .

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
