### ISSUE TITLE
Cover the newtype idiom

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#174]
This idiom allows really nice function signatures with zero cost abstraction. For example, see these [function signatures](https://github.com/japaric/criterion.rs/blob/master/src/statistics/sample.rs#L49) I came up with to do some statistics operations - it reminds me of readable Haskell function signatures like `compute :: Sample -> Statistic -> Float`.

Also the newtype idiom can be used with phantom types for extra type safety (like unit checking). So it may be a good idea to introduce this idiom before phantom types.

cc #145 #151 
cc @mdinger

**Comment by steveklabnik** [comment]
I'd be happy to mentor anyone who wants to work on this!

**Comment by gurgalex** [comment]
Hi @steveklabnik , 

I'd be happy to help, but how?

From [what I can tell](https://github.com/jaheba/stuff/blob/master/communicating_intent.md#newtypes), the new type idiom adds meaning to a value by communicating what it is (km, miles, temp type, etc).
From
