### ISSUE TITLE
Markdown warning in hello.md

### ISSUE THREAD

**Issue by tmollov** [rust-lang/rust-by-example#1751]
Hi Rustaceans,

Currently translating this book to Bulgarian language and i encountered a warning from markdown:
this is the warning:
`MD001/heading-increment/header-increment: Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]`
at Line 39 from [THIS](https://github.com/rust-lang/rust-by-example/blob/master/src/hello.md) file.

With `mdbook serve` i can't see the difference in it after changing it to H2, at least it look same to me in the browser.

Is there a reason for that or it is just a typo in the doc?

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
