### ISSUE TITLE
"superflous" is somehow misleading

### ISSUE THREAD

**Issue by kberov** [rust-lang/rust-by-example#1770]
In the [channels](https://github.com/rust-lang/rust-by-example/blame/6af3f81ea643da9d877b08090a70ce9a8bb90605/src/std_misc/channels.md#L17) section, line 17 we read.
`// (type annotation is superfluous)`.
I understand it as "nod needed". When I remove the type annotation, the program cannot be compiled.
Does it actually mean "more than enough"?

**Comment by marioidival** [comment]
I don't think so: I've just executed this one without the type annotation and everything goes well.
