### ISSUE TITLE
Vecors example does not compile, requires mut

### ISSUE THREAD

**Issue by GunterSchmidt** [rust-lang/rust-by-example#1799]
https://doc.rust-lang.org/rust-by-example/std/vec.html

Compiling playground v0.0.1 (/playground)
error[E0596]: cannot borrow `collected_iterator` as mutable, as it is not declared as mutable
  --> src/main.rs:16:5
   |
16 |     collected_iterator.push(0);
   |     ^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
   |
help: consider changing this to be mutable
   |
3  |     let mut collected_iterator: Vec<i32> = (0..10).collect();
   |         +++

**Comment by marioidival** [comment]
Hi @GunterSchmidt, the idea of this snippet is just for you as a learner to change the line and see how it goes.

```rust
    // Error! Immutable vectors can't grow
    collected_iterator.push(0);
    // FIXME ^ Comment out this line
```

**Comment by GunterSchmidt** [comment]
ups, sorry. Used it as a language reference, not a language course.
