### ISSUE TITLE
Code compilation error(Under 1.2 Formatted print section)

### ISSUE THREAD

**Issue by 0xmuon** [rust-lang/rust-by-example#1840]
line 37 shows error. (The code was **default displayed**, nothing was changed in the code.)

![image](https://github.com/rust-lang/rust-by-example/assets/127816064/5a450543-7cb2-4503-96f3-be0e81423f57)

**Comment by snailtomatoes** [comment]
This is working as intended, the comments under the line 37 states:
`// FIXME ^ Add the missing argument: "James"`

Towards the end of the page in the section "Activities" is stated that correcting the error is the first exercise.

Some errores are there by default for you to correct and are part of the example/exercise.

**Comment by 0xmuon** [comment]
Sorry for not going through all the docs. Thanks for letting me know.
