### ISSUE TITLE
Topics for the formatting chapter

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#196]
- [x] How to manually implement the `Show` trait, and access the `{}` formatter
- [x] A full list of (formatting) argument types
- [ ] Implementing more than one formatting trait. I think we could reuse the example about the latitude/longitude of a city. We could offer two formats: `12.345° N` (floating) and `12° 23' 34"` (default).
- [ ] [`Formatter::pad`](http://doc.rust-lang.org/core/fmt/struct.Formatter.html#method.pad), important to make `{:>5}` and `{:<3}` work on a custom `Show` implementation.
- [ ] Precision, how to implement `{:0.5}` and `{:0.03}`?
- [ ] `fmt::Result`, what kind of errors could arise from formatting?

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
