### ISSUE TITLE
RFC: New category - Container Types (name WIP)

### ISSUE THREAD

**Issue by cybergeek94** [rust-lang/rust-by-example#208]
This category would cover the following types:

* `Cell`
* `RefCell`
* `UnsafeCell`?
* `Rc` and `Weak`
* ~~`Gc`~~
* `Arc` (`Send` and the other kinds should be covered prior to this appearing)

Or two separate categories:
* `Cell`
* `RefCell`
* `UnsafeCell`

and then

* `Rc` and `Weak`
* ~~`Gc`~~
* `Arc`

**Comment by steveklabnik** [comment]
I'm not going to keep these kinds of issues open on the tracker, thanks!
