### ISSUE TITLE
`regex` crate and `regex!`

### ISSUE THREAD

**Issue by cybergeek94** [rust-lang/rust-by-example#212]
I love regular expressions too much to not take this topic for myself. While I haven't had occasion to use them in Rust yet, I have some good experience with regex, including building a small-time enterprise Android app around them back when I was freelancing.

I was thinking I'd cover runtime construction with  `Regex::new`, show how to use it, and then cover the `regex!` macro and show the reader how awesome it is. I've never heard of another language with regex-to-native compilation. I should also include the warning from the documentation about increased binary size, but advise the user to choose the appropriate approach for the application.

I'm not sure if I should cover the basics of regular expressions or link to a good guide for them. The `regex` crate documentation has a good reference but it won't teach how to use them. [This][regex] is the one I used to learn regex.

So far, I am disappointed by this project's lack of XKCD references. I'd like to help with that.

![XKCD 208][xkcd]

~~***Perl!***~~ ***Rust!*** (The comic should be properly attributed, of course.)

[regex]: http://www.regular-expressions.info/tutorial.html
[xkcd]: http://imgs.xkcd.com/comics/regular_expressions.png

**Comment by steveklabnik** [comment]
These are out of tree now.
