### ISSUE TITLE
explain how to cast vectors, arrays and slices

### ISSUE THREAD

**Issue by vks** [rust-lang/rust-by-example#213]
I think this should be added to the corresponding sections. Here is an example for casting vectors:

``` rust
fn main() {
    let a: Vec<uint> = range(1, 10).collect();
    let b: Vec<u32> = a.iter().map(|&e| e as u32).collect();
    for i in b.iter() {
        println!("{}", i);
    }
}
```

I'm not sure what the best way for slices and arrays is though.

**Comment by steveklabnik** [comment]
This isn't really a "cast", and I'm not sure how often it is needed. Given nobody has commented in three years here, I think I'm going to close this one. Thanks!

**Comment by ytrezq** [comment]
@steveklabnik at least explain how to do it on this issue.

**Comment by frogtd** [comment]
@ytrezq you mentioned the wrong guy btw
