### ISSUE TITLE
Suggestion: Add a Cargo chapter

### ISSUE THREAD

**Issue by jbiason** [rust-lang/rust-by-example#215]
I think it would be interesting to go through the basics of using an external library and generating a package of sorts.

**Comment by arthurprs** [comment]
A first version could simply a single small example and point the reader to http://doc.crates.io/guide.html

**Comment by steveklabnik** [comment]
This would be a great addition; I'd be happy to mentor anyone who wants to work on this!

**Comment by mark-i-m** [comment]
I could take a stab at this too 😄

@steveklabnik Does #949 look like the right direction?
