### ISSUE TITLE
explain trait inheritance

### ISSUE THREAD

**Issue by vks** [rust-lang/rust-by-example#216]
The trait chapter does not explain inheritance. A minimal example:

``` rust
trait C : A + B {}
```

This means that any implementation of `C` also has to implement `A` and `B`.
See the [reference manual](http://doc.rust-lang.org/rust.html#traits) for documentation.

**Comment by mdinger** [comment]
This still needs doing. The relevant [book page](http://doc.rust-lang.org/nightly/book/traits.html#inheritance).

**Comment by steveklabnik** [comment]
This is covered by https://github.com/rust-lang/rust-by-example/issues/90
