### ISSUE TITLE
No hash nor version on rlib's filename?

### ISSUE THREAD

**Issue by tallesl** [rust-lang/rust-by-example#225]
I was following the [Library](http://rustbyexample.com/crates/lib.html) tutorial and it is stated that the the rlib filename generated by rust shoud "*contain a hash and their version in their name*".

I did pretty much exactly like the tutorial but my file wasn't generated with hash nor version at all. Mine was `liberty.rlib` and the tutorial's `liberty-e6eaab2e-0.0.rlib`.

Is this a behavior change in Rust? The current [nightly tutorial](http://doc.rust-lang.org/tutorial.html#a-minimal-example) still shows the generated filename with hash and version.

By the way, about my environment:

    $ rustc --version
    rustc 0.12.0-pre-nightly (9dcf89567 2014-08-12 00:26:13 +0000)
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 13.04
    Release:        13.04
    Codename:       raring

**Comment by steveklabnik** [comment]
This no longer mentions stuff about the hash and version.
