### ISSUE TITLE
Considering using mdbook instead of gitbook

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#248]
This would remove our dependency on `node.js`, which would let us get closer to make this repo cargo buildable.

**Comment by nathankleyn** [comment]
@japaric @steveklabnik Is this something you're still interesting in doing? It feels like something I might actually be able to work on.

**Comment by steveklabnik** [comment]
@nathankleyn absolutely. It's been too big of a project for me to try to tackle, but it's something I want for sure.

**Comment by nathankleyn** [comment]
@steveklabnik If that's the case, I might have a poke tonight and get a feel for what's involved - it's something I'd love to try my hand at, although I will almost certainly have questions for you along the way! :grinning:

**Comment by steveklabnik** [comment]
Sure thing, I'd be happy to answer any questions. It's certainly a project that's feasable, it's just a lot of grunt work, and I've been trying to focus on 'write more docs' and less 're-do the build system'

The key thing is the plugin that gives us the fancier "embed the result of running this in the page." it's mostly javascript, but would need adapted a little. 

Also, if you need any improvements in rustbook to support it, I'm happy to walk you through those too

**Comment by mdinger** [comment]
I'm opposed to this without rustbook being upgraded to having dark theme support. I find light themes much much harder on the eyes and so I wouldn't ever move to where a dark theme isn't available (I really dislike the that the book and std docs are light themed only).

Also, it'd be worth considering using [mdBook](https://github.com/azerupi/mdBook) instead. He seems to be putting more effort into improving it than rustbook is seeing and it's independent of the rust repo which makes it simpler to hack on.

**Comment by steveklabnik** [comment]
If mdBook is really full featured, I'm actually happy to have it just eat rustbook entirely, frankly. And I mirror rustbook out of tree too.

**Comment by mdinger** [comment]
It isn't yet I don't think but it has a few niceties that rustbook doesn't have like a more proper sidebar toggling and next/previous arrows. It's still new though. We gotta give it time. He also has printing the entire book on the todo list. That would be nice.

**Comment by nathankleyn** [comment]
@mdinger @steveklabnik Given the above, let me wait on this for now - I'll familiarise myself with the differences between rustbook and mdBook and get an idea of what needs to be done. If anybody else wants to pick this up who knows what they're doing, feel free! :grinning:

**Comment by mdinger** [comment]
[mdBook](https://github.com/azerupi/mdBook) now has multiple themes included including a dark theme. See the [example render](http://azerupi.github.io/mdBook/) though it hasn't been pushed to crates yet. I'm not opposed to this anymore.

Something else which I think would be convenient is if `cargo` could export the JSON or TOML from the `Cargo.toml`. Then the cargo framework could handle the testing of the files (I think) and the example structure could just be exported into a JSON file which the book generator could grab to build the docs. Also discussed https://github.com/rust-lang/rust-by-example/issues/439 and https://github.com/rust-lang/cargo/pull/1968#issuecomment-139828816 .

**Comment by brson** [comment]
Should be converted to mdbook at this point. I don't think there's anything blocking this. Just do the conversion and change the CI.

**Comment by steveklabnik** [comment]
Yeah, the only blocking is the "just", there's a _lot_ going on here.

**Comment by mdinger** [comment]
See https://github.com/azerupi/mdBook/issues/29 but unless something has changed, as far as I know we're still waiting for examples which are editable. It's also missing search but I think that's a more minor issue.

**Comment by mdinger** [comment]
BTW, I may have time coming up this 4th of July week so if mdbook was in good enough shape for this, I may attempt it. We'll see how it goes.

**Comment by steveklabnik** [comment]
Updated the title here; rustbook _is_ mdbook these days.
