### ISSUE TITLE
Can you please add example and some explaination on Named lifetimes?  

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang/rust-by-example#288]
Hello,
  I am reading http://doc.rust-lang.org/guide-lifetimes.html but still not clear on usage and difference in returning reference vs 'r reference.  Can you please add some examples and explanation on this topic?  E.g. What is the difference between below two?

```
struct Point {x: f64, y: f64}

fn TestPointMut(p: &mut Point) -> (& f64, & f64) {
       (&p.x, &p.y)
}

fn TestPointLifetime<'r> (p: &'r Point) -> (&'r f64, &'r f64) {
       (&p.x, &p.y)
}
```

Thanks,
Rohit Joshi

**Comment by steveklabnik** [comment]
I'd be happy to mentor anyone who's looking to work on this!

**Comment by LuisAyuso** [comment]
I'd be happy to help here,  I not quite sure of how deep the explanation needs to go. But I could explain why lifetimes are the most awesome feature ever lived. 

can you @steveklabnik  point me out to the contributing guidelines?

**Comment by steveklabnik** [comment]
Sure thing! They're here: https://github.com/rust-lang/rust-by-example/blob/master/CONTRIBUTING.md

 > I not quite sure of how deep the explanation needs to go

I'm open to a range of things, honestly.

**Comment by frewsxcv** [comment]
Seems like the core concept here is about lifetime elision? In which case we have https://rustbyexample.com/scope/lifetime/elision.html Or maybe the focus is on what the name of lifetime is?
