### ISSUE TITLE
Add examples for find(), any(), all() on std::iter

### ISSUE THREAD

**Issue by kevinburke** [rust-lang/rust-by-example#296]
I'm having trouble wrapping my head around the syntax... thanks!

**Comment by mdinger** [comment]
Take a look at [closures](http://rustbyexample.com/fn/closures.html) which has just been drastically updated. If you still have difficulty please clarify. This question is vague considering the `std` libs already provide examples. For example: [`find()`](http://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find)

**Comment by Xmasreturns** [comment]
[Closures](http://rustbyexample.com/fn/closures.html) currently has examples for .any() and .find(). If it's helpful, I can add one for .all() as well, but it should be fairly straightforward after knowing the other two.

**Comment by steveklabnik** [comment]
Yes, I'm going to consider this fixed. Thanks!
