### ISSUE TITLE
Before "channels", perhaps more on typing should be introduced

### ISSUE THREAD

**Issue by xiaq** [rust-lang/rust-by-example#31]
The "channels" chapter presents the following snippet:

```rust
fn main() {
    // channels have two endpoints: the Sender<T> and the Receiver<T>,
    // where T is the type of the message to be transfer
    // (type annotation is superfluous)
    let (tx, rx): (Sender<_>, Receiver<_>) = channel();
```

I find that it's not entirely clear that

* `_` can also be used a placeholder in the type. It seems to not have been mentioned before.

* The exact type of `_` is inferred based on expressions *after* the `let`. I have learned of H-M and it seems rust implements it, but it could be confusing to someone only familiar with local inference.

These two points seem to be unmentioned (but should be) before this chapter. Correct me if I have missed them out. Although I managed to figure those out, it could still be confusing to others :)

**Comment by steveklabnik** [comment]
Channels now come far after we talk about generics and such, so I think this is fixed.
