### ISSUE TITLE
Enhance attribute/cfg/custom

### ISSUE THREAD

**Issue by cpylua** [rust-lang/rust-by-example#350]
The current attribute/cfg/custom example will not compile if we do not pass the `--cfg some_condition` flag to `rustc` and the generated html shows the placeholder `{custom.out}`. 

I think we should either insert the compiler error or add a function with `#[cfg(not(some_condition))]` as we did in cfg.rs.

**Comment by steveklabnik** [comment]
This is fixed, sa far as I can tell. It shows the error.
