### ISSUE TITLE
deriving(Decodable) is deprecated in favor of deriving(RustcDecodable)

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust-by-example#356]
We need to add an external crate, rustc_serialize, and switch over to this.

Also, deriving(Encodable) -> deriving(RustcEncodable)

**Comment by steveklabnik** [comment]
I have a patch that fixes this, but it's not going to be good to go until tonight.

**Comment by mdinger** [comment]
This is fixed I think...

**Comment by steveklabnik** [comment]
Yes, I ended up merging it in. Thanks for the triage!
