### ISSUE TITLE
Macro topic stdout confusing or broken

### ISSUE THREAD

**Issue by BrandonBrowning** [rust-lang/rust-by-example#368]
The standard out after examples is shown like the following

`{simple.out}`
(http://rustbyexample.com/staging/macros.html#494-macro_rules)

I would expect the standard output to be shown, maybe in collapsible form.

Might apply to other topics.

**Comment by mdinger** [comment]
PR https://github.com/rust-lang/rust-by-example/pull/407 should fix this if/when it lands.

**Comment by mdinger** [comment]
@steveklabnik This is fixed.
