### ISSUE TITLE
Latest version is not deployed

### ISSUE THREAD

**Issue by gchp** [rust-lang/rust-by-example#373]
It seems that the live site needs to be updated with the latest version of the repo. I was looking at this page: http://rustbyexample.com/array.html
and noticed that it fails to build due to some obsolete syntax in the example, however the example is up to date on master.

**Comment by steveklabnik** [comment]
Our last build failed, and so it hasn't been updated. When a passing build happens, the site will get updated.

**Comment by gchp** [comment]
Ah ok, cool! Thanks for the response :)
