### ISSUE TITLE
Issue when running make all

### ISSUE THREAD

**Issue by narutosanjiv** [rust-lang/rust-by-example#379]
I have tried to run make all but face a number of issue. 
```
kenshin@linux-w19f:~/Documents/projects/rust-by-example> make all
./setup-stage.sh
Checked out revision 110.
rustc src/update.rs --out-dir bin
src/update.rs:2:12: 2:17 error: feature has been removed
src/update.rs:2 #![feature(phase)]
                           ^~~~~
```
I have removed #![feature(phase)] from update.rs. I again run update.rs and again i have found that error: #[phase] is deprecated; use #[macro_use], #[plugin], and/or #[no_link], then i again i have removed but still getting these error.
```
./setup-stage.sh
Checked out revision 110.
rustc src/update.rs --out-dir bin
src/update.rs:5:1: 5:27 error: can't find crate for `regex_macros`
src/update.rs:5 extern crate regex_macros;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Makefile:28: recipe for target 'all' failed
make: *** [all] Error 101
```
As per my knowledge, regex_macros is crates library, does we need to convert these project as crates compatible project?

**Comment by GBGamer** [comment]
We're working on it now.

**Comment by narutosanjiv** [comment]
@GBGamer  Ok! Sorry! I have not seen @steveklabnik  pull request regarding converting these projects into cargo projects.

**Comment by steveklabnik** [comment]
Yes, my PR is in-progress. It needs a new nightly to land on Travis, IIRC. Thanks for filing though! I'm going to close this in favor of that.
