### ISSUE TITLE
borrow/mut: calls move a copy

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#384]
The example:

```rust
    // `mutable_geb` is a mutable copy of `geb`
    let mut mutable_geb = geb;

    // Borrow a mutable object as mutable
    new_edition(&mut mutable_geb);

    // Mutable objects can be immutably borrowed
    borrow_book(&mutable_geb);
```

says "`mutable_geb` is a mutable *copy* of `geb`". To me *copy* means creation of another independent object (a `memcpy()` of the data), but this doesn't behave like a copy. If I add at the end:

```rust
    borrow_book(&geb);
```

I get:

> error: use of moved value: `geb`
> error: aborting due to previous error

Which indicates that it wasn't a copy — there's still only one shared object.

**Comment by GBGamer** [comment]
Ah, we need to `#[derive(Copy)]`
