### ISSUE TITLE
for: replace range() function with range notation

### ISSUE THREAD

**Issue by genbattle** [rust-lang/rust-by-example#389]
I was updating old code of mine and got this warning for one of my code files:

```
main.rs:15:14: 15:19 warning: use of unstable item: will be replaced by range notation, #[warn(unstable)] on by default
main.rs:15     for i in range(1, 1000) {
```

I pulled up Rust by Example to see what the new idiomatic way of doing this was and found that Rust by Example was using the same (apparently unstable) syntax. The [Rust book](http://doc.rust-lang.org/book/looping.html) also uses the outdated syntax.

So at the moment there's no straightforward up-to-date resources on what the syntax _should_ be. But apparently it involves Rust's new [a..b] range syntax. Can someone with more knowledge about what the syntax *should* be please update Rust by Example.

**Comment by genbattle** [comment]
It looks like this is a fairly [new change](https://github.com/rust-lang/rust/issues/20830). I also discovered by wading through various github issues for Rust that the new syntax for basic for loops using numeric ranges is:
```
for i in a..b {
```

**Comment by genbattle** [comment]
Also apparently brackets are required in some cases but not in others?
```
for i in (a..b) {
```

**Comment by Vayn** [comment]
I encountered this warning, thanks for sharing the information @genbattle

**Comment by mdinger** [comment]
`for i in (a..b) {`is just a bug. I think https://github.com/rust-lang/rust/pull/21396 is a fix. I think I fixed this in https://github.com/rust-lang/rust-by-example/pull/421 if it's accepted.

**Comment by anderspitman** [comment]
Is there any way to avoid this warning when using a variable in the range? ie

```rust
let a = [i32; 10];
for i in range(0, a.len()) {}
```

**Comment by mdinger** [comment]
```rust
fn main() {
    let a: [i32; 2] = [1, 2] ;
    for i in 0..a.len() {
        println!("{:?}", i);
    }
}
```
