### ISSUE TITLE
borrow/ref: Not clear what's the difference between ref and &

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#390]
In other languages `&` is called a reference and borrowing looks very much like references, so to me `&` and `ref` seem like the same thing.

I'd appreciate an example that contrasts the two — why `let Point { x: ref ref_to_x, y: _ }` is OK, but `let Point { x: & ref_to_x, y: _ }` isn't?

**Comment by GBGamer** [comment]
`ref` is used in pattern matching, so its used when you want to borrow
something in, for example, a match statement.

    let a = Some("Hello!".to_string());
    match a {
        Some(ref s) => { //s is an &String here
        }
        ...
    }

    match a {
        Some(s) => {
            // s is a String here, and therefore
            // is owned by the match
        }
        ...
    }

**Comment by pornel** [comment]
Why can't you use `&` to borrow in the match?

```rust
match a {
Some(&s) => {}
}
```
?

**Comment by GBGamer** [comment]
That, I don't know. It's not really a decision I agree with. I like that
style better, personally.

On Sun, Jan 11, 2015 at 11:27 AM, Kornel <notifications@github.com> wrote:

> Why can't you use & to borrow in the match?
>
> match a {Some(&s) => {}
> }
>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust-by-example/issues/390#issuecomment-69507268>
> .
>



-- 
"Calling all. This is our last cry before our eternal silence."
"The lone and level sands stretch far and away"

**Comment by pornel** [comment]
I'm not trying to question Rust design decision here, just understand difference between `ref` and `&` — and I'm reporting that the example about references doesn't elaborate on that.

Whether that's just arbitrary, or quirky syntax to avoid ambiguity, or it has slightly different meaning, I'd like to know that, because I'm not sure when to use which and why rustc complains about `&_-ptr` or such when I use `&` instead of `ref`.

**Comment by GBGamer** [comment]
I think the idea is that you destruct as you construct, like in a

   let op = Some(a);

    match op {
        Some(x) => x,
        None => ...
    }

So if you type

    match op {
        Some(&x) => // here you are dereferencing a pointer
            ...
        None => ...
    }

**Comment by pornel** [comment]
Sorry, I don't understand your last answer. `&x` is dereferencing a pointer? I thought `*x` is dereferencing.

Perhaps I'm asking stupid question, but the mental model I have is from C:

    object  ----  reference operator &  ---> pointer
    object  <--- dereference operator * ---- pointer

and there's no room in it for `ref`. If it's like this:

    object  ---- ref operator ---> pointer

then in my mind it's identical with `&`, but clearly in Rust there must be a difference.

When I use `&` where Rust expects `ref` I get error message that I don't understand:

> mismatched types: expected `isize`, found `&_` (expected isize, found &-ptr)

I'm not sure what `&_` and `&-ptr` are, but I'm guessing it means reference to an unknown type. And it's weird, because the type should be known from the context.

**Comment by GBGamer** [comment]
So where are you seeing this error? In Rust, you basically have this:

```
let a = &i;
let r = *a;
// These are exactly like in C (i.e. `&i` gets the address of i,
// `*a` dereferences a)
```

However, this does not help us when we do pattern matching.

```
let a = Some(1i); // This is how we construct an Option
match a {
    Some(x) => println!("{}', x), // This prints '1'
    // Notice we "deconstruct" in a match statement the same way we
    // normally construct
    ...
}
```

What about when we have to get a reference in a match statement where there was
none before? In normal code, getting a reference to a variable is easy.

```
struct BigFoo {
    // Lots of fields
}

fn bar(bf: &BigFoo) {
    // Do stuff with bf
}

fn main() {
    let bf = BigFoo {
        // lots of fields
    }

    bar(&bf);
}
```

However, what if you have, say, a match statement?

```
fn possibly_print(x: &Option<String>) {
    match *x {
        // BAD: It's impossible to move out of an &-reference
        //Some(s) => println!("{}", s);

        // GOOD: Instead, we take a reference into the `Option`s memory
        Some(ref s) => println!("{}", *s),
        None => println("No string!"),
    }
}
```
(Note: this is taken directly from the [rust docs book][book])

[book]: http://doc.rust-lang.org/book/README.html

**Comment by pornel** [comment]
The error I was getting was from

```rust
match a {
  Some(&x) => 
}
```

So I think I'm starting to get why it's illegal syntax:

```rust
fn main() {
    let x = 123;
    let &x_ref_1 = &x;
    let ref x_ref_2 = &x;
    //let & x_ref_3 = x; // same error as when matching &x
    let ref x_ref_4 = x;
}
```

but "matching uses same syntax as constructing" doesn't seem right to me:

```rust
    let s1 = Some(&x); // legal
    let s2 = Some(ref x); // illegal
```

**Comment by GBGamer** [comment]
There are two things going on here:

    let x = 3i;
    let s1 = Some(&x);
    match s1 {
        Some(&y) => {}, // y = x here (it's destructured the same way it's constructed)
        ...
    }

`ref` is only useful for match statements; it's literally only for

    let s2 = Some(x);
    match s2 {
        Some(ref y) => {}, // y = &x here
        ...
    }

**Comment by pornel** [comment]
Oh, that's interesting! Are these two statements equivalent?

```rust
let x = &y;
let ref x = y;
```

**Comment by GBGamer** [comment]
Yes, exactly!

On Mon, Jan 12, 2015 at 2:23 PM, Kornel <notifications@github.com> wrote:

> Oh, that's interesting! Are these two statements equivalent?
>
> let x = &y;let ref x = y;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust-by-example/issues/390#issuecomment-69658337>
> .
>



-- 
"Calling all. This is our last cry before our eternal silence."
"The lone and level sands stretch far and away"

**Comment by pornel** [comment]
Ok, so now it makes sense to me! Thanks!

I suggest adding such simple example to the site:

```rust
let y = 'y';

// `ref` on the left side of an assignment is like adding `&` on the right side
let ref x1 = y;
let x2 = &y;

println!("{}", x1 == x2);
```

The full example is useful as well, but with destructuring at the same time there's much more going on.

**Comment by GBGamer** [comment]
Thank you very much for bringing this incredibly confusing thing to our
attention; I hadn't even thought about it before you said it :)

**Comment by mdinger** [comment]
@pornel I just saw this thread and modified PR https://github.com/rust-lang/rust-by-example/pull/421 to try to elaborate on this.

The specific file was [pointers.rs](https://github.com/mdinger/rust-by-example/blob/flow_control/examples/flow_control/match/destructuring/destructure_pointers/pointers.rs)

By the way, your critiques are very helpful. It's really hard to anticipate learning questions. Generally I focus on trying to fix things I find confusing but having others do the same is really useful.

**Comment by pornel** [comment]
@mdinger thanks. It's much clearer. 

And I didn't know if let existed :)

**Comment by mdinger** [comment]
`ref` and `&` are discussed [here](http://www.reddit.com/r/rust/comments/2tq33x/ref_keyword/) on reddit. `let mut ref mut x = y` I hadn't seen before. If my PR is *generally* accepted, I may try to work that in or refer to somewhere it can be discussed more thoroughly.

These explanations are missing in general and really need to be added.

**Comment by mdinger** [comment]
Destructuring and pattern matching discussed [here](http://www.reddit.com/r/rust/comments/2u6ovr/multiple_assignment_unpacking_pattern_matching/co5mlax).

I have a feeling *pattern matching* may need to be discussed as a separate topic from `match`. `match` uses pattern matching but it's also typically where it's explained.

**Comment by mdinger** [comment]
Is this still a problem? Is there an actionable response that can be taken?

**Comment by pornel** [comment]
Yes, I think it still can be improved.

The big example on that page focuses on a case where `ref` is necessary, but it doesn't make it clear how `ref` relates to `&`. There's too much going on for me to understand it.

For me it "clicked" when I saw the [simplest case](https://github.com/rust-lang/rust-by-example/issues/390#issuecomment-69660693):

```rust
// `ref` on the left side of an assignment is like adding `&` on the right side
let ref x1 = y;
let x2 = &y;
```

So I suggest adding exactly that to the page, before showing a complex case.

**Comment by LukeSkyw** [comment]
Just spent two hours trying to make sense of this:

```
struct Foo {
    value: u32,
}

fn double(v: &Vec<(Foo, u32)>) -> Vec<u32> {
    v.iter().map(|&(&f, v)| f.value + v).collect()
  |                ^^ expected struct `Foo`, found reference
  |
  = note: expected type `Foo`
  = note:    found type `&_`
}

fn main() {
    let vector = vec!(
        (Foo { value: 1 }, 2),
        (Foo { value: 2 }, 3),
        (Foo { value: 3 }, 4));
    let doubled = double(&vector);
    println!("{:?}", doubled);
}
```

So, as explained above, it should have been:
```
struct Foo {
    value: u32,
}

fn double(v: &Vec<(Foo, u32)>) -> Vec<u32> {
    v.iter().map(|&(ref f, v)| f.value + v).collect()
}

fn main() {
    let vector = vec!(
        (Foo { value: 1 }, 2),
        (Foo { value: 2 }, 3),
        (Foo { value: 3 }, 4));
    let doubled = double(&vector);
    println!("{:?}", doubled);
}
```

**Comment by AlecZadikian9001** [comment]
It's confusing, especially when you add in unsafe pointers. To be honest, I usually change between ref and & randomly until the code compiles.

**Comment by abbshr** [comment]
```rust
fn main() {
    if let Some(&pat) = Some(&Box::new(1)) {
        println!("{:?}", pat);
    }
}
```

The rust compiler explained as follow:
```
error[E0507]: cannot move out of borrowed content
 --> ref.rs:2:17
  |
2 |     if let Some(&pat) = Some(&Box::new(1)) {
  |                 ^---
  |                 ||
  |                 |hint: to prevent move, use `ref pat` or `ref mut pat`
  |                 cannot move out of borrowed content
```

So, using `ref` just in **pattern match** is undoubted~

**Comment by kaiwk** [comment]
Hello, sorry for reopening this issue, but I found it's an interesting topic.

I know that pattern match is a way to match programming language syntax itself, but I still feel confused about keyword `ref`. Why can't we just use `let *x_ref = x`. In that case, `x` is a value, and `x_ref` is a reference. 

For example:

```rust
if let Some(* x_ref) = Some(x) {
}
```
It's more consistent with Rust syntax.

In my opinion, getting a reference to a value should be an opposite behavior in pattern match, which is dereference.  Maybe `deref` is better than `ref`.

```rust
if let Some(deref x_ref) = Some(x) {
}
```

**Comment by vbauerster** [comment]
> e.g. in methods I can use `&self` instead of `ref self`.

> Why can't you use `&` to borrow in the match?
> 
> ```rust
> match a {
>     Some(&s) => {}
> }
> ```
> 
> ?
> 
> e.g. in methods I can use `&self` instead of `ref self`.

Looks like nobody gave an answer regarding `&self` in methods.
Actually `&self` is a shorthand for a type one implements method on.

Shorthand | impl for MyType
---------- | ----------------
`self` | `self: MyType`
`&self` | `self: &MyType`
`&mut self` | `self: &mut MyType`

So, technically `&self` is not a *reference pattern* and there is nothing to destructure on it. That's why saying `ref self` in methods is equally not appropriate as saying `let x = ref MyType`.
