### ISSUE TITLE
structs: Not explained what unit structs are for

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#391]
```rust
// A unit struct
struct Nil;
```

The example tells me what it's called, but not what it is. What do you use it for?

```rust
// Instantiate a unit struct
let _nil = Nil;
```

Unit structs are confusingly similar to C's incomplete struct types, so this bit of code looks weird to me. Why would compiler allow instantiation of a struct with no members? What's the use-case for it?

The same pattern, under a different name, appears in [generics/impl](http://rustbyexample.com/generics/impl.html):

```rust
struct T; // A null struct
```

**Comment by GBGamer** [comment]
As far as I know, unit structs are pretty much only useful as trait
objects. If anyone would like to correct me? I don't think I've ever used
them in my own code.

**Comment by mdinger** [comment]
Look at [phantom units](http://rustbyexample.com/generics/phantom/units.html) where it's used to make types `Inch` and `Mm` distinct and different. That used to use a null  enum (`enum Mm {}`) but it's more succinct as a struct.

**Comment by Bema** [comment]
I also wasn't sure about the use case for unit structs, found some more information [here](https://doc.rust-lang.org/book/structs.html#unit-like-structs).

**Comment by ubsan** [comment]
Triage: would we like to say this is fixed? Or should we add a chapter on unit structs?

**Comment by pornel** [comment]
https://doc.rust-lang.org/book/structs.html#unit-like-structs

> For instance, a library may ask you to create a structure that implements a certain trait to handle events. If you don’t have any data you need to store in the structure, you can create a unit-like struct.

For me this is OK

**Comment by israteneda** [comment]
I think unit structs still is not well explained in rust-by-example.
