### ISSUE TITLE
phantom/units: The example is very dense

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#392]
```rust
impl<Unit, T: Add<T, Output=T> + Copy> Add<Length<Unit, T>>
        for Length<Unit, T> {
    type Output = Length<Unit, T>;
```

There's *a lot* going on in that line, and it requires significantly more effort to deconstruct than previous examples.

Could it be broken down? Maybe the large comment that is above that line could be mixed with the code like this:

```rust
impl<Unit, T: Add<T, Output=T> + Copy> // this is impl<T> blah blah
Add<Length<Unit, T>> // of this and that
for Length<Unit, T> // for this yada yada
```

Also it's not explicitly mentioned what `Output=T` is for.

**Comment by GBGamer** [comment]
Alright, I'll fix this, thanks! (Gonna take me a while, because I can't
access a computer, but in a few hours a fix'll be up)
