### ISSUE TITLE
Unable to read code on Android

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#393]
On Nexus 5/Android 5 I can't read the examples because they're displayed all in one line in nature short text box and it's even very hard to scroll that box (tested Chrome Beta and Firefox Beta). 

![screenshot_2015-01-11-12-42-15](https://cloud.githubusercontent.com/assets/72159/5695257/313ac7bc-9990-11e4-83e0-20096d80330c.png)

In Chrome "request desktop site" has rendered code properly once, but on subsequent pages it was all in one line again. 
In Firefox desktop view messes up layout completely with navbar obscuring the main content.

**Comment by GBGamer** [comment]
As far as I can tell, on my Moto G running Android Lollipop with Firefox,
it works. Try seeing if you have JavaScript running, this is what happens
when you don't have JavaScript on desktop, at least.

**Comment by pornel** [comment]
If I disable JS it looks like this 
![screenshot_2015-01-11-18-59-29](https://cloud.githubusercontent.com/assets/72159/5696330/38bc8af0-99c4-11e4-87df-790481c32a4c.png)

**Comment by GBGamer** [comment]
That is weird... Could you try on Firefox Stable, with JavaScript enabled?

**Comment by pornel** [comment]
Perhaps relevant - mobile ISPs in UK use Citrix ByteMobile proxy that mangles HTML.

 The page isn't over HTTPS and has significant whitespace in `<div>` instead of `<pre>`, so this could be causing a problem.

**Comment by pornel** [comment]
I don't see option to disable JS in Fx 
![screenshot_2015-01-11-19-05-23](https://cloud.githubusercontent.com/assets/72159/5696348/f8ab612e-99c4-11e4-9c4b-b503ac020adf.png)

**Comment by GBGamer** [comment]
I think its gotta be the UK ISP. On T-Mobile US, a Nexus 5 works perfectly
(Chrome stable, Lollipop)

**Comment by pornel** [comment]
Nevermind about the ISP. I've checked over my WiFi and it's still all in one line.

**Comment by GBGamer** [comment]
That is weird... I'm sorry, I don't know. It works perfectly on both a
Nexus 5, and a Moto G, both on Lollipop, on both Chrome Stable and Firefox
Stable.

On Sun, Jan 11, 2015 at 11:18 AM, Kornel <notifications@github.com> wrote:

> Nevermind about the ISP. I've checked over my WiFi and it's still all in
> one line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust-by-example/issues/393#issuecomment-69506888>
> .
>



-- 
"Calling all. This is our last cry before our eternal silence."
"The lone and level sands stretch far and away"

**Comment by pornel** [comment]
It's the ISP indeed — I wasn't seeing changes after refreshing the page, because the browser has saved mangled pages in the appcache.

Can you use `<pre id=editor>` instead of `<div id=editor>`? I think that'd help.

Also HTTPS would help. I've tried switching to HTTPS and ignoring certificate errors, but the server isn't configured anyway.

**Comment by GBGamer** [comment]
If you go to https://rust-lang.github.io/rust-by-example, you can get https.

**Comment by pornel** [comment]
Thanks!
