### ISSUE TITLE
Meta links on top of nav bar lead to steveklabnik's repo

### ISSUE THREAD

**Issue by sinistersnare** [rust-lang/rust-by-example#397]
Currently, "about the author" links to https://github.com/steveklabnik, "Questions and Issues" links to https://github.com/steveklabnik/rust-by-example/pulls, and "Edit and Contribute" links to https://github.com/steveklabnik/rust-by-example/edit/master/examples/threads/input.md
and the top 'bookmark' image links to https://github.com/steveklabnik/rust-by-example

I hope this is not desired behaviour :)

**Comment by steveklabnik** [comment]
Whoops! Wonder how that happened. Yes, it's not desired.

**Comment by mdinger** [comment]
I think this changed when gitbook was updated to latest. Now I can't find any link back to here. One should be added to the introduction page unless someone thinks of a better location for one.
