### ISSUE TITLE
iter: uses clever code without a comment

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#398]
The example uses `mem::replace` without explanation why. 

```rust
Some(mem::replace(&mut self.curr, new_curr))
```

Assigning to `self.curr` instead seems to work, so is it just to make the code a line shorter? Or is there another reason, e.g iterators have to be thread-safe and `mem::replace` is doing atomic swap?

**Comment by GBGamer** [comment]
Yeah, I have no idea. @steveklabnik, any reason for this?

**Comment by steveklabnik** [comment]
This text was around before I was maintainer, so I'm not sure. `mem::replace` does an in-place replacement, but I'm not sure if it's important or not.

**Comment by mdinger** [comment]
Japaric knows a lot and it's probably just an optimization that he never realized was confusing. It's been there a while.
