### ISSUE TITLE
path: prelude?

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#404]
> The prelude exports the appropriate platform-specific Path variant.

Sounds like compiler jargon. Does it mean "global `Path`"?

**Comment by GBGamer** [comment]
How does this sound:

> The compiler automatically chooses the correct `Path` based on the platform.

**Comment by pornel** [comment]
That's better, but doesn't explain which path - where it is. I'd expect it to be `std::something::Path`, but I guess only unqualified "global" path is set automatically?

**Comment by GBGamer** [comment]
I really can't think of how to word it...

On Tue, Jan 13, 2015 at 1:24 PM, Kornel <notifications@github.com> wrote:

> That's better, but doesn't explain which path - where it is. I'd expect it
> to be std::something::Path, but I guess only unqualified "global" path is
> set automatically?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust-by-example/issues/404#issuecomment-69822944>
> .
>



-- 
"Calling all. This is our last cry before our eternal silence."
"The lone and level sands stretch far and away"

**Comment by pornel** [comment]
Maybe

> The Path struct represents file paths in the underlying filesystem. There are two flavors of Path: posix::Path, for UNIX-like systems, and windows::Path, for Windows. You don't need to import them. The global `Path` is appropriate for the current platform.

**Comment by GBGamer** [comment]
Ooh, I like it. Would you mind submitting a pull request?

**Comment by steveklabnik** [comment]
Is there something specific about the prelude that's causing this problem? It's not jargon, it's a module: http://doc.rust-lang.org/nightly/std/#the-rust-prelude-and-macros

**Comment by pornel** [comment]
Ahhh, I didn't know prelude was actually a publicly-exposed module. I thought it's just a codename for an internal magic compiler thing, since I never needed to interact with it explicitly (because all names from prelude are available without `use`).

I remember when I started out with rust I had a problem with getting `Path` to work, because I couldn't believe it's "global" and I don't need to import it, so I've been trying all kinds of `use std::io::path::arrgh::where::are::you::Path`.
