### ISSUE TITLE
closures: No explanation of `&:`

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#405]
The closure syntax uses a mysterious sigil `&:` which isn't explained.

**Comment by GBGamer** [comment]
`&:` means a closure by reference, i.e. the variables that are closed over are passed by reference.
`&mut:` is the same, but they're now mutable.
`move` means that all variables are actually moved into the closure.

**Comment by mdinger** [comment]
That sigil is gone now: https://github.com/rust-lang/rust/pull/21843
