### ISSUE TITLE
hof: No explanation how to create a function that takes a closure

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#406]
The example uses preexisting functions accepting closures, but doesn't show how to create one.

I'm struggling with this, because the compiler won't infer the closure type, and closure types were not explained (related #405).

```rust
fn callme<T>(callable: T) {
    callable(12i32);
}

fn main() {
    callme(|&:arg| -arg);
}
```

> error: expected function, found `T`

**Comment by GBGamer** [comment]
```
fn callme<F>(callable: F)
        where F: Fn(i32) -> i32 {
    println!("{}", callable(12i32));
}

**Comment by mdinger** [comment]
The [closures](http://rustbyexample.com/fn/closures.html) section now includes an example covering this case. This should be fixed.

**Comment by pornel** [comment]
Thank you!
