### ISSUE TITLE
[Docs] Add richer examples to the Guide to Strings

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-by-example#427]
<a href="https://github.com/velvia"><img src="https://avatars.githubusercontent.com/u/1062875?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [velvia](https://github.com/velvia)**
_Saturday Jan 10, 2015 at 07:50 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/20854_

_This issue was labelled with: A-docs in the Rust repository_

---

As someone coming from dynamic as well as JVM languages, Rust strings were confusing.  The Strings guide has very helpful intro material, but soon I found myself stumbling on more sophisticated use cases.

For example, let's say I want a struct where a member stores a list of strings:

``` rust
pub struct DataRecord {
  pub name: String,
  pub tags: Vec<&'static str>
}
```

The number of possible choices is bewildering.   Do I use `[String]`, `Vec<String>`, `[&str]`, etc. etc.?   Minimizing allocation is good, but structs are tricky because they might be kept around and bounced between multiple function calls before being disposed, or even kept in some other data structure.  Also, each string within the list might come from a constant or not.  Much more things to think about.

Anyways, the suggestion would be to cover a few examples like this where you use Strings in structs, vecs, arrays etc and go over what are best practices and common scenarios.

**Comment by velvia** [comment]
@steveklabnik thanks.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
