### ISSUE TITLE
Online editor highlight issue

### ISSUE THREAD

**Issue by caizixian** [rust-lang/rust-by-example#429]
It only highlights `i32` `i8` etc,but `is` `us`

**Comment by mdinger** [comment]
https://github.com/ajaxorg/ace/pull/2325 merged to upstream and should fix this though it's untested. Currently though, ace is downloaded directly from [ajaxorg/ace-builds](https://github.com/ajaxorg/ace-builds) which releases periodically; so we're waiting for that to update.

[play.rust.org](https://play.rust-lang.org/) has the same issue but I'm not sure how they get new ace builds and when they get updates.

**Comment by caizixian** [comment]
@mdinger LGTM.

**Comment by mdinger** [comment]
This works now
