### ISSUE TITLE
Decide whether to transition all examples from make test to cargo test

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#439]
All the examples could be transitioned to `cargo test` from `make test` as discussed on PR https://github.com/rust-lang/rust-by-example/pull/433#issuecomment-72081445 . Currently this would be awkward without https://github.com/toml-lang/toml/pull/235 and so we're waiting for that to materialize before a decision is made for or against transitioning.

@steveklabnik I'm assuming postponing this is fine for now. If so, can you flag this postponed?

**Comment by steveklabnik** [comment]
yes, I want everyone to go to cargo test, but haven't had the time to do
the work. I personally don't care if the compact toml syntax lands or not.

**Comment by steveklabnik** [comment]
(there is no postponed tag)

**Comment by mdinger** [comment]
Okay. That's helpful because previously I'd be hesitant to start porting because I wasn't sure if it'd be accepted.

I want the syntax so I doubt I'll work on porting it until then but someone else is welcome to it.

**Comment by mdinger** [comment]
https://github.com/rust-lang/cargo/pull/1225 is wip to provide dependency access for cargo. If this supports export to JSON, it could potentially allow a direct migration without many changes aside from the `Cargo.toml` and the structure file.

**Comment by steveklabnik** [comment]
The changes to toml have landed.

**Comment by steveklabnik** [comment]
This is now `mdbook test` 👍
