### ISSUE TITLE
threads: Wrong claims due to spawn() vs scoped() confusion

### ISSUE THREAD

**Issue by m10e** [rust-lang/rust-by-example#442]
The example first mentions spawn(), then uses scoped() in the code snippet, then claims that the scheduling is non-deterministic. The use of scoped() and the ignoring of the returned JoinGuard causes immediate joins upon the return of scoped(), so the scheduling is very deterministic.

**Comment by steveklabnik** [comment]
This will be fixed with my open PR which re-writes this documentation.
