### ISSUE TITLE
attribute/cfg: What values are set by default?

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#446]
The example only shows "linux", but what values are set on other platforms?

How can I check what's my platform's name according to Rust?

Is there a way to target _all_ Unix platforms? (OS X, FreeBSD, etc.)

Is there a way to target x86 and ARM?

**Comment by mdinger** [comment]
This seems to be documented under [Reference/conditional compilation](http://doc.rust-lang.org/reference.html#conditional-compilation). Looks like you'd use:
```rust
#[cfg(any(target_os = "linux", target_os = "freebsd"))]
fn needs_foo_or_bar() {}
```

How nesting is applied isn't completely clear though it states you can.

**Comment by mdinger** [comment]
Ah, `target_family` looks like what you need.
