### ISSUE TITLE
use has limited usefulness in math operations

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#451]
The two normal forms for `std::num::Float` function use are methods: `num.sin()` and importing `Float`: `Float::sin(num)`. In computations, both are pretty [problematic](http://www.reddit.com/r/rust/comments/2vl40h/question_about_library_design_stdnum/coitllk) but that link also shows a good workaround which would make a good example.

```rust
use std::num::Float;

// Manually declaring
const sinh:  fn(f64) -> f64 = Float::sinh;
const asinh: fn(f64) -> f64 = Float::asinh;

fn main() {
    let e = std::f64::consts::E;

    // Very long syntax
    Float::asinh(Float::sinh(e));

    // Poor readability
    e.sinh().asinh();

    // Manually declared has nice syntax
    asinh(sinh(e));
}
```

It would be good to show this where the `use` is explained.

**Comment by steveklabnik** [comment]
This currently goes against good Rust style: the 'very long syntax' is considered best.
