### ISSUE TITLE
Toggling comments in code editor

### ISSUE THREAD

**Issue by karbak** [rust-lang/rust-by-example#464]
It would be nice if there was a button/option in the live code editor to toggle comments on/off. Especially in some of the earlier examples, the ratio of comment/code lines is high, and makes the code not especially easily readable.

**Comment by GBGamer** [comment]
I think this means that we need to do more to make the earlier examples more readable.

**Comment by steveklabnik** [comment]
We now use mdBook for all of this, please add a feature request upstream! Thank you.
