### ISSUE TITLE
Incorrect search engine summary of rustbyexample.com

### ISSUE THREAD

**Issue by sjef** [rust-lang/rust-by-example#465]
Searching for "rust by example" in Google returns this "**[Rust][rust]** is a programming language with a focus..." as rustbyexample.com's summary(or whatever it is called). This issue is also true for Baidu.

Bing and Duckduckgo returns this "**Rust by Example. Rust** is a programming language with a focus on type..."

Below are images showing the search result in Google, Baidu, Bing and Duckduckgo.

Google:
![rbegoogle](https://cloud.githubusercontent.com/assets/8290704/6316077/3e8ed428-ba18-11e4-87fe-49e32eafb07a.PNG)

Baidu:
![rbebaidu](https://cloud.githubusercontent.com/assets/8290704/6316079/485e5546-ba18-11e4-9518-6e01e951b5a5.PNG)

Bing:
![rbebing](https://cloud.githubusercontent.com/assets/8290704/6316078/432fd4aa-ba18-11e4-8ef5-4dbf5760dc8d.PNG)

Duckduckgo:
![rbeduckduckgo](https://cloud.githubusercontent.com/assets/8290704/6316076/3d5faf82-ba18-11e4-8703-ce9bf9ad0ade.PNG)

**Comment by mdinger** [comment]
A possible fix is sorta detailed at https://github.com/rust-lang/rust-by-example/pull/466#issuecomment-75396099 but it's very preliminary.

**Comment by sjef** [comment]
No longer appears to be an issue with any of the search engines.
Probably should have written this comment before I closed it.
