### ISSUE TITLE
Please add example of destructors in RAII example

### ISSUE THREAD

**Issue by e-oz** [rust-lang/rust-by-example#467]
Opening this example, I hoped to see how to implement destructor:
https://github.com/rust-lang/rust-by-example/blob/master/examples/raii/raii.rs
But there is 0 words about it.

**Comment by steveklabnik** [comment]
Yes, adding information about Drop here would be great. I'm happy to mentor anyone who wants to work on this!

**Comment by maccoda** [comment]
Hey @steveklabnik,
I am keen to address this one but unfortunately the link no longer exists, from your comment I am guessing we want to provide some information about the `Drop` trait, similar to what you have done in the [book](https://doc.rust-lang.org/book/second-edition/ch15-03-drop.html). Would that be right?

**Comment by steveklabnik** [comment]
@maccoda that page is at https://github.com/rust-lang/rust-by-example/blob/0d5f96a4a8bae71baab52cbdd010914948a2abc1/src/scope/raii.md now, which is rendered here https://rustbyexample.com/scope/raii.html

And yeah, it should show how to implement `Drop`, similar to the book. Feel free to use a totally different example if you'd like.
