### ISSUE TITLE
Sidebar is broken

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust-by-example#468]
When I visit <http://rustbyexample.com/>, I can click any of the links in the side bar just fine. But as soon as I reach the desired page, the sidebar is replaced with the text "where":

![2015-02-22-165444_1362x732_scrot](https://cloud.githubusercontent.com/assets/667901/6321494/8586b710-bab3-11e4-9ff5-17179e0e1209.png)

This is especially annoying because, due to rust-by-example taking over the back button, the "where" persists even when I go 'back' through history. I have to refresh the page for the sidebar to return.

**Comment by steveklabnik** [comment]
This is very odd. I cannot reproduce. What os/browser etc?

**Comment by tomjakubowski** [comment]
OS: Arch Linux
Browser: Chromium Version 39.0.2171.99 (64-bit)

**Comment by tomjakubowski** [comment]
Could be related to the ad block extension I use, I will investigate. 



—

**Comment by steveklabnik** [comment]
I'm on Linux, but using Iceweasel.

**Comment by tomjakubowski** [comment]
Disabling the ad blocker doesn't fix the issue. Here's a screenshot of the inspector after the "where" appears:

![2015-02-22-172939_1362x732_scrot](https://cloud.githubusercontent.com/assets/667901/6321703/6beea006-bab8-11e4-8cd1-4f6814b652a0.png)

**Comment by tomjakubowski** [comment]
OK, what seemed to happen was that clicking on a link put the text "where" into the search field, which then filtered all of the topics on the left hand side out (since none of them contained the text "where"). When I deleted the text I was able to use the navigation panel again.

Here are some steps to reproduce the bug from scratch:

* Click the "magnifying glass" icon to start a search
* Type some gibberish in, until all entries from the navigation panel are filtered out
* Reload the page. Note the entries in the nav panel return.
* Click a link on the nav panel. This will populate the search field and subsequently filter out all entries in the nav panel.

I would also suggest that the styling of the search input should be changed. It was impossible to tell that the field was a search field *at all* until I inspected the source. Simply using a white background for the search field should be sufficient to make it clear that it's an input.

**Comment by mdinger** [comment]
I've run into this before. The remembering of search terms across sessions seems to sometimes leave the sidebar looking oddly empty. Definitely confusing. Might just be a gitbook issue.

**Comment by mdinger** [comment]
[Gitbook 2.0](https://github.com/GitbookIO/gitbook/pull/562) is approaching. It might be worth waiting/checking to see if this changes with 2.0.

**Comment by steveklabnik** [comment]
I can confirm that this happens to me, too.

That means this is a gitbook issue, not an us issue, though :/ Might want to file some bugs with them.
