### ISSUE TITLE
scriptable debugging

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#489]
`lldb` supports [scripting](http://lldb.llvm.org/scripting.html) and looks like a generally useful technique. It seems like a good idea to include a similar example with a Rust example, one which directly applies to Rust.

The example is rather complicated...I'm not sure if it can be reduced but if it could it would be good to do so.

This is not directly about understanding Rust but it seems like it would enable Rust users and so could be useful here. I'm not exactly sure how much this entails as I haven't looked in great detail but I'd like to be optimistic that it could be more compact and could refer to `lldb` for more advanced details. It might also apply to `gdb` or other debuggers but as before, I haven't looked into it and don't know.

**Comment by steveklabnik** [comment]
I would be happy to take a PR for this, but I don't think we need a bug tracking it; it's far too broad.
