### ISSUE TITLE
Expand println section

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#495]
The [`println!`](http://rustbyexample.com/print.html) section should be expanded to include:
- [x] `print!`
- [x] `println!`
- [x] `format!`
- [x] `{}` vs `{:?}`
- [x] `{:b}` and other formatting parameters
- [x] Why doesn't `{}` work for vectors and generic containers?
- [ ] Explain `{:#?}` [RFC 640](https://github.com/rust-lang/rfcs/blob/master/text/0640-debug-improvements.md)

@crumblingstatue Note anything else that should be added. I'll add it to the list.

**Comment by mdinger** [comment]
@crumblingstatue I don't think that last cc worked.

**Comment by crumblingstatue** [comment]
I agree that more chapters could be added in the "Formatted print" section.
However, the first introduction to `println!` should use `fmt::Display` for formatting, as that is the natural way to write formatted output. `fmt::Debug` shouldn't be taught as the "default" way of writing formatted output, but it should certainly be mentioned, as it is a useful tool for debugging.

**Comment by mdinger** [comment]
[reddit thread](http://www.reddit.com/r/rust/comments/2ycl15/very_newb_printing_strings_without_quotes/) highlighting confusion usage of `{:?}` created.

**Comment by mdinger** [comment]
Added `{:#?}` to header. This has landed: http://is.gd/hdfaHi

**Comment by mdinger** [comment]
https://github.com/rust-lang/rust-by-example/issues/196 is very similar to this issue but has different suggestions

**Comment by coffeejunk** [comment]
It might be helpful to add a small paragraph about `print!` needing a `flush()` to immediately display text on `stdout`

(ref rust-lang/rust#23818)

**Comment by steveklabnik** [comment]
Looks like there's only one checkbox left; I'd be more than happy to mentor anyone who wants to work on this!

**Comment by maccoda** [comment]
@steveklabnik Looks like this one is also complete thanks to @vishalsodani :smile:

**Comment by steveklabnik** [comment]
🎊
