### ISSUE TITLE
process/pipe example panics because process.stdin is None

### ISSUE THREAD

**Issue by thepatrick** [rust-lang/rust-by-example#505]
```thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:362```

I see the same output both when I run the example on rustbyexample.com and when I execute it locally (seen in both the nightly from a bout a week ago and today)

**Comment by mdinger** [comment]
For [process/pipe](http://rustbyexample.com/process/pipe.html), try replacing:
```rust
let process = match Command::new("wc").spawn() {
    Err(why) => panic!("couldn't spawn wc: {}", why.description()),
    Ok(process) => process,
};
```
With
```rust
let process = match Command::new("wc")
                            .stdin(std::process::Stdio::piped())
                            .stdout(std::process::Stdio::piped())
                            .spawn() {
    Err(why) => panic!("couldn't spawn wc: {}", why.description()),
    Ok(process) => process,
};
```

Seems to work properly. The stdio doesn't seem configured by default anymore.

**Comment by mdinger** [comment]
This is fixed. Should be closed.

**Comment by thepatrick** [comment]
Thanks!
