### ISSUE TITLE
This should be more visible on main rust-lang.org site

### ISSUE THREAD

**Issue by sstirlin** [rust-lang/rust-by-example#509]
The site rustbyexample.com should be much more visible on the main rust-lang.org site.  Currently there's only an obscure link deep down in All docs -> External documentation.  I've read The Book several times over the past months and never even realized that rustbyexample.com existed.

I think it's an excellent companion resource and should be listed prominently next to The Book.

Since the same authors are maintaining it all anyway this shouldn't be a problem :)

**Comment by sstirlin** [comment]
Also, for that matter, the 30-minute intro should also be listed on the main page.  It should look something like this:

Getting Started (30-minute intro)
Book
Rust by Example
API docs
Reference
All docs

**Comment by mdinger** [comment]
Not really the correct place for this. See https://github.com/rust-lang/rust-www/issues/103 where I cloned this too.

**Comment by sstirlin** [comment]
Sounds good.  I'll close it here since it's cloned on rust-www
