### ISSUE TITLE
cfg example perhaps refer to cfg! macro

### ISSUE THREAD

**Issue by mikedilger** [rust-lang/rust-by-example#516]
I was unaware of the `cfg!` macro and for a long time used the `cfg` attribute exclusively with much duplicated code.  Perhaps the http://rustbyexample.com/attribute/cfg.html page could include a small note about the macro

**Comment by mdinger** [comment]
Good idea! I wasn't aware of this either. For reference, this refers to [`std::cfg!`](http://doc.rust-lang.org/std/macro.cfg!.html)
