### ISSUE TITLE
2nd example doesn't compile by default

### ISSUE THREAD

**Issue by orta** [rust-lang/rust-by-example#523]
![screen shot 2015-04-03 at 3 42 31 pm](https://cloud.githubusercontent.com/assets/49038/6987707/17da59a4-da18-11e4-9578-56d790412039.png)

I made no source changes to the example, just hit run.

**Comment by orta** [comment]
Oh, looks like that's part of the process, might be worth mentioning in the pre-text that something is going to be wrong inside it.

**Comment by mdinger** [comment]
Yeah, this could be commented to start or not. There are pluses and minuses to doing it both ways. Instructional errors are more likely to be noticed if there actually is an error though.
