### ISSUE TITLE
HOF Tutorial Does Not Run

### ISSUE THREAD

**Issue by brunobeltran** [rust-lang/rust-by-example#525]
rustbyexample.com/hof.html
Errors out due to failed feature tests.

Error message shown is:

error: unstable feature
note: this feature may not be used in the beta release channel
error: unstable feature
note: this feature may not be used in the beta release channel
error: aborting due to 2 previous errors

**Comment by mdinger** [comment]
Playpen currently doesn't support nightly which is causing this. See https://github.com/rust-lang/rust-playpen/issues/83 . Lets see if they'll add a nightly channel quickly.

**Comment by mdinger** [comment]
Link to [hof](http://rustbyexample.com/hof.html)

**Comment by mdinger** [comment]
This is fixed and should be closed
