### ISSUE TITLE
Explain rules for casting to smaller types in "Casting" section

### ISSUE THREAD

**Issue by brunobeltran** [rust-lang/rust-by-example#526]
The current code in the [Casting](http://rustbyexample.com/type/cast.html) section only has examples where the target of a cast can hold the value.

I think an explanation should be inserted as to why this code prints "still compares equal!" (although that comparison causes a warning, "comparison is useless due to type limits, #[warn(unused_comparisons)] on by default") and "I understand unsigned casting!"

    let x = 1000u16;
    let max_u8 = (std::u8::MAX as u16) + 1u16;
    let y = x as u8;
    let z = (x % max_u8) as u8;

    if 1000 == y {
        println!("Still compares equal!")
    } 
    if z == y {
        println!("I understand unsigned casting!")
    }

I would add it myself but I started learning Rust last night so I'm not confident whether Rust is truly implicitly casting 1000 to u8 to get 232 == y which evaluates to true, or whether the comparison is literally ignored as suggested by the warning. 

I also don't know how signed wrap-around works at all. (Discovered the above via an educated guess).

**Comment by mdinger** [comment]
This is a good question. You could ask on IRC. Someone probably knows. Then post the [botbot](https://botbot.me/mozilla/rust/) log with the answer so someone can write it up unless you want to. If you don't, that's the method anyone else will take unless they already know the answer.

**Comment by brunobeltran** [comment]
No one seemed to be able to agree on the answer (Steve thought that e.g. i8->u8 was gated), so I simply tested my best guess with some huge for loops and wrote up the answer when it worked, in PR #530.

**Comment by mdinger** [comment]
Your PR merged. You should close this or modify the OP so that it states precisely what the remaining problems are.

**Comment by brunobeltran** [comment]
Whoops, thanks for the reminder. I think that fixes my concern.
