### ISSUE TITLE
URL re-writing breaks the back button

### ISSUE THREAD

**Issue by brunobeltran** [rust-lang/rust-by-example#527]
Occasionally (hard to reproduce), when hitting the back button, I'll get a 404. Less often, clicking a link in the sidebar when going from a sub-section to a top-level section will give a 404. 

An example of how the URLs evolve (I don't know what the cause might be, but if it's not obvious I can try to spend some time making it reproducible):
AT>> http://rustbyexample.com/arg/getopts.html
[click "testing"]
AT>> http://rustbyexample.com/test.html
[hit back button (Firefox 37.0 on Ubuntu 14.04)]
AT>> http://rustbyexample.com/arg/arg/getopts.html

Less often, it's something like this
AT>> http://rustbyexample.com/arg/getopts.html
[click "testing"]
AT>> http://rustbyexample.com/arg/test.html

**Comment by steveklabnik** [comment]
This is unfortuantely going to be an upstream bug in Rustbook, and not something we can fix :/

**Comment by mdinger** [comment]
He means gitbook but yeah
