### ISSUE TITLE
"Moving Closure" used but never introduced/explained

### ISSUE THREAD

**Issue by brunobeltran** [rust-lang/rust-by-example#531]
From what I can tell (I have been following the examples fairly carefully and sequentially), the concept of a "moving closure" as mentioned in [threads](http://rustbyexample.com/threads.html)
appears to no longer exist:
https://github.com/rust-lang/rust/issues/4339

More importantly, it is not mentioned anywhere prior to that point, whereat it is not explained.

**Comment by mdinger** [comment]
(I'm aware this need to be improved. I'm just trying to make sure you have somewhere to look for now)

Closures aren't really covered well on rbe. They've been changing rapidly for a while and only recently have stabilized. The [book closure section](http://doc.rust-lang.org/book/closures.html) on [moving closures](http://doc.rust-lang.org/book/closures.html#move-closures) is where you need to check currently. It has been improved recently and is more up to date than it has been for a while.

**Comment by mdinger** [comment]
This is covered [here](http://rustbyexample.com/fn/closures/output_parameters.html) in the updated closures section. This is fixed.
