### ISSUE TITLE
No chapter on impl?

### ISSUE THREAD

**Issue by thejohnfreeman** [rust-lang/rust-by-example#535]
I think it's first used in 13.1 Structures > Visibility, and again in 14.1 Generics > Implementation, but there doesn't seem to be any dedicated chapter covering what an impl is, its purpose, its restrictions, features, caveats, etc.

**Comment by thejohnfreeman** [comment]
Is it chapter 21 named Methods? Maybe move it earlier.

**Comment by mdinger** [comment]
The section you're looking for is definitely [methods](http://rustbyexample.com/fn/methods.html). I think things have changed since you filed this bug so I don't think this bug is still valid.
