### ISSUE TITLE
Example in `Threads` section never runs code asynchronously

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust-by-example#541]
In the example in http://rustbyexample.com/threads.html, the program will wait for each thread to finish before spawning the next one - this could be a bit counterintuitive to people just copy/pasting from rustbyexample.

Doing something like the following would allow for the threads to actually run asynchronously:

```rust
use std::thread;

static NTHREADS: i32 = 10;

// This is the `main` thread
fn main() {
    let mut thread_handles = Vec::new();
    for i in 0..NTHREADS {
        // Spin up another thread
        let handle = thread::scoped(move || {
            println!("this is thread number {}", i)
        });
    
        // store the handle so we can wait for it later
        thread_handles.push(handle);
    }
    
    // wait for all the threads to finish before ending the program
    for handle in thread_handles {
        handle.join();
    }
}
```

**Comment by mdinger** [comment]
This seems like it's fixed now in [threads](http://rustbyexample.com/std_misc/threads.html).
