### ISSUE TITLE
Examples never run (indexOf on undefined POST result)

### ISSUE THREAD

**Issue by cjwelborn** [rust-lang/rust-by-example#542]
None of the examples will run. There is an error in the JS where after the POST result comes back from play.rust-lang.com, the `result.indexOf("error:") !== -1` fails because `result` is undefined. I wish I had a PR to go with this, I may look into it further.

Screenshot:
![rust by example-indexof](https://cloud.githubusercontent.com/assets/3335984/7108785/e5bafef2-e155-11e4-84d9-4c1fba84deb7.png)

The editor stays in the "Running..." state.

**Comment by cjwelborn** [comment]
I think I've figured this out using my browser console. The data that is being sent includes `{version: 'master'}`, and the response is 'Invalid value for version'. Changing to `{version: 'beta'}` solved the issue for me.

**Comment by cjwelborn** [comment]
This is a duplicate of #540, sorry about that. #539 looks like it will fix this anyway.

**Comment by mdinger** [comment]
@cjwelborn Actually, I appreciate the diagnosis though. I'm really bad with javascript and when diagnosing this, I was researching how the playpen works. I found the decorators kinda confusing. Knowing how to diagnose this from the browser/javascript side would have been helpful. So, your post is inciteful.

I learn a lot trying to help out with this site!

**Comment by cjwelborn** [comment]
Thanks. This bug inspired me to make a [rustplay](https://github.com/welbornprod/rustplay) command just now. Just messing around really, because I don't use node often and it was good practice. Anyway, glad I could help.

**Comment by mdinger** [comment]
Nifty!
