### ISSUE TITLE
No version of rust specified for static site generation

### ISSUE THREAD

**Issue by CaseyLeask** [rust-lang/rust-by-example#544]
Following the instructions at https://github.com/rust-lang/rust-by-example#how-to-generate-the-static-site, and rust 1.0.0-beta didn't work for me.
I'm installing rust 1.0.0-alpha now in the hope that it works.

**Comment by CaseyLeask** [comment]
rust-1.0.0-alpha.2 failed as well.

**Comment by CaseyLeask** [comment]
rustc 1.0.0-alpha (44a287e6e 2015-01-08 17:03:40 -0800) failed to run

**Comment by mdinger** [comment]
You should have the rust nightly installed but the beta will work. A few examples will fail without the nightly though. Also install subversion and npm. I think that's all you need.

**Comment by mdinger** [comment]
Master currently isn't building or running in browser but https://github.com/rust-lang/rust-by-example/pull/539 fixed it as of a few days ago. You probably need that PR too for now.

**Comment by mdinger** [comment]
Were these instructions sufficient to get it running? Then all that needs to be done is update the README

**Comment by CaseyLeask** [comment]
@mdinger The 1.0.0beta didn't work, but I've got `make all` and the rest of the commands running for the first time on this nightly:
```
grox:rust(master) $ rustc --version
rustc 1.0.0-nightly (e6a812402 2015-04-14) (built 2015-04-13)
```

I hesitate to recommend that people use the nightly build, because of the potential for future nightly builds to have bugs that the main release line won't.

**Comment by mdinger** [comment]
You only need the nightly for those specific examples which make use of it. The rest don't need it. Rbe will move away from the nightlies over time anyway. It probably won't be needed by Rust 1.1 or 1.2 anymore.
