### ISSUE TITLE
Modules section breaks on `std::old_io::stdio::println`

### ISSUE THREAD

**Issue by CaseyLeask** [rust-lang/rust-by-example#558]
![screen shot 2015-04-24 at 7 21 02 pm](https://cloud.githubusercontent.com/assets/430277/7316080/1608acac-eab7-11e4-8fb8-38a9244f3943.png)

**Comment by mdinger** [comment]
[Modules section](http://rustbyexample.com/mod.html)

**Comment by CaseyLeask** [comment]
Thanks @mdinger, it's all fixed :+1:
