### ISSUE TITLE
Strings chapter broken by split_whitespace error

### ISSUE THREAD

**Issue by fortpolio** [rust-lang/rust-by-example#560]
>error: type `&'static str` does not implement any method in scope named `split_whitespace`
>error: aborting due to previous error

**Comment by mdinger** [comment]
Seems to be fixed. Must be a glitch or something. See above link for more info.

**Comment by mdinger** [comment]
Also, [rbe strings](http://rustbyexample.com/str.html)

**Comment by steveklabnik** [comment]
Yup, must have been temporary. Working now. @fortpolio let me know if it's still not working for you.

**Comment by fortpolio** [comment]
It works now, thanks.
