### ISSUE TITLE
Debug (Hello World/Formatted print/) output has a backwards slash in it

### ISSUE THREAD

**Issue by KingOfThePirates** [rust-lang/rust-by-example#571]
http://rustbyexample.com/hello/print/print_debug.html

```{rust, ignore}
println!("{1:?} {0:?} is the {actor:?} name.",
             "Slater",
             "Christian",
             actor="actor's");
```
Output
`"Christian" "Slater" is the "actor\'s" name.`

**Comment by mdinger** [comment]
Why is this a problem? This example is examining `fmt::Debug` and that's what his looks like when `Debug` is applied.

**Comment by KingOfThePirates** [comment]
I understand where the backwards slash might come from because of my Java background, but nowhere in the Rust book or Rust by Example does it even mention escape sequences, much less tell you what kinds of them there are, and, regardless, the example does not even use one- it just pops up in the output.

I do not want to program by coincidence- what the hell is going on here?

Why is this ok?

**Comment by mdinger** [comment]
It's probably just this bug: https://github.com/rust-lang/rust/issues/24588. A comparison with `fmt::Display` on playpen: http://is.gd/NZS0GZ

From an instruction standpoint I don't consider it that big an issue though. `fmt::Debug` doesn't always format things in an ideal way. `\'` obviously isn't ideal and if that's a problem, use `fmt::Display`. Either way, it's just how Rust prints for now. It's a bigger issue with those unicode characters in the playpen link; you can't even tell what they are supposed to be without a look-up table.

If it bothers you though, submit a PR to add a comment about it. It's just that the `fmt::Debug` implementation isn't being smart enough.
