### ISSUE TITLE
Doc idea: Describe which Rust constructs use pointer indirections and which memcpy

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#576]
I've realized I don't have intuition about how Rust's constructs like Slices and Vecs are laid out in memory, and thus how much of them are inline in structs, how much can be on stack, how much gets copied around.

I've seen mentions how many fields slices and vectors have, but that's not quite enough to visualize how, e.g. `Option<Box<Vec<T>>>` looks like. 

Slices are passed to functions as `&[T]`, but does `&[&[T]]` make sense? Should it be `[[T]]`?

I'd love to see some diagrams that show how many pointer indirections are involved in usage of complex types.

**Comment by steveklabnik** [comment]
We specifically have not and do not guarantee layout yet, so that's part of this. We only guarantee structs with repr(c)

**Comment by pornel** [comment]
I understand you don't guarantee specific layout, but what about indirection? I think you define that indirectly anyway via `Sized` and what's allowed in structs, what can be in recursive structs, etc.

**Comment by pornel** [comment]
e.g. I wonder if `[[T]]` is same as C's `T[][]`. 

It compiles as a function argument, but when I try to use it the compiler `says cannot index a value of type `[[T]]`.

But if I do `&[&[T]]` won't that create pointer-to-a-pointer somewhere, which is an unnecessary level of indirection?

Given how incredibly expensive cache misses are on modern CPUs, it's very important for me to fully understand which types and expressions have hidden pointers.

**Comment by pornel** [comment]
This is what I was after: http://cglab.ca/~abeinges/blah/turpl/_book/data.html
