### ISSUE TITLE
generics/phantom/testcase_units: example adds unnecessary complication

### ISSUE THREAD

**Issue by Letheed** [rust-lang/rust-by-example#582]
The example is about demonstrating the usefulness of phantom types by implementing the Add trait for a Length type.

I think it is unnecessary to do it over a generic <T> type:
`struct Length<Unit, T>(T,PhantomData<Unit>);` should just be
`struct Length<Unit>(f64,PhantomData<Unit>);` (or `f32` as in the example)

The implementation:
```
impl<Unit, T> Add<Length<Unit, T>> for Length<Unit, T> where
    T: Add<T, Output=T> + Clone + Copy {
    type Output = Length<Unit, T>;

    fn add(self, r: Length<Unit, T>) -> Length<Unit, T> {
        Length(self.0 + r.0, PhantomData)
    }
}
```
can then be written:
```
impl<Unit> Add for Length<Unit> {
    type Output = Length<Unit>;

    fn add(self, rhs: Length<Unit>) -> Length<Unit> {
        Length(self.0 + rhs.0, PhantomData)
    }
}
```
Unless being able to implement Length over several type (f32, f64, i32, ...) is needed, there is no point to it, and I think this is not the point of this example (but I might be wrong).

**Comment by mdinger** [comment]
I think this is a reasonable suggestion. The complex bounds here really make this example pretty heavyweight.

**Comment by GregDavidson** [comment]
It would be great to do it the less generic way first, then follow that up with the more generic example so that it's easy to see how the features combine.

**Comment by mdinger** [comment]
Conceptually I agree but compare and contrast between those two pages like this is complicated. It might be better to do the generic `Add` without phantom types. It should be similar but simpler.

Still, complex testcases are useful ... tricky to find a balance.

**Comment by Letheed** [comment]
Maybe as a final showcase in Generics, as 13.9, since it uses generics, where clause, multiple bounds and phantom types ? (though I agree the latter is quite verbose). Maybe throwing in a function defined over generics too, to be complete over the generics' module.

Also, since the point is to demonstrate how all of it is implemented and interacts together, I would tend to think added complexity is not a problem here (as long as it's relevant).

**Comment by mdinger** [comment]
Well, a final set of examples comprehensive over generics does seem like a fine idea. I'm not sure of any other great ideas for examples though except for match operations like dot products and such. Examples are very easy to make unwieldy.

For now though, moving the full generics example to a new section seems fine to me.
