### ISSUE TITLE
Add defaults to generics section

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#585]
The [`Add trait`](http://doc.rust-lang.org/nightly/std/ops/trait.Add.html) uses a default so these should be discussed in generics.

**Comment by steveklabnik** [comment]
We should! For consistency, using `Add` as the example there makes sense too.

I'm happy to mentor anyone who wants to fix this bug!

**Comment by angusiguess** [comment]
@steveklabnik I'd be interested in working on this

**Comment by leodasvacas** [comment]
The stabilized functionality of defaults is only part of a larger feature that got stuck. This may be confusing, see rust-lang/rfcs#2321 for a summary and possible way forward.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
