### ISSUE TITLE
long_tuple can't debug

### ISSUE THREAD

**Issue by tennix** [rust-lang/rust-by-example#589]
In [Tuples chapter](http://rustbyexample.com/primitives/tuples.html), if I added one more element in `long_tuple` and tried to print it with `{:?}`, then it would be an error

`
error: the trait `core::fmt::Debug` is not implemented for the type `(u8, u16, u32, u64, i8, i16, i32, i64, f32, f64, char, bool, bool)` [E0277]
`

In [Debug chapter](http://rustbyexample.com/hello/print/print_debug.html)

> All std library types automatically are printable with {:?} too

I read the `std::fmt::Debug` source code and found there are some limitations for Debug trait. For arrays and tuples, it can't be too long. Since I can't find it documented in trpl or reference, I think we should point it out in rust-by-example

**Comment by mdinger** [comment]
See https://github.com/rust-lang/rust-by-example/issues/127 also.

**Comment by tennix** [comment]
@mdinger yes, there can be long tuples but it can't use Debug trait. If not pointed this out somewhere, people will get confused if they try to print long tuples or long arrays using Debug trait

**Comment by steveklabnik** [comment]
I'd be happy to help mentor someone to fix this bug; we should point out this behavior of tuples for sure.

**Comment by marioidival** [comment]
As @vishalsodani say in PR #915 this is not possible, so this issue can be closed? @steveklabnik
