### ISSUE TITLE
Result of running the code snippets isn't preformatted

### ISSUE THREAD

**Issue by magopian** [rust-lang/rust-by-example#597]
When running code snippets, like the one on http://rustbyexample.com/cast.html, the result isn't preformatted.

This means for example that multiple spaces will be conflated to a single one when displayed. In the above url, there's a `println!("  -1 as a u8 is : {}", (-1i8) as u8);`, but the result doesn't have the two leading whitespaces before the -1.

**Comment by mdinger** [comment]
Yeah. Rbe doesn't leave the output looking nice. The output is much nicer when you run it directly from the playpen. This same example in the [playpen](http://is.gd/rxg1nS).

**Comment by magopian** [comment]
That brings a few questions:
1/ should we be using the playpen?
2/ what is Rbe? Does it need to be fixed? Is it fixable?

**Comment by mdinger** [comment]
Rbe is Rust by example. Rbe does use the playpen. The text is stored and sent over to the playpen encoded as a string I believe. Playpen parses it, runs it and sends the output back as I remember.

It's probably just a css mistake. This was a fairly recent change that modified the formatting: https://github.com/rust-lang/rust-by-example/pull/488. You could try locally reverting it to see if it fixes it. I don't remember what all the css options do without looking them up.

It's pretty low priority either way. There are still some big weakpoints in the documentation and until they are fixed, back end fixes will likely be low priority.

**Comment by steveklabnik** [comment]
This is now fixed with the port to mdbook; 

```text
Casting: 65.4321 -> 65 -> A
1000 as a u16 is: 1000
1000 as a u8 is : 232
  -1 as a u8 is : 255
1000 mod 256 is : 232
 128 as a i16 is: 128
 128 as a i8 is : -128
1000 as a i8 is : -24
 232 as a i8 is : -24
```

newlines and all
