### ISSUE TITLE
Lifetime bounds are missing from the documentation

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust-by-example#613]
A question I see asked frequently is what the heck `'a: 'b` means in a bound like this:

``` rust
struct Foo<'a, 'b> where 'a: 'b {
    /* ... */
}
```

I didn't see this question addressed in either the section on bounds or the section on lifetimes.

**Comment by mdinger** [comment]
This is now explained in either [lifetime/bounds](http://rustbyexample.com/scope/lifetime/lifetime_bounds.html) or [lifetime/coercion](http://rustbyexample.com/scope/lifetime/lifetime_coercion.html) though `'a: 'b` isn't listed under one of the rules...maybe it should be added.

**Comment by steveklabnik** [comment]
Yup. Closing!
