### ISSUE TITLE
Comments should be better styled

### ISSUE THREAD

**Issue by eccegordo** [rust-lang/rust-by-example#619]
There is no font color distinction between commented text and code text. This makes it really hard to distinguish code from comment and hampers overall readability, IMHO. Even setting the comment color to 50% would help a lot.

![struct_visibility___rust_by_example](https://cloud.githubusercontent.com/assets/497659/8771114/b66c6bb8-2e71-11e5-9608-4df518452ffd.png)

**Comment by mdinger** [comment]
This is recent. I'm not sure when it started but it's weird.

**Comment by mdinger** [comment]
Seems to have changed from when this was updated: https://github.com/ajaxorg/ace/pull/2586

Playpen works properly so rbe is probably just doing something weird.

**Comment by mdinger** [comment]
@bluss you monitored that PR going in. The [ace kitchen sink](http://ace.c9.io/build/kitchen-sink.html) shows the same issue so it seems to be ace which is the problem. I'm thrown by playpen working properly though. Any idea?

**Comment by mdinger** [comment]
That PR merged July 11: [playpen](https://github.com/rust-lang/rust-playpen/commits/master) doesn't show anything obvious which would be related.

**Comment by mdinger** [comment]
I think I see the problem. The operators regex is falsely stating `//` is an operator. I think I can fix it.

**Comment by mdinger** [comment]
I fixed this in https://github.com/ajaxorg/ace/pull/2600 so this should be fixed the next time is updated.
