### ISSUE TITLE
Example of traits' use of bounds includes previously un-described syntax

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang/rust-by-example#627]
In [**15.3: Bounds**](http://rustbyexample.com/trait/bounds.html), the example code includes the following:

``` rust
impl<T: Add<T, Output = T>> Add<Vec2<T>>
        for Vec2<T> {
// ...
}
```

The declaration with the type assigned `Output = T` has not been covered previously in the book, and it's neither commented here, nor readily apparent from the context, how it behaves. (I'm off to go look it up in the main docs myself presently!)

**Comment by mdinger** [comment]
I think you're looking for [generics/constraining](http://rustbyexample.com/generics/assoc_items/constrain.html). I'm not sure this section should still exist or not ... either way, if you read carefully and compare it to [generics/bounds](http://rustbyexample.com/generics/bounds.html) (the generics text was based on the trait text), you'll see the explanations are very similar but the examples are very different. That's probably why both were kept. An easy fix would be to stick a "See Also" section on the end which references the other section.

**Comment by chriskrycho** [comment]
Ah, you are correct—I’d gone looking for that and missed it. I can
submit a PR with some text to that effect later; it was *very* easy to
miss (as I expressly went looking for it and couldn’t find it). I may
see if I can add a slightly more detailed explanation of the assignment
bounding type on generics/constraining.

Also worth note: the verbiage on the `where` clause variant with the
assignment operator in generics/constraining indicates that it’s not
functional; it’s not clear in the *text* what the status is for the
inline assignment operator (e.g. `<T = i32>`), though of course it is
implemented and does work.

I’m wondering if it might be worth putting the writeup on bounds like
that in the generics section, and then just *referencing* it in the
associated items bounding section?

I’d be happy to put together a PR for these changes (or others to the
same effect you guys think would be better).

**Comment by mdinger** [comment]
Generally only things that work are explained however in this case a non-working example is given because it needs to be understood to explain the shorthand. The fact that the shorthand works at all without the original form is really strange though. Having a comment stating it works wouldn't be a bad idea though.

```rust
fn apply_eq<C>(c: C) where
    C: Contains,
    C::A = i32 { ... }
```

I don't know what you mean about putting bounds in generics. The text in [generics/bounds](http://rustbyexample.com/generics/bounds.html) is already very similar to [trait/bounds](http://rustbyexample.com/trait/bounds.html). If you look at the main points of the text in both sections, they are almost identical.

**Comment by chriskrycho** [comment]
Sorry, in my comment on the "bounds in generics", I was getting confused by the similarity of generics/bounds and trait/bounds. I think your previous suggestion to **See also** [Constraining](http://rustbyexample.com/generics/assoc_items/constrain.html) in the traits/bounds would probably be a good first step.

That said, all the examples in generics/constraining are of the form that applies *only* to constraints (i.e. they all use `Contains`) and this form appears to be valid in `where` clauses more generally, per its use in trait/bounds (as noted in the original post). Maybe we could add an example using the assignment form in [generics/where](http://rustbyexample.com/generics/where.html)?

**Comment by mdinger** [comment]
I don't think they're different; trait/bounds is just much more complicated:

```rust
// Use generics to implement `Sub` for `Vec<T>`.  `T` may be anything so far.
impl<T> Sub<Vec2<T>> for Vec2<T>
// Constrain `T` with the `Sub` trait when input is `T`. Then
// `Output`  must be the same type.
//
// This follows the same rules as in  generics/associated items/constraining.
// In that section, the type `Contains` has no type parameters; that is, it is
// `Contains` and *not* `Contains<T>`. Even without a type parameter, a `<>` is
// added for the equality shorthand: `Contains<A = i32>`. Likewise here,
// `Sub<T>` becomes `Sub<T, Output = T>`.
        where T: Sub<T, Output = T> {
// Write the rest of the method like normal
    type Output = Vec2<T>;

    fn sub(self, rhs: Vec2<T>) -> Vec2<T> {
        Vec2 {
            x: self.x - rhs.x,
            y: self.y - rhs.y,
        }
    }
}
```

A couple things to note:
* Sections like [functions/closures](http://rustbyexample.com/fn/closures.html) and [generics](http://rustbyexample.com/fn/closures.html) must be ready sequentially from top to bottom.
* Generics are really complicated and have to be considered carefully. They lead to a lot of really complicated looking expressions which are far from obvious.
* In general, I think the generics section is pretty helpful in informing you what you can and cannot do but there are a bunch of cases which are missing.
* I would not be inclined to turn fairly straightforward examples like [generics/where](http://rustbyexample.com/generics/where.html) into complicated testcases. Those are the domain of testcases.

**Comment by chriskrycho** [comment]
I agree with you on all your bullet points, and I think you're right that complicating [generics/where](http://rustbyexample.com/generics/where.html) would be a mistake.

I'm tracking with you on the elaborated example code, as well—though it took me reading through it a few times just now to get it locked in mentally. For some reason the analogy between `Contains` and `Sub` wasn't coming clear in my mind initially; I think I was getting some mental noise from "Constraining" with "Contains" and not processing that `Contains` was just a normal `trait`. Perhaps I'm just slow to catch on! But as you say, it's complicated both syntactically and semantically.

I think that traits' being used—especially in this fairly involved way—before they're explained complicated things for me. The syntax in play is specific to traits, which I think contributed to my failure to absorb that example fully. (I assume there's a reason why traits are saved until so late in the book, and I do note that they're linked on the relevant pages in the generics section..)

**Comment by mdinger** [comment]
I consider traits as introduced and explained in generics (section 13) where they are introduced, bounds are introduced, empty bounds are used as an example (actually, I thought an empty trait was really weird for a long time hence the [empty trait example](http://rustbyexample.com/generics/bounds/testcase_empty.html)).

The traits (section 15) section is more about "hey, you understand traits so here are some extra things you can do with them. Well, I'll also throw in some std library traits to fill it out".

Anyway, this bug fundamentally seems to be a misunderstanding (which is reasonable. docs which are only usable by people who already understand are pretty useless). The [traits/bounds](http://rustbyexample.com/trait/bounds.html) section definitely needs some links to the sections where the explanations are. If you can think of anything else concrete which could be done which would have made this more understandable for you, please state them.

**Comment by chriskrycho** [comment]
Hmm, I *really* disagree about traits being explained in the generics section. [generics/traits](http://rustbyexample.com/generics/gen_trait.html) doesn't really explain what a `trait` is, it just says, "Of course, `trait`s can be generic too," and then gives an example of a generic use of traits. In fact, having that line in the generics *without* knowing what a trait is was kind of weird to me reading through: why "of course"? We don't even know what traits are yet!

The *conceptual* explanation of what traits are and how they relate to types that implement them comes in [**15 Traits**](http://rustbyexample.com/trait.html) itself, and I think that conceptual framework is pretty key to understanding how the bounds work—at least for me, that's a big part of why `Contains` and `Sub` didn't process: I hadn't assimilated traits yet.

I don't know whether the team is open to this or not (@steveklabnik?), but I think just moving the Traits section to before Generics would help a _lot_ with clearing this up. The only substantive change other than order that would entail would be explaining the particular case that brought this up in the Traits section rather than the Generics section. I imagine that would need a bit broader a discussion, though!

In the meantime I can submit a small PR for adding links to to the sections of the explanations, at least, and that should be helpful even if the team doesn't want .

**Comment by mdinger** [comment]
Regarding the team, I write almost all the new content but nothing lands without steve's +1. I assume I have some sway but I don't really know.

Okay, not stating what a `trait` actually is is an oversight (I think...not sure now...). Hmm...as a section though, traits might go better under functionality...not sure. Regardless, understanding of the traits/bounds problem is surely hindered more by not understanding generics than not understanding the single phrase (which might just be an oversight): "A trait is a collection of methods declared/defined for an unknown type".

Still, the [traits example](http://rustbyexample.com/trait.html) (which is good) is followed basically by a bunch of miscellaneous examples with no theme or goal other than bounds which is a restatement of a previous example which has a more difficult and much more complicated example (the example, while difficult, is good so it was kept). I would be more inclined to move the good points of the traits section into earlier section than to move the entire miscellaneous section earlier.

**Comment by steveklabnik** [comment]
@mdinger , as an active contributor to this repo, you do have sway :)

I haven't read the relevant sections in a while, @chriskrycho , so I'll toss this onto my list of "RBE needs review" stuff, which is taking a while. Spent most of today dealing with the 1.2 release...

**Comment by chriskrycho** [comment]
@steveklabnik, I can't imagine why that would be so. Launching a minor revision of a programming language into the world is just a *small* thing, right? Thanks for that! There's no urgency on this; I'm just writing it up while it's fresh, trying to do my small part as a guy in the "newbie" phase while I'm still in it and remember the things that confused!

@mdinger, I may just be coming at it from a different angle, but I see traits as relatively orthogonal to generics. There are lots of ways to implement traits/type-classes in a language that don't entail the approach (or syntax!) taken by Rust for generics. I certainly don't think you need to understand generics before you can understand `trait`s, because it's pretty straightforward to construct examples of things (like `Add`!) that don't require generics to show how powerful traits can be.

I also think the examples throughout the section actually do a really good job of show the ways that a `trait` can be employed—not so much the grab-bag feel you get from it. Indeed, I thought that section was one of the clearest and most graspable in the book. The examples were eminently practical, and they all made a lot of sense to me—this one bit of syntax aside. It's *definitely* more approachable than the scoping rules, which currently precede it!

For whatever it's worth, here's the approach I would take if I were moving it:

  - Move the whole Traits section to one of two places:
      + just before Generics, as an easier lead-in to one of the harder concepts and syntaxes in Rust.
      + just after `macro_rules!`—it's a great follow-up to [macros/dry](http://rustbyexample.com/macros/dry.html) and the functions section.
  - Instead of basically duplicating the Bounds section between [trait/bounds](http://rustbyexample.com/trait/bounds.html) and [generics/bounds], just leave it in generics/bounds, with reference back to the earlier, more general discussion in traits.
  - if it feels too short, add another example of using traits—possibly finding one that's a good lead-in to generics, to cap the section and provide a good transition.

I think you could just leave the rest as-is, and it works quite well. With regard to this specific example, you're right that it's a good example. Perhaps doing it in two parts under [generics/bounds] would do the trick: introduce a more basic form as a test case, then elaborate on it?

[generics/bounds]: http://rustbyexample.com/generics/bounds.html

**Comment by mdinger** [comment]
@chriskrycho I guess I'm not really opposed to your recommendation but I would change how traits/bounds is written or move the example or something. I'd probably put them close to the functions and macros section because that's what traits are usually used for. See also the final three comments in https://github.com/rust-lang/rust-by-example/issues/582#issuecomment-109646823 which seems a little related as it is discussing adding another slightly simpler add example to generics (which could be similar to putting the traits/bounds example in generics somewhere).

Your grab bag critique is well founded based on what I have stated here. My focus has for the most part been on trying to get the documentation to where a topic is understandable by sequentially reading the section (something I think has been lacking for a long time). Knowing how to practically use that knowledge is a different question entirely.

Note also: the scoping rules is supposed to change with https://github.com/rust-lang/rust-by-example/pull/607 whenever it lands.

**Comment by chriskrycho** [comment]
@mdinger, your comment on macros is *exactly* what I was thinking about using them to define functionality.

I'll take a gander at #607. Don't take my previous comment about the scopes as a critique; scoping rules are varying degrees of subtle in every language I've used, from Fortran to JavaScript, and they're particularly important and nuanced in Rust for good reason. I followed that well; it's just a complicated topic. If you've managed to improve on the previous pass, outstanding.

Once @steveklabnik has a chance to comment (as noted above, no urgency), I'll look at putting together a PR.

**Comment by mdinger** [comment]
@steveklabnik I did read your comment I just didn't have any great response other than "Oh, that's good" I guess. It's definitely good you're following these threads too.

**Comment by steveklabnik** [comment]
Hi @mdinger , @chriskrycho ,

Do either of you have a decent summary here? is this issue still important? There's a lot going on...

**Comment by chriskrycho** [comment]
Haha, wow, I have *no* idea. I'd say: let's close this issue at this point. I think some of the stuff up-thread I suggested is still a good idea, but I think RbE probably needs a much more thorough review than I'm able to give it for me to say whether the specific suggestions here are still valid.
