### ISSUE TITLE
Valgrind output on mac confusing for panic.rs http://rustbyexample.com/std/panic.html

### ISSUE THREAD

**Issue by sumproxy** [rust-lang/rust-by-example#632]
```
rustc check.rs && valgrind --leak-check=full ./check
==17032== Memcheck, a memory error detector
==17032== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==17032== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==17032== Command: ./check
==17032== 
--17032-- ./check:
--17032-- dSYM directory is missing; consider using --dsymutil=yes
thread '<main>' panicked at 'division by zero', check.rs:5
==17032== 
==17032== HEAP SUMMARY:
==17032==     in use at exit: 25,266 bytes in 372 blocks
==17032==   total heap usage: 460 allocs, 88 frees, 31,674 bytes allocated
==17032== 
==17032== LEAK SUMMARY:
==17032==    definitely lost: 0 bytes in 0 blocks
==17032==    indirectly lost: 0 bytes in 0 blocks
==17032==      possibly lost: 0 bytes in 0 blocks
==17032==    still reachable: 136 bytes in 1 blocks
==17032==         suppressed: 25,130 bytes in 371 blocks
==17032== Reachable blocks (those to which a pointer was found) are not shown.
==17032== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==17032== 
==17032== For counts of detected and suppressed errors, rerun with: -v
==17032== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 15 from 15)
bash-3.2$ rustc --version
rustc 1.2.0 (082e47636 2015-08-03)
bash-3.2$ 
```

**Comment by mdinger** [comment]
I think [std/panic](http://rustbyexample.com/std/panic.html) is the page he's referring to:

**Comment by sumproxy** [comment]
Yes, that's the one

**Comment by mdinger** [comment]
I can't reproduce.

I just checked with `rustc 1.4.0-nightly (5aca49c69 2015-08-10)` and with `rustc 1.2.0 (082e47636 2015-08-03)` and I don't see memory leaks. Is the code the same as is on the page? I'm using valgrind version 3.10.0.SVN where you're using 3.10.1. That's the only difference I see.

**Comment by sumproxy** [comment]
The code is copied one-to-one
the system I'm using is 
Darwin localhost 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

**Comment by nnethercote** [comment]
There is no leak. See this?
```
ERROR SUMMARY: 0 errors from 0 contexts
```
If there was a leak, this count would be non-zero. Having "still reachable" memory is common and reasonable. See http://valgrind.org/docs/manual/mc-manual.html#mc-manual.leaks, which says the following:

'Since the block is still pointed at, the programmer could, at least in principle, have freed it before program exit. "Still reachable" blocks are very common and arguably not a problem. So, by default, Memcheck won't report such blocks individually.'

**Comment by mdinger** [comment]
Even if this bug is invalid, it'd probably be worth putting a note somewhere about this. This could be confusing/surprising if you don't know anything about valgrind.

**Comment by sumproxy** [comment]
Should I change the title to something else or just close it?

**Comment by mdinger** [comment]
Changing the title is probably fine. Valgrind on mac is scary for panic or something.

**Comment by nnethercote** [comment]
I suggest closing. There is no bug here. The Rust program is behaving perfectly reasonably.

**Comment by sumproxy** [comment]
Closing as unrelated to rust behavior
