### ISSUE TITLE
Emphasize both &T and &mut T are valid as types

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#646]
This is a clone of https://github.com/rust-lang/rust/issues/28684

---

The docs mainly use `&` and `&mut` as binding examples and even suggest `mut` is a property of binding and not a type. This led me to conclude the following:

``` rust
// Assumed invalid
struct Borrow<'a>(&'a mut i32);
// Assumed the proper way to do this
struct Borrow<'a>(&'a i32);

let i = 3;
// `mut` is added here instead
let b = Borrow(&mut i);
```

The fact that both `&T` and `&mut T` are valid as types and not just as bindings should be emphasized to clarify this.

Maybe it could go in the "Custom Types" section...

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
