### ISSUE TITLE
Make the index button work for javascript-less clients

### ISSUE THREAD

**Issue by NawfelBengherbia** [rust-lang/rust-by-example#649]
Rust by Example looks nice and works well without Javascript. The only thing it misses is an index page.

**Comment by mdinger** [comment]
I think this is controlled by gitbook so you'd have to send this upstream

**Comment by NawfelBengherbia** [comment]
[Done](https://github.com/GitbookIO/gitbook/issues/965)

**Comment by steveklabnik** [comment]
Thanks! since it's an upstream issue, I'm going to close it here, as it'll get fixed next time we update after they fix it.
