### ISSUE TITLE
Lifetime explanations don't currently account for lifetimes inherent flexibility

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#658]
PR https://github.com/rust-lang/rust-by-example/pull/655 pointed out that the section on lifetimes doesn't properly specify the size of a lifetime. A specific confusion was whether the lifetime size is chosen by the scope of the reference or the scope of the owned variable. In actuality, the size may be chosen as one or the other or anywhere in between depending on context. Changing the context can change the lifetime. This should be detailed more properly.

See https://github.com/rust-lang/rust-by-example/pull/655#issuecomment-153303105 in particular for more specifics of how it should be improved.

**Comment by Xmasreturns** [comment]
As an update, I tried to address some of this in #711 and #710

**Comment by steveklabnik** [comment]
I'm going to close this one out since those PRs were merged; @mdinger if you have more specifics, please open a new issue!
