### ISSUE TITLE
Activity: Arrays and slices

### ISSUE THREAD

**Issue by absoludity** [rust-lang/rust-by-example#675]
It would be great to have an activity to go with the [Arrays and slices example](http://rustbyexample.com/primitives/array.html)
For an example of a small activity, see [Display](http://rustbyexample.com/hello/print/print_display.html)

For an example of a larger activity, see [Tuples](http://rustbyexample.com/primitives/tuples.html)

**Comment by absoludity** [comment]
@steveklabnik or @mdinger : can you add an "activity" label (or similar) to this issue, and #676 and #677 please? I'm doing a talk tonight and just trying to ready some activities that people might be able to assign to themselves. No problem if not - I can still get them [searching issues for activity](https://github.com/rust-lang/rust-by-example/search?q=Activity&type=Issues&utf8=%E2%9C%93)

**Comment by mdinger** [comment]
I'd just create an issue called activities to add and make a checklist of things that need to be done. See task lists [here](https://guides.github.com/features/mastering-markdown/) for an example.

**Comment by absoludity** [comment]
@mdinger OK - will do. I'd wanted people to be able to assign tasks to themselves - but right, it's probably easier just to comment and I can update the task list. Thanks.

**Comment by mdinger** [comment]
Also, I don't have access to adding labels and @steveklabnik hasn't historically added labels when people asked for them as I remember. Also, the number of people who submit PRs to this repository is fairly small and the gain from doing so would likely be fairly small.

**Comment by steveklabnik** [comment]
I don't have any real aversion to adding a label if it's useful, but

>  I'd wanted people to be able to assign tasks to themselves

GitHub only allows those with commit to do such assignments.

**Comment by absoludity** [comment]
@steveklabnik , @mdinger Yep, as above, people can just comment if they're interested and I can update a task list in the description. I'll do that on the next once I've finished the above activities. Thanks.

**Comment by steveklabnik** [comment]
(meta; I've deleted some off-topic historical commentary here that's not relevant to the issue)

Yup, adding an activity sounds great; let's brainstorm some ideas!

**Comment by Morsicus** [comment]
How about a software checking if two arrays have the same elements  (don't care of the order, don't care of the duplicates) ? 

It was a question coming from IRC.

**Comment by absoludity** [comment]
Yep, that could work, though it's quite a step from the examples on the page. It might be good to have a few steps to get to that? For example, the activity could start by comparing the lengths, then comparing for equality (ie. order and duplicates do matter), then updating to that order doesn't matter, then duplicates don't matter?

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
