### ISSUE TITLE
Activity: Structures

### ISSUE THREAD

**Issue by absoludity** [rust-lang/rust-by-example#676]
It would be great to have an activity to go with the [Structures example](http://rustbyexample.com/custom_types/structs.html)

For an example of a small activity, see [Display](http://rustbyexample.com/hello/print/print_display.html) (this one already has the reader creating a struct based of an example, so it could be more interesting on the structs example itself).

For an example of a larger activity, see [Tuples](http://rustbyexample.com/primitives/tuples.html)

**Comment by ubsan** [comment]
Triage: this seems to be fixed.
