### ISSUE TITLE
Activity: Enums

### ISSUE THREAD

**Issue by absoludity** [rust-lang/rust-by-example#677]
It would be great to have an activity to go with the [Enums example](http://rustbyexample.com/custom_types/enum.html). One idea - an HttpStatus enum which has OK, Redirect, Error etc., but where each can include a status code, with something similar to the inspect function on the page already?

For an example of a small activity, see [Display](http://rustbyexample.com/hello/print/print_display.html)

For an example of a larger activity, see [Tuples](http://rustbyexample.com/primitives/tuples.html)

**Comment by steveklabnik** [comment]
I agree, that idea sounds good. Maybe we can flesh this idea out a bit and then someone can send in a PR?

**Comment by Morsicus** [comment]
I like your activity @absoludity. For a more "academical" activity a fizz buzz game could be an idea too. What do you think ? I will be happy to help on this :)

**Comment by absoludity** [comment]
It'd be quite a step from the examples to a fizz-buzz game (and possibly hard to do without assuming other existing knowledge?). It sounds like a great idea for an activity at the end of a larger section, for eg., after the flow-control or functions sections?

**Comment by Morsicus** [comment]
Indeed. Opening an other issue.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
