### ISSUE TITLE
generics/assoc_items: Confusing variable names

### ISSUE THREAD

**Issue by Seeker14491** [rust-lang/rust-by-example#681]
To me, using the variable name `number` to refer to the first item, and the name `digit` to refer to the second item in the examples on  '[The problem](http://rustbyexample.com/generics/assoc_items/the_problem.html)' and '[Associated types](http://rustbyexample.com/generics/assoc_items/types.html)' pages is confusing. The names `first_number` and `second_number` would be better.

**Comment by mdinger** [comment]
This would be good fix. Something like `number1` and `number2` might also be an option

**Comment by Seeker14491** [comment]
@mdinger That's good too, though lets make it `number_1` and `number_2` to follow the [naming conventions](https://github.com/rust-lang/rfcs/pull/430).

**Comment by mdinger** [comment]
This is an easy fix so I won't implement it but else anyone is welcome to.
