### ISSUE TITLE
Proposal: Remove code block in "10. Modules"

### ISSUE THREAD

**Issue by Xmasreturns** [rust-lang/rust-by-example#690]
In its current incarnation, the example code block in ["Ch 10. Modules"](http://rustbyexample.com/mod.html)  serves only to confuse readers.

Prior to introducing syntax for defining public modules and introducing `module::item` syntax, the sample code raises questions regarding what can and can't be used. However, this is obfuscated by requiring `#[allow(dead_code)]` to avoid defining a public module to align with the rest of the chapter. For that purpose, all of the included information (ability to nest modules/call on item in module/module item visibility) is shown immediately afterwards in "Ch 10.1 Visibility". As a result, the code in "Ch 10. Modules" is unhelpful at best.

I propose to remove the code block in "Ch 10. Modules", such that it resembles ["Ch 7. Flow Control"](http://rustbyexample.com/flow_control.html) - containing only a short description of what a module is.

**Comment by steveklabnik** [comment]
Seems reasonable.

**Comment by mdinger** [comment]
I also have no real problem with this.

**Comment by Xmasreturns** [comment]
This change is included in PR #691
