### ISSUE TITLE
make all error 101 on Ubuntu 14.04

### ISSUE THREAD

**Issue by tiansiyuan** [rust-lang/rust-by-example#693]
make all
./setup-stage.sh
取出版本 134。
cargo run
 Downloading regex v0.1.41
unable to get packages from source

To learn more, run the command again with --verbose.
make: *** [all] 错误 101

**Comment by steveklabnik** [comment]
This is a bug in Cargo, not in RBE directly. Mind filing this over at https://github.com/rust-lang/cargo/issues/new ? Thanks!

**Comment by tiansiyuan** [comment]
Done. 

Thanks.
