### ISSUE TITLE
Superfluous tuple at the end of “14.3.4 The ref pattern”

### ISSUE THREAD

**Issue by sscherfke** [rust-lang/rust-by-example#695]
At the end of the example code in section [14.3.4 ref pattern](rustbyexample.com/scope/borrow/ref.html), there are the lines

```
    let tuple = (Box::new(5u32), 3u32);

    println!("tuple is {:?}", tuple);
```

If I’m not wrong, they don’t make any sense in this context or add anything meaningful.  Should they maybe be deleted?

**Comment by mdinger** [comment]
I don't know either. What you're suggesting would probably be okay

**Comment by russmack** [comment]
Closed, I think.  [http://rustbyexample.com/scope/borrow/ref.html](http://rustbyexample.com/scope/borrow/ref.html)

**Comment by steveklabnik** [comment]
You're right @russmack , thanks!
