### ISSUE TITLE
13.7.2 Associated types - block code colors missing

### ISSUE THREAD

**Issue by Xmasreturns** [rust-lang/rust-by-example#697]
http://rustbyexample.com/generics/assoc_items/types.html
I noticed on the coloring of block code (not the runnable example code) in 13.7.2, 13.7.3, and 13.8.1 is missing, while it's available on pretty much every other page I can find where block code exists. It didn't seem like an issue with the .md files themselves, as the `rust` indicators are there.

Any ideas on what's causing this?

**Comment by mdinger** [comment]
I think I've noticed it before and kinda suspect it is highlighting only working on one of the code blocks in the page. The examples are generated separately and so have their own separate issues.

FWIW, in the near future, I'm expecting that [mdBook](https://github.com/azerupi/mdBook) will get decent ace support which I think will allow rbe to be ported over. Thus, issues like this should become non-issues. See [this](http://azerupi.github.io/mdBook/format/rust.html#Inserting%20runnable%20Rust%20files). Note: Ace still needs to be enabled along with a proper example reset. This should also allow multiple runnable examples on the same page if that is desired. Rbe currently only supports a single runnable example on a page for whatever reason.

**Comment by steveklabnik** [comment]
Yup! We've now ported, so this can be closed.
