### ISSUE TITLE
13.7.3 Constraining - Not implemented?

### ISSUE THREAD

**Issue by Xmasreturns** [rust-lang/rust-by-example#700]
http://rustbyexample.com/generics/assoc_items/constrain.html
Two main issues:
1) This page doesn't provide any description of what's actually being considered "constraining".
2) It actually says "// Caveat: This hasn't been implemented yet and doesn't work."

Are there plans for Rust to have this implemented in the near future? If not, then I propose a deletion of the page entirely as it doesn't seem to provide any useful information.

If the implementation is coming soon, what's the proper way to hide this page until it becomes useful?

**Comment by steveklabnik** [comment]
I agree with just deleting it.

**Comment by mdinger** [comment]
Does the book cover this topic at all yet? To delete it from the online book you delete it from the `structure.json` file I think. The alternative is to delete it entirely in a single commit so if it was ever reverted, it'd be easy.

I'm okay with this suggestion. That bug really needs to get fixed sometime.
