### ISSUE TITLE
Proposal: Remove 13.7.4 Testcase:Add

### ISSUE THREAD

**Issue by Xmasreturns** [rust-lang/rust-by-example#701]
I propose the removal of 13.7.4 to remove redundant material.

http://rustbyexample.com/generics/assoc_items/testcase_add.html
The example on this page doesn't show anything new to the reader. Compared to the bottom example on [the associated types page](http://rustbyexample.com/generics/assoc_items/types.html), it is less comprehensive, more repetitive in nature, and backtracks with respect to section order.

**Comment by mdinger** [comment]
I guess I don't really have a strong opinion here either way. In a sense, I can see the earlier one as slightly simpler which might be appealing while it deals with the varying permutations the later example bans. On the other hand, your grasp of what reads right and proper seems excellent so I wouldn't mind deferring to your judgment here.

I have no issues with accepting this proposal unless @steveklabnik does.

**Comment by steveklabnik** [comment]
Apparently github didn't save my comment, I meant to say "I suppport just removing it"
