### ISSUE TITLE
custom_types/enum/testcase_linked_list: Add activity

### ISSUE THREAD

**Issue by dporru** [rust-lang/rust-by-example#709]
I feel `custom_types/enum/testcase_linked_list` is missing an activity. A possible activity would be to add an `append` method.
I would be willing to add it.

**Comment by steveklabnik** [comment]
Sounds great; what do you think `append` would look like?

**Comment by dporru** [comment]
It's been a while since I looked at this, but I suppose there are two possible implementations:

In place:
Let the second last item point to the item you want to append. The item you want to append will point to Nil.
This alters the list, which is different from the prepend method in that manner.

Copy:
Create a new list by copying all the elements and again let the second last item point to the item you want to append.

I don't know which would be more intuitive.

I suppose both would need to be implemented recursively. I haven't used Rust in a while unfortunately, so I don't have a clear picture about this.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
