### ISSUE TITLE
Copy/paste not working

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-by-example#712]
**tl;dr:** Copy/Paste not working(correctly), for me, in Linux when Firefox's about:config `dom.event.clipboardevents.enabled` is set to the non-default value of `false`

Tested on page: https://rustbyexample.com/hello.html but only inside the example area/frame of the Hello world rust code (outside of it, it works)

Seems to be the same issue(the ACE editor?) like here: https://github.com/rust-lang/rust-playpen/issues/69#issuecomment-155036257

**Comment by steveklabnik** [comment]
Yes, it's probably an upstream issue with ACE.

**Comment by aoaaxy** [comment]
They say ACE requires clipboard events to work, and since I was disabling them by the above, that's why copy didn't work, see: https://github.com/ajaxorg/ace/issues/2794#issuecomment-180786353

**Comment by steveklabnik** [comment]
We've now changed to mdbook; OP is gone. Closing!
