### ISSUE TITLE
Bad Links

### ISSUE THREAD

**Issue by Vm900** [rust-lang/rust-by-example#717]
Hi
I followed all the installation directions properly but got this error in the end:
cp: cannot stat ‘node_modules/gitbook-plugin-rust-playpen/book/ace/mode-rust.js’: No such file or directory

Checking links...
Bad link in ./examples/std/hash/alt_key_types/input.md:30 [404] http://doc.rust-lang.org/std/collections/struct.VecMap.html
Some links were bad.

Please help
Thanks

**Comment by mdinger** [comment]
Are you on debian, ubuntu, or something else?

**Comment by Vm900** [comment]
Yes freya

**Comment by mdinger** [comment]
FYI for anyone following along, Freya is apparently a [minor release](http://blog.elementary.io/post/134884577281/freya-032-released) for [elementary OS](https://elementary.io/).

Did you install subversion? Does it run under the name `svn`?

**Comment by mdinger** [comment]
By the way, the bad links were just fixed.

**Comment by ubsan** [comment]
Triage: is this fixed? This seems to be fixed.
