### ISSUE TITLE
Panic running http://rustbyexample.com/mod/use.html

### ISSUE THREAD

**Issue by MrMormon** [rust-lang/rust-by-example#718]
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
playpen: application terminated with error code 101

**Comment by mdinger** [comment]
This is because the playpen is throwing errors. See [this](http://is.gd/fSxX75) for another weird case. The errors seem to be shifting around a little. Nightly seems to work. I'd ask on IRC if you're curious why this is happening because someone probably knows.

**Comment by MrMormon** [comment]
I was using the website. Shoulda said.

**Comment by mdinger** [comment]
Removing it would be good. You could refile under https://github.com/rust-lang/rust-www/issues if you feel so inclined.

**Comment by MrMormon** [comment]
Can't remove, but can close.
