### ISSUE TITLE
Embed a playpen-like editor inside the book

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#73]
I got this working [1][2] in the [editor](https://github.com/japaric/rust-by-example/tree/editor) branch and have setup a [clone site](http://japaric.github.io/rbe/hello.html) for testing.

At the moment, I have two bugs to fix:
- [x] The buttons are misplaced, they should be inside the editor area
- [x] You need to refresh the page to see the editor
- [x] Use the same colors when highlighting both static code and the code inside the editor.
- [x] Height of the editor should always fit the contained source code.

I'll like to have other people test it, and let me know if you have any suggestion or if you find any other bug. (or if you know how to fix any of the bugs I have mentioned :P - here's the [css](https://github.com/japaric/rust-by-example/blob/editor/node_modules/gitbook-plugin-rust-playpen/book/editor.css) and the [js](https://github.com/japaric/rust-by-example/blob/editor/node_modules/gitbook-plugin-rust-playpen/book/editor.js) if you want to take a look)

Once we are sure the editor works the way we want, I'll merge this into the original site.

[1] I've reused @SergioBenitez live code editor implementation for the rust-lang.org website. Kudos to him!
[2] Implementation detail: The "{hello.play}" string in the input markdown gets expanded into the live code editor containing the `hello.rs` source code

cc @kud1ing @vojtechkral @vks @zslayton

---
### Original description

The playpen exposes a CORS-enabled JSON API that could be used to embed a playpen-like editor in each example, this would allow the user to run the example, and see the output inline; or experiment further by editing the source code of the example.

See graydon/rust-www#26 for a reference implementation. We should try to provide a similar interface to the one provided by [rust-lang.org](http://www.rust-lang.org) (plus a "Reset" button to show the original example code)

**Comment by chriskrycho** [comment]
Sort of follow up to this: I found this issue while looking around for how to go about implementing the theme change (because reading at night, it's killing my eyes). Anybody know if they added that functionality? Or at least a pointer to where to *look*?

I'd be happy to make whatever changes are necessary on *this* end to support if they have.

**Comment by mdinger** [comment]
Which part? How to change the playpen theme or how to expose it to the webpage as an option?

**Comment by chriskrycho** [comment]
Either or both! My initial looking around at the GitBook implementation
didn't make it clear, though I'm also happy to spend more time digging
on the docs in the next couple days.

**Comment by mdinger** [comment]
Well, changing the theme isn't actually that hard. See https://github.com/mdinger/rust-by-example/commit/767361bf0f09693591f23b1f9ea68b1116d7956b where I change the theme to "tomorrow night" (it still flashes white so I probably missed a css value somewhere though). Valid theme names are listed at [ace](https://github.com/ajaxorg/ace/tree/master/lib/ace/theme). Both the [rust playpen](https://play.rust-lang.org/) and the [ace kitchen sink demo](http://ace.c9.io/build/kitchen-sink.html) support changing themes so you can browse their themes for something you like if that helps.

To use that though, it should probably change to a dark theme when you switch gitbook to a dark theme so you'd have to signal the change somehow and then modify that and all the colors and warnings and such then.

**Comment by chriskrycho** [comment]
Right, and it was hooking into the GitBook events that I was concerned
with; my initial question wasn't clear enough! Does GitBook expose
that event programmatically? Otherwise, can we maybe just add a little
on-page JS to watch another CSS class, and on that basis update the
style sheet reference? I'll take another look at how the Ace style
sheet is attached.

**Comment by mdinger** [comment]
That I don't know. I think I've looked at doing it before but never was sure how to proceed.

**Comment by chriskrycho** [comment]
I’ll take a further look over the course of the week and see if I can see a good way to hook into that event-wise and substitute the CSS. If nothing else, it looks like the style used is just set on the editor div itself like ace-tomorrow (good for them for using it sensibly!) so it should be pretty straightforward to update if there’s an event I can hook into. I may even—as a temporary workaround—be able to do it just by watching for changes to the main book container div. I’ll post a further update when I have more.
