### ISSUE TITLE
`where` is not highlighted as a keyword

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-by-example#730]
On http://rustbyexample.com/generics/where.html

the first example has "impl" and "for" highlighted in color, but "where" in default text color. 

That's unfortunate, because it makes the most important keyword in this example harder to notice.

**Comment by ubsan** [comment]
Triage: fixed

**Comment by pornel** [comment]
The first code block on the page isn't fixed yet: 

![screen shot 2016-07-27 at 10 28 53](https://cloud.githubusercontent.com/assets/72159/17170626/e8a6396c-53e4-11e6-9092-b282aede9788.png)

**Comment by ubsan** [comment]
Ah, 

    ```rust
    ```
blocks are incorrect still.
