### ISSUE TITLE
8.2.4 Mistake in code comment

### ISSUE THREAD

**Issue by gracemi** [rust-lang/rust-by-example#733]
I think that in point [8.2.4](http://rustbyexample.com/fn/closures/input_functions.html), there is a mistake in the first code comment. 
The code comment is: 
// A function which takes a **closure** as an argument and calls it
and it should be
// A function which takes a **function** as an argument and calls it

**Comment by ubsan** [comment]
Bump

This seems to be fixed with #735

**Comment by steveklabnik** [comment]
Thanks!
