### ISSUE TITLE
Chapter 5 Casting: incorrect use of the term "two's complement"

### ISSUE THREAD

**Issue by symingz** [rust-lang/rust-by-example#741]
In the code example, the last comment says "two's complement of 232 is -24". This statement is false according to the definition of two's complement in Wikipedia, which is consistent with my memory of text book definitions. I think the correct way to say this is "the 8bit unsigned representation of 232 is the same as the 8bit two's-complement representation of -24".
To generalize, other uses of "two's complement" in this code example are also wrong.

**Comment by srinivasreddy** [comment]
@steveklabnik  please close this issue
