### ISSUE TITLE
Chapter 5.1 Literals has a weird first sentence

### ISSUE THREAD

**Issue by symingz** [rust-lang/rust-by-example#742]
The first sentence of Chapter 5.1 is this:

"Numeric literals can be type annotated by adding the type as a suffix, with the exception of usize that uses the usize suffix and isize that uses the isize suffix."

According to this sentence, usize and isize are not different from other types, why call them exceptions?

**Comment by mdinger** [comment]
This is probably because the `isize` and `usize` used to use `is` and `us` as suffixes which made them distinct from the others. So the types were properly updated but the sentence was not. Feel free to submit a PR fixing it. Thanks for pointing it out!

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust-by-example/pull/754 fixed this!
