### ISSUE TITLE
extend overloading example by mentioning macros

### ISSUE THREAD

**Issue by vks** [rust-lang/rust-by-example#75]
Currently only traits are mentioned in the overloading example. They only work if the functions to be overloaded have the same number of arguments. Using macros it is possible to have more generic overloading. See for example this implementation of a Python-like `range`:

``` rust
#![feature(macro_rules)]

use std::iter::range_step;

macro_rules! range (
    ($start:expr, $end:expr, $step:expr) => (
        range_step($start, $end, $step)
    );
    ($start:expr, $end:expr) => (
        range($start, $end)
    );
    ($end:expr) => (
        range(0, $end)
    );
)
```

**Comment by steveklabnik** [comment]
I don't feel this is appropriate for the book; using macros for only overloading isn't something that you should do.
