### ISSUE TITLE
1.2:  The 'format pi' question introduces too many concepts at once.

### ISSUE THREAD

**Issue by gregglind** [rust-lang/rust-by-example#761]
```
Add a println! macro that prints: Pi is roughly 3.143, using twenty-two divided by seven to generate the estimate for Pi. (Hint: you may need to check the std::fmt documentation for setting the number of decimals to display)
```
## why improve this?
- mistakes _early_ in tutorials are spirit-killing
- learning 'division' isn't really the point of this lesson.

Issues:
- `22/7` generates an int, which won't format correctly under `{:.3}`.  This is non-obvious and isn't discussed anywhere.
- the link docs to `format!` aren't clear about how to how handle this.  It's one of those obvious things if you are coming from C-derived langs.

Suggested simplifications / fix
- explain something about division here.
- have this instead:

```
let pi = 3.141592;
```
- and have the user control the number of places shown.

**Comment by mdinger** [comment]
You're right and these are tricky. I don't really have objections to this fix. It could be extremely puzzling to run into. The distinction is important but shouldn't be necessary right here. Especially this early.

**Comment by Xmasreturns** [comment]
#763 should have addressed this, so I think this can be closed. Let me know if it's not!

**Comment by steveklabnik** [comment]
Closing!
