### ISSUE TITLE
Error when running "18.4.1 open"

### ISSUE THREAD

**Issue by donaldpipowitch** [rust-lang/rust-by-example#762]
When I run the example ["18.4.1 open" ](http://rustbyexample.com/std_misc/file/open.html) I get an error:

```
thread '<main>' panicked at 'couldn't open hello.txt: entity not found', src/main.rs:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/read-files` (exit code: 101)
```

A `hello.txt` should be available however. What can I do?

```
$ rustc -V
rustc 1.9.0 (e4e8b6668 2016-05-18)

$ cargo -V
cargo 0.10.0-nightly (10ddd7d 2016-04-08)
```

**Comment by steveklabnik** [comment]
Where exactly is the text file in relation to the other files?

**Comment by donaldpipowitch** [comment]
Oh oh... stupid me. It's relative to the source file! `src/main.rs`. But it should be next to the `target/`, right? That's how a beginner looks like. Sorry for wasting your time. I'll close this.

**Comment by donaldpipowitch** [comment]
Well, I have

```
src/main.rs
target/debug/open
hello.txt
```

And changed `let path = Path::new("hello.txt");` to `let path = Path::new("../../hello.txt");`, shouldn't this work? I get the same error.

Also... When `target/debug/open` is my actual compiled program why does the error message `thread '<main>' panicked at 'couldn't open hello.txt: entity not found', src/main.rs:16` contains a reference to `src/main.rs:16`. (Does my program contain references to the original source code much like a source map in JavaScript...?)

**Comment by mdinger** [comment]
You're using cargo and this example doesn't use it. Cargo is a tool which does lots of things including calling rustc to actually compile the code via rustc with the correct flags and download dependencies etcetera.

This example uses rustc which will generate the `open` executable right next to `open.rs`. Running that command as is should work. Your file structure should look like this before you run the command:

```text
test
├───hello.txt
└───open.rs
```

**Comment by donaldpipowitch** [comment]
@mdinger Thanks, but I don't know if it explains any of my questions? If I'd have used `rustc` directly and not with Cargo I'd have written it in the same way as you described. But I don't know why the path resolves differently when I use Cargo...?

**Comment by mdinger** [comment]
Ah, that's a different question. Try `../hello.txt`. Your directory structure should be:

```text
my_open
├───src
│   └───main.rs
│   └───target
│       └───*lots of stuff*
├───hello.txt
├───Cargo.lock
└───Cargo.toml
```

You'll run `cargo run` from the `my_open` directory which will do the running but the `src` directory will be considered the current directory for the program regardless of where the built target happens to be located I believe.

**Comment by steveklabnik** [comment]
> the src directory will be considered the current directory for the program regardless of where the built target happens to be located I believe.

No, it's always relative to the current working directory, which is where `cargo run` is run from.

**Comment by mdinger** [comment]
^ Eh, guess I was wrong but I was pretty sure I tried it from the `my_open` folder and `../hello.txt` worked. Weird. Maybe I remembered what I did incorrectly.

**Comment by donaldpipowitch** [comment]
Thank you both for answering this question.
