### ISSUE TITLE
touch() must also include write(true) or append(true)

### ISSUE THREAD

**Issue by casey** [rust-lang/rust-by-example#765]
I believe that the touch example is incorrect:

https://github.com/rust-lang/rust-by-example/blob/f4fd0b50c10b337bf6eb7706dea62688a53426de/examples/std_misc/fs/fs.rs#L26

If you look at `std::fs::OpenOptions`, it states that if `create(true)` is specified, then `write(true)` or `append(true)` must be set:

https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.create

On OS X, I get this error: `Invalid argument (os error 22)`

**Comment by realcr** [comment]
I am experiencing the same issue on Ubuntu 16.04. Adding the `.write(true)` option solves the problem.

**Comment by xftroxgpx** [comment]
This issue seems to be in need to be closed as per previous merge.
I think github didn't auto-close it because of the extra `issue` word in `Fixes issue #765`
