### ISSUE TITLE
More navigable chapter list

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-by-example#766]
The sidebar with nested chapters is quite sprawling now. It's very hard to get an overview of what's in the book. Maybe the front page could contain a hyperlinked summary of the top level chapters.

**Comment by steveklabnik** [comment]
> Maybe the front page could contain a hyperlinked summary of the top level chapters.

This sounds like a great idea to me; I'm happy to mentor anyone who wants to fix this up!

**Comment by vishalsodani** [comment]
I would like to do this. Can you please suggest what needs to be done here. Just link to html pages on the introduction page?

**Comment by steveklabnik** [comment]
Yes! Basically, think of it as like a short summary: a link and short description of each chapter.

**Comment by marioidival** [comment]
@steveklabnik can close this issue?
