### ISSUE TITLE
18.5.2: It seems there is no wait while process goes out of scope

### ISSUE THREAD

**Issue by lucklove** [rust-lang/rust-by-example#769]
![image](https://cloud.githubusercontent.com/assets/8718109/16706379/89882b18-45dc-11e6-8d93-9d83700338cb.png)
It seems not match with [the example](http://rustbyexample.com/std_misc/process/wait.html)
Any thing wrong?

**Comment by lucklove** [comment]
Should call Child::wait explicitly?

**Comment by mdinger** [comment]
The example is no longer correct. This is probably what you want.

```rust
use std::process::Command;

fn main() {
    let _process = Command::new("sh")
                           .arg("-c")
                           .arg("sleep 10")
                           .spawn()
                           .expect("failed to execute process");

    println!("reached end of main");
}
```

Documentation is under [`Command`](https://doc.rust-lang.org/std/process/struct.Command.html). If you need to capture output, it is under [`output`](https://doc.rust-lang.org/std/process/struct.Command.html#method.output).

**Comment by mdinger** [comment]
Actually, I'm not sure now. Is it actually working incorrectly with the current command? I mean, I run the following multiple times quickly and get:

```cmd
mdinger:~$ rustc test.rs && ./test && ps -e | grep sleep
reached end of main
 4470 pts/1    00:00:00 sleep
 4524 pts/1    00:00:00 sleep
 4578 pts/1    00:00:00 sleep
 4632 pts/1    00:00:00 sleep
```

This seems okay. What is the problem you have? `sleep` runs and the output prints out quickly. I guess I'm not sure what the problem is.

**Comment by lucklove** [comment]
@mdinger As the example shows:
`
$ rustc wait.rs && ./wait
reached end of main
# `wait` keeps running for 5 seconds
# `sleep 5` command ends, and then our `wait` program finishes
`
If it's correct, the wait(or test in your example) should keep running for a moment instead of quit quickly.

**Comment by mdinger** [comment]
I would think it would but I didn't grep for my rust binary. sleep always ran for about 10 seconds which is what I input and expected.
