### ISSUE TITLE
License issue: MIT and Apache license simultaneously

### ISSUE THREAD

**Issue by leksak** [rust-lang/rust-by-example#771]
As the headline implies, there is a licensing conflict with this repository, as both the [MIT-license](https://github.com/rust-lang/rust-by-example/blob/master/LICENSE-MIT) and the [Apache-license](https://github.com/rust-lang/rust-by-example/blob/master/LICENSE-APACHE) are included. 

Since the Apache license is more restrictive than the MIT-license, one can only conclude that the Apache license is the only one that applies. 

Regardless, one of them should be removed and the remaining license should arguably be renamed to "LICENSE".

**Comment by steveklabnik** [comment]
> Since the Apache license is more restrictive than the MIT-license, one can only conclude that the Apache license is the only one that applies. 

This is not true, you can accept the terms of either license.
