### ISSUE TITLE
Proposal: A new chapter on atomics and memory ordering

### ISSUE THREAD

**Issue by critiqjo** [rust-lang/rust-by-example#774]
With this example: https://gist.github.com/critiqjo/26e9f4ef4c22ab4eaae97870d6af272e

The example does not illustrate its purpose if run from play.rlo or play.i32 since both of them are probably giving the docker only a single core to run on. It is getting reordered very well in my Corei3-2330M.

**Comment by critiqjo** [comment]
I understand that this example is not beginner-friendly. But this would have helped me a lot some months back. If this is not the place for such an example, then where do you suggest such an example should go (don't tell me "nowhere!" :smile:) -- stackoverflow/docs?

**Comment by mdinger** [comment]
I'm not familiar with this topic so am not a good person for review. Maybe @steveklabnik will step up or point out someone. Regardless, the fact that no one commented here is more likely because they're busy than that they didn't like the suggestion.

**Comment by critiqjo** [comment]
If this is indeed deemed as "include-able" material, I will issue a PR with (extensive) docs ... soon.

**Comment by critiqjo** [comment]
Closing this... May be it better fits in [nomicon](https://doc.rust-lang.org/nomicon/atomics.html), but I won't bother myself with a PR, but feel free to use, copy, modify the example I provided without any obligations whatsoever...

Cheers!
