### ISSUE TITLE
Inline examples instead of separate files

### ISSUE THREAD

**Issue by lambda** [rust-lang/rust-by-example#776]
Something odd that I noticed about the Rust by Example book, as opposed to most other forms of Rust documentation, is that the examples are not inline in the Markdown, but stored in separate files.

This could raise the barrier to entry a little bit to people who want to submit quick fixes via that GitHub online editor interface, at that makes it quick and easy to propose an edit to a single file, but not to many at once. For instance, see my suggestion to add easy "Edit" links to the Rust Book to suggest edits: rust-lang/book#141; I was going to suggest the same for Rust by Example, but realized this issue would make that a little more complicated.

I even notice that a feature has been added to mdBook (azerupi/mdBook#29) to support this style of example, in anticipation of migrating Rust by Example from gitbook to mdBook.

I'm wondering if there's a good reason for keeping the examples out of line, other than making tooling slightly easier by not having to extract the examples to compile and test them. There are already a couple of tools to make that easy to do, like [rust-skeptic](https://github.com/brson/rust-skeptic) and [tango](https://github.com/pnkfelix/tango), so it would seem that it might be a better idea to use one of those and keep examples inline, to make editing the examples easier.

**Comment by steveklabnik** [comment]
Also, `mdbook` supports testing iniline examples, so while the feature would make it easier to port, we could convert it after.

**Comment by brson** [comment]
I'm fine with moving the examples inline.

**Comment by steveklabnik** [comment]
This is now true!
