### ISSUE TITLE
5 Casting: Swap around a bit

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust-by-example#780]
Nothing after the title page actually covers Casting, so I'd think that the first page should be `Types` or some such, and `Casting` should be a subheading.

**Comment by steveklabnik** [comment]
Agreed. I'm happy to mentor anyone who wants to fix this!

**Comment by maccoda** [comment]
@steveklabnik Just wanted to check did we need anything else to close this one off? :smile:

**Comment by steveklabnik** [comment]
We're good!
