### ISSUE TITLE
"Re-enabling box" doesn't work as it suggests.

### ISSUE THREAD

**Issue by scottschroeder** [rust-lang/rust-by-example#782]
The lesson titled [Re-enabling box](http://rustbyexample.com/error/reenabling_box.html) walks the reader through implementing the `error::Error` trait to allow custom error types to cast into `Box<error::Error>`.

We also have implemented `From<ParseIntError> for DoubleError`, and set our result type to `std::result::Result<T, Box<error::Error>>`.

From this we are led to believe that when the `try!` is performed on the integer parse,
the failure will result in a `DoubleError`, and when the function returns, the `DoubleError` becomes a `Box<error::Error>` through type erasure.

Whats actually happening, is that the `ParseIntError` already implements `error::Error`, and undergoes type erasure before ever becoming a `DoubleError`.
- Expected: `ParseIntError` -> `DoubleError` -> `error::Error`
- Actual: `ParseIntError` -> `error::Error`

This makes a significant amount of code in the example obsolete, because half of our enum never gets used.

There is a simple "fix" for this:

```
- type Result<T> = std::result::Result<T, Box<error::Error>>;
+ type Result<T> = std::result::Result<T, DoubleError>;
```

but that sort-of invalidates the lesson.

**Comment by scottschroeder** [comment]
My suggestion would be to point out that `ParseIntError` implements `error::Error`, and that we can simplify our code by only needing to implement the `EmptyVec` error.

I'd be happy to create a pull request with that fix, _if_ its the recommended way to clarify the lesson.

**Comment by mdinger** [comment]
This certainly sounds like a problem and your argument seems reasonable. I'm currently trying to reach out to someone currently to get some clarification on a couple things before attempting to render an opinion about how this should proceed.

**Comment by BurntSushi** [comment]
@scottschroeder I think your analysis is correct. I'm not sure I totally agree with your fix though. It kind of depends on what the example is trying to demonstrate. If you look at section 16.7 and compare it with 16.8, it's clear that 16.8 incrementally builds on top of 16.7. Namely, that implementing `Error` gives the *caller* more flexibility with respect to handling the error. This doesn't necessarily mean that the *implementor* of the error wants to switch everything over to `Box<Error>`.

This is kind of a subtle point though, and would (I think) require the example to more explicitly differentiate between the goals that the library author is trying to achieve and the goals that the application author is trying to achieve. Optimizing away the error enum makes the *current* wording make a little more sense, but I feel like that kind of misses the broader point: you should implement `From` and `Error`, and you should return explicit errors whenever possible, but that implementing `Error` gives the caller some convenient flexibility.

**Comment by scottschroeder** [comment]
I agree, there is a disconnect between how a library author would raise the error, and how a caller would handle it.

My concern is that demonstrating that point effectively would require a much more complex example, and might become too much to digest for a reader.

If we did want to showcase the difference between a library and its caller, perhaps doing something like:
```
mod double {
    // DoubleError and associated code goes here.
}
// Calling code goes here, and uses Box<error::Error>
```

The problem is, that we would still need a another error to demonstrate type erasure, so that the new error, and `DoubleError` both end up as `Box<error::Error>`

_Caveat: I'm still a rust novice, perhaps a more experienced rustacean could offer an elegant solution that I can't deduce._

**Comment by mdinger** [comment]
I was discussing this with @BurntSushi and I thought a few things could be done and he seemed to agree:

* The example could be subtly reworded to emphasize that, while the implementations of the underlying error branches might not get hit, it is good form to fill them out. Therefore, the recommended example will still be basically the same
* The main goal is for `box` to work properly and filling this out will still fulfill that goal
* A future followup example could expound on the caller perspective further without much change being required

@scottschroeder Thanks for bringing this up!

**Comment by steveklabnik** [comment]
That plan sounds great, @mdinger ; let's do it.

**Comment by marioidival** [comment]
The PR #797 fixes this issue.
