### ISSUE TITLE
"The type of a variable can't be changed" - but could maybe mention shadowing?

### ISSUE THREAD

**Issue by icanrealizeum** [rust-lang/rust-by-example#783]
This `mutable = true;`
here: 
http://rustbyexample.com/primitives.html

Makes me wish that `let mutable = true;` was mentioned as a way to still be able to change the type of the variable by shadowing the old one. I think it would be interesting to have in that context. 

Thanks for your consideration.

**Comment by steveklabnik** [comment]
Yes, shadowing is important, and would be a great addition; possibly adding its own section!

I'm happy to mentor anyone who wants to fix this.

**Comment by zsck** [comment]
Given that there appears to now be a whole section that (briefly) discusses binding [scope and shadowing](https://rustbyexample.com/variable_bindings/scope.html), would it be more appropriate to simply add a link to that section?  I personally feel that having a separate section for these things is perfectly reasonable. The concepts deserve at least a little bit of dedicated attention, and I'm not sure we necessarily need to tie the explanation of primitives to the technique of shadowing. In light of that, maybe this issue can be closed?

**Comment by steveklabnik** [comment]
Yeah, that seems good to me.

**Comment by jansol** [comment]
Link and example are in place, please close this.
