### ISSUE TITLE
rust playground run button position

### ISSUE THREAD

**Issue by morriswinkler** [rust-lang/rust-by-example#784]
I figured that the position of the RUN and RESET button on the embedded rust editor could be placed below the editor, on long code examples  you will need to scroll back up to run the example. 

See: [print_display.html](http://rustbyexample.com/hello/print/print_display.html)

**Comment by mdinger** [comment]
The current long term goal is to have [this](http://azerupi.github.io/mdBook/format/rust.html) style. When we'll migrate to that is unclear. Besides that, this idea probably is okay but I don't know who if anyone may implement it.

**Comment by steveklabnik** [comment]
Yes, we have moved to mdbook, which changes the style a bit.

Anything updating the style would have to go through mdBook, so this ticket isn't valid anymore. Closing!
