### ISSUE TITLE
Adding or removing semicolon from macros

### ISSUE THREAD

**Issue by FedericoPonzi** [rust-lang/rust-by-example#785]
Hi,
I've started studying from rust through this site, and I've noticed that in some example code the macros ends with semicolon, and others don't (for example: [tuples](https://github.com/rust-lang/rust-by-example/blob/master/examples/primitives/tuples/tuples.rs#L47)).
I think that they should be added everywhere missing or removed from macros.

**Comment by steveklabnik** [comment]
In general, they should be added, yes!
