### ISSUE TITLE
Website Issue: unable to run code examples

### ISSUE THREAD

**Issue by mccolljr** [rust-lang/rust-by-example#793]
Any attempt to run a code example results in the following error messages being logged to the browser console in the order shown:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error) | https://play.rust-lang.org/evaluate.json
```

```
XMLHttpRequest cannot load https://play.rust-lang.org/evaluate.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rustbyexample.com' is therefore not allowed access. The response had HTTP status code 500. | hello.html:1
```

```
Uncaught TypeError: Cannot read property 'length' of null | editor.js:200
```

I didn't see an existing issue regarding this. I've been able to duplicate the behavior in the latest versions of Chrome and Safari on OSX El Capitan (10.11.3)

I'm able to successfully get the playground to run code when I submit a request from the console:
```js
$.post("https://play.rust-lang.org/evaluate.json", JSON.stringify({"code":"fn main() {\n// The statements here will be executed when the compiled binary is called\n// Print text to the console\nprintln!(\"Hello World!\");\n}","version":"stable","backtrace":"0"})).then(function(r){ console.log(r); })
```

but the same request fails when I attempt to send the request without first using JSON.stringify on the payload. This fails:
```js
$.post("https://play.rust-lang.org/evaluate.json", {"code":"fn main() {\n// The statements here will be executed when the compiled binary is called\n// Print text to the console\nprintln!(\"Hello World!\");\n}","version":"stable","backtrace":"0"}).then(function(r){ console.log(r); })
```

Has anyone else experienced this?

**Comment by mdinger** [comment]
@jonas-schievink You know what is causing this?

**Comment by jonas-schievink** [comment]
Not really, but maybe this is related to rust-lang/rust-playpen#245 (in case you don't set `backtrace` at all, it might also return a 500 error). Would explain why it works with `"backtrace"="0"`. Since when does this happen?

**Comment by TimNN** [comment]
Since the the backtrace functionality was added back to playpen in rust-lang/rust-playpen#243 two days ago.

Basically, if `"backtrace"` has not been set it defaults to `"auto"`, which means "enable backtraces in debug mode and disable them in release mode".

However as you can see from rust-lang/rust-playpen#245, requesting a backtrace currently fails on the playpen servers.

**Comment by TimNN** [comment]
A fix has been deployed to http://play.rust-lang.org and the few examples I tried from http://rustbyexample.com/ also seem to be working.

**Comment by mdinger** [comment]
@TimNN Thanks!
