### ISSUE TITLE
Lifetime section should include an example where you need to finely specify them.

### ISSUE THREAD

**Issue by autra** [rust-lang/rust-by-example#802]
After going through the "lifetime" section, I failed to understand the point of lifetimes. I didn't see where I needed Foo<'a> or Foo<'a, 'b>. I tried different program I thought wouldn't compile, but they did! So at the end, I was like "ok, I know the syntax of lifetimes parameters, but when do I need to bother about these? Why can't the compiler put some 'a everywhere?". I mean, I _felt_ there was something going on, but couldn't _see_ it yet.

After going through [this section of the rust doc](https://doc.rust-lang.org/0.12.0/guide-lifetimes.html#parameter-lifetimes), things are a lot clearer to me. Basically, this example shows where you need to specify precisely the lifetime of each parameters

``` rust
// This does not compile yet, because 'r in inferred to be B lifetime. 
// it would if we specified different lifetimes for a and b on one hand, 
// and shape on the other hand.
fn select<'r, T>(shape: &'r Shape, threshold: f64,
                 a: &'r T, b: &'r T) -> &'r T {
    if compute_area(shape) > threshold {a} else {b}
}
                                                     // -+ r
fn select_based_on_unit_circle<'r, T>(               //  |-+ B
    threshold: f64, a: &'r T, b: &'r T) -> &'r T {   //  | |
                                                     //  | |
    let shape = Circle(Point {x: 0., y: 0.}, 1.);    //  | |
    select(&shape, threshold, a, b)                  //  | |
}                                                    //  |-+
                                                     // -+

```

 it really helped me to click things together.

To explain a bit more toroughly, the `coercion` section is not far from this, but failed to help me. 

``` rust
// Here, Rust infers a lifetime that is as short as possible.
// The two references are then coerced to that lifetime.
fn multiply<'a>(first: &'a i32, second: &'a i32) -> i32 {
    first * second
}

// `<'a: 'b, 'b>` reads as lifetime `'a` is at least as long as `'b`.
// Here, we take in an `&'a i32` and return a `&'b i32` as a result of coercion.
fn choose_first<'a: 'b, 'b>(first: &'a i32, _: &'b i32) -> &'b i32 {
    first
}
```

indeed `choose_first` could be written with only one lifetime parameter, just like `multiply`, and the coercion would work just fine. So I didn't see when I needed 'a *_and_ 'b, so I didn't see why I should specify 'a at all (why couldn't the compiler add them for me in all cases?).

I think this section would really benefit from an example like the one above WDYT? If you agree with this, I can make a PR. If so, what would be the best place for this example? Maybe we can add a "The problem" subsection like in "Associated items"? I do think we can find something better than shape and threshold though.

**Comment by mdinger** [comment]
This sounds okay but note that critical responses may take some time. I've been busy and other development guys often are as well. Also note that https://github.com/rust-lang/rust-by-example/pull/655 was filed and closed but I don't actually remember how much the topic was addressed. It definitely was worthy of trying to fix. In particular, see https://github.com/rust-lang/rust-by-example/pull/655#issuecomment-153303105.

With lifetimes, one historical problem has been even explaining what the syntax means to people. It has seemed problematic enough that syntax meaning may be entirely separated from usage explanation. That is to say, even if this example doesn't explain usage well, if syntax meaning is clear, then at least one part is okay.

Also, `'a: 'b` documentation is generally non-existent anywhere in any docs so removing examples about it isn't great. Making them better would be ideal.

**Comment by autra** [comment]
> critical responses may take some time

No problem :-) I'm not in a hurry.

> if syntax meaning is clear, then at we're doing one thing correct.

+1, and it was clear for me at least.

> Also, 'a: 'b documentation is generally non-existent anywhere in any docs so removing examples about it isn't great.

Yep, I was thinking about adding things more than removing. Actually, I have a first try ready. I just added a "test case" page at the end of this section. I'll attach a PR in a minute.

About #655... Well. TBH I haven't read everything in details (except the comment you linked), but I generally agree with you that this section should not try to explain *too* precisely what a lifetime is (until we find a very good and compact way of expressing it without circular references I guess). It's a "by example" book after all! I have tried to keep the PR in this spirit, let me know if I succeeded.

On overall, I feel that lifetimes are not that complicated, at least for 90% of the cases. Reading the example in my first comment was enough for me to grasp the concept (although I haven't tested thoroughly my understanding).

**Comment by da-x** [comment]
Would this be sufficient in the meanwhile? https://github.com/da-x/rust-by-example/commit/a3237a4ffa131e4389cff3479a0d199fae447b16
Explanations about the necessity of specifying lifetimes can start small.

**Comment by mdinger** [comment]
The concept is OK but avoiding writing out error messages is preferable
because they tend to change and become outdated. That is one reason 'try
this' sections appear.

**Comment by autra** [comment]
> Would this be sufficient in the meanwhile? da-x@a3237a4
Explanations about the necessity of specifying lifetimes can start small.

Imo not really, because one would discover compiler error messages soon enough. It's not necessary to just copy it in this book. We must make it understandable. Actually, I think the problem should be taken the other way around: we should aim at making the concept clear, then compiler messages would become clear too.

That being said, #805 might not be the best way to achieve this. IDK.

**Comment by da-x** [comment]
I understand. Then how about having the compiler error be automatically generated in the build process of the rust-by-example book, along with a label that says 'relevant to version x.y.z..'? Then it won't be a copy, will always be up-to-date and well in the spirit of learning by example.

For me this error message has had a huge explanatory value. That is, after I tried learning about life-times as much as possible.

**Comment by mdinger** [comment]
I don't think it is likely someone will write a script to parse the compiler output and merge it into examples at certain points for something as simple as this, especially if the alternative is the leave a bad example in the code which will throw an error generated by the compiler directly (and will always be up to date) when it is run.

There are simple, reliable solutions here:

* leave a `Try this` section
* leave bad code in the example as something instructive

Both have pluses and negatives for a reader. Both probably require careful attention which readers don't always use.

**Comment by steveklabnik** [comment]
Given that #805 tried to solve this, but wasn't really great, I'm going to close this. If anyone has any specific, concrete ideas for improvements, please open new issues! Thanks.
