### ISSUE TITLE
Suggestion to use `GitBook API Theme` and 2 column layout

### ISSUE THREAD

**Issue by dumindu** [rust-lang/rust-by-example#818]
Thanks for the great work. Herewith I would like to suggest to use 2 column layout with more detailed explanations and much cleaner examples by using [GitBook API Theme](https://github.com/GitbookIO/theme-api)

ex.
![GitBook API Theme](https://github.com/GitbookIO/theme-api/raw/master/img/theme-api.png)

ex. 
How we can use Inline explanations [Hello Backbone](http://arturadib.com/hello-backbonejs/docs/3.html)

Thanks.

**Comment by mdinger** [comment]
See https://github.com/rust-lang/rust-by-example/issues/248. This might be WONTFIX.

**Comment by steveklabnik** [comment]
Yes, if anything, we'd want to migrate to mdbook rather than keeping with
gitbook, I'd think.

**Comment by steveklabnik** [comment]
Yes, we have migrated to mdBook, so any style things have to go through there. Thanks!
