### ISSUE TITLE
suggest upload rust-playpen plugin to npm

### ISSUE THREAD

**Issue by ParkHanbum** [rust-lang/rust-by-example#819]
Hi~ I'm translating rust-by-example to korean. 
I want upload that to gitbook.com but there is not support rust-playpen.
therefore, I was uploading "rust-playpen plugin" to npm temporarily.

can you upload that to npm?

**Comment by mdinger** [comment]
Gitbook integration is on the way out. In the future, it is expected that rbe will migrate to [mdBook](https://github.com/azerupi/mdBook/). Other [translations](https://github.com/rust-lang/rust-by-example#translations-to-other-languages) currently link to wherever the website is hosted. If you aren't selfhosting, github provides website hosting which is what many people use.

As it is, I don't think the playpen plugin was ever meant to be permanent nor used by others. Can't you just use github hosting and link on the readme like the others do?

**Comment by steveklabnik** [comment]
Yes, we don't intend to stay on gitbook, and so I'm not planning on creating this as a real plugin. I would suggest doing what the other translations do for now. Thanks!
