### ISSUE TITLE
calibre is required for making the project on Ubuntu 16.04

### ISSUE THREAD

**Issue by realcr** [rust-lang/rust-by-example#824]
I am using Ubuntu 16.04.
When running the commands:
```
make all
make html pdf epub
```
I get a message that ebook-convert command line tool is missing. I found that in order to obtain it the following command should be invoked:

```
sudo apt install calibre
```
Maybe this should be added to the required packages for debian related distros on the main readme file.

**Comment by steveklabnik** [comment]
I'd happily take a PR for this, sure!

**Comment by russmack** [comment]
Closed?
