### ISSUE TITLE
Potential improvement for http://rustbyexample.com/hello/print.html example

### ISSUE THREAD

**Issue by moreaki** [rust-lang/rust-by-example#829]
The current example reads:

`println!("{} of {:b} people know binary, the other half don't", 1, 2);`

Would it be more correct to state:

`println!("{} of {:b} people know binary, the other half doesn't", 1, 2);`

Since we probably assume a binary world, half of the set is singular, which probably also means we need to adjust the wording.

**Comment by steveklabnik** [comment]
Sounds good to me. I'd happily take a PR for this.

**Comment by ubsan** [comment]
I'd also change "of" to "in".
