### ISSUE TITLE
filesystem example has issues on Windows. May be an issue with rustc.

### ISSUE THREAD

**Issue by RobBlob** [rust-lang/rust-by-example#830]
1. The following causes a compilation error:
 `use std::os::unix;`

I was able to avoid this by preceding it with `#[cfg(target_family="unix")]`

2. The following fragment fails to compile:

```
if cfg!(target_family = "unix") {
        unix::fs::symlink("../b.txt", "a/c/b.txt").unwrap_or_else(|why| {
        println!("! {:?}", why.kind());
        });
    }
```

fails attempting to compile the contents of the block. I would expect it to skip the block entirely.

Using rustc 1.14.0 on Windows 10, and cargo 0.15.0-nightly.

**Comment by steveklabnik** [comment]
None of this uses `unix` anymore; closing!
