### ISSUE TITLE
cfg! macro doesn't do conditional compilation

### ISSUE THREAD

**Issue by est31** [rust-lang/rust-by-example#831]
I'm referring to this section of the docs: http://rustbyexample.com/attribute/cfg.html

It says:

```
Conditional compilation is possible through two different operators:

   * the cfg attribute: #[cfg(...)] in attribute position
   * the cfg! macro: cfg!(...) in boolean expressions
```

But the `cfg!` macro doesn't do conditional compilation. Instead, it expands to a boolean expression at compile time. This is a slight difference, which has caused confusion, see this issue: https://github.com/rust-lang/rust/issues/38928

**Comment by RobBlob** [comment]
Thanks, I already filed an issue there (#38928).

**Comment by RobBlob** [comment]
Oops, should have been https://github.com/rust-lang/rust-by-example/issues/830

**Comment by est31** [comment]
Oh, right
