### ISSUE TITLE
Pgup/pgdown does not work

### ISSUE THREAD

**Issue by hacxman** [rust-lang/rust-by-example#836]
Pgup and pgdown does not work. Please don't disable it.

**Comment by steveklabnik** [comment]
What platform are you on? It works here.

**Comment by hacxman** [comment]
Linux, webkitgtk-2.4.11. It works in webkit from PyQt4 but syntax highlighting doesnt. Any idea whats wrong?

**Comment by steveklabnik** [comment]
Not sure. I tested on Firefox for Windows.

**Comment by Gordon-F** [comment]
@hacxman looks like browser issue. Or maybe gitbook issue.

Pgup/pgdown works well on latest Chrome/Firefox (Linux and Windows)

Maybe close issue ?

**Comment by steveklabnik** [comment]
We've ported it to mdbook, and page up/page down seems to work now. If it doesn't still, please file a bug upstream. Thank you!
