### ISSUE TITLE
Error: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by MuradGazibekov** [rust-lang/rust-by-example#838]
`gazibekov@MacBook-Air-Murad ~/D/rust-by-example-master> make html pdf epub`
`node_modules/.bin/gitbook build stage`
`module.js:472`
`    throw err;`
  `  ^`

`Error: Cannot find module 'internal/fs'`
`    at Function.Module._resolveFilename (module.js:470:15)`
  `  at Function.Module._load (module.js:418:25)`
   ` at Module.require (module.js:498:17)`
   ` at require (internal/module.js:20:19)`
   ` at evalmachine.<anonymous>:18:20`
   ` at Object.<anonymous> (/Users/gazibekov/Downloads/rust-by-example-master/node_modules/graceful-fs/fs.js:11:8)`
  `  at Module._compile (module.js:571:32)`
    `at Object.Module._extensions..js (module.js:580:10)`
    `at Module.load (module.js:488:32)`
    `at tryModuleLoad (module.js:447:12)`
`make: *** [html] Error 1`

**Comment by mdinger** [comment]
IDK, did you run `make all`? That is something like this:

```text
git clone https://github.com/rust-lang/rust-by-example.git rbe && cd rbe && make all && make html pdf epub
```

**Comment by ashneo76** [comment]
I did run `make all`, but I still get the same error. I am on node v7.4.0

**Comment by timmyjose** [comment]
Same issue here. Node version: v7.4.0, NPM version: 4.0.5. Found related issue with Node/NPM here: https://github.com/npm/npm/issues/14232

@ashneo76 Downgrading to Node v6.9.4 worked for me.

**Comment by aliokan** [comment]
The same on Sierra 10.12.3 (16D32) with `npm -v 4.1.2` and `node -v v7.5.0`. 
Fresh install on new machine. 

```
stderr: module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users/user/Documents/GIT-REPOS/project/node_modules/fontchaos-fetcher/node_modules/unzip/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by steveklabnik** [comment]
We've ported to mdbook, so the old build system and node dependency are gone now. Closing!

**Comment by hustcer** [comment]
I have just made a epub version of `Rust by Example`, if anyone need it just download from here: https://github.com/hustcer/open-books/blob/main/Rust%20By%20Examples.epub
