### ISSUE TITLE
Point2 vs Point2D

### ISSUE THREAD

**Issue by J3RN** [rust-lang/rust-by-example#841]
Reading through Hello World -> Display, I was a little confused as to why the struct is named `Point2`, since there is no `Point` or `Point1`. However, at the end of that page, it says this:

```rust
 // println!("What does Point2D look like in binary: {:b}?", point);
```
This name is implying it's a 2D point, which makes the name make sense. Would it be acceptable if I changed to struct's name in this book from `Point2` to `Point2D` to help others avoid the confusion?

**Comment by ubsan** [comment]
I think this is a typo :3
