### ISSUE TITLE
primitives/array uses the term "word" without defining it

### ISSUE THREAD

**Issue by Poddster** [rust-lang/rust-by-example#843]
Section 2.3, Arrays and Slices, uses the term word:

>Slices are similar to arrays, but their size is not known at compile time. Instead, a slice is a **two-word object**, the **first word** is a pointer to the data, and the **second word** is the length of the slice. Slices can be used to borrow a section of an array, and have the type signature &[T].

What is a `word` in terms of Rust?

I know what a word is in terms of CPU architecture. Is Rust using the same notion? i.e. will the `length word` have a different bitsize on a 16bit processor vs an x86-64 one? Does the length always have the same bitsize as the pointer? (i.e. is it a `usize` ?)

As it's not explained on the page I'm unsure. Is the term "word" actually relevant here or was it just incidental usage? Could another term, e.g. "value" or "primitive" or something else, be used instead?

**Comment by russmack** [comment]
Close #843 please, thanks!
Merged here:
https://github.com/rust-lang/rust-by-example/commit/0173da6195b1cf0b34ba9c86a4e88af254f52c5e

**Comment by Poddster** [comment]
Thanks @russmack 👍
