### ISSUE TITLE
cast/alias: Confusing wording -> typing 

### ISSUE THREAD

**Issue by jeiting** [rust-lang/rust-by-example#854]
https://rustbyexample.com/cast/alias.html

"The main use of aliases is to reduce typing; for example the IoResult<T> type is an alias for the Result<T, IoError> type."

Is "typing" here referring to the programming concept or the physical act of typing on a keyboard?

If it refers to the physical act, perhaps a better word would be "boilerplate" or "repetition". Glad to submit a PR if my understanding is correct here.

**Comment by steveklabnik** [comment]
The latter. PR very welcome!

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust-by-example/pull/855 should have closed this!
