### ISSUE TITLE
std/box: warning: field is never used: `x`

### ISSUE THREAD

**Issue by maniankara** [rust-lang/rust-by-example#857]
When running `17.1 Box, stack, heap` example, we get this warning:
```
warning: field is never used: `x`, #[warn(dead_code)] on by default
...
warning: field is never used: `y`, #[warn(dead_code)] on by default

```
Ofc, the fields are never used.
Then the warning must be suppressed as it might be bit misleading

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust-by-example/pull/858 was merged so closing!
