### ISSUE TITLE
Fix result of Display implementation -> fmt::Result to ->fmt::Result<(), Error>

### ISSUE THREAD

**Issue by jcbritobr** [rust-lang/rust-by-example#860]
The code about failed with following message:

```
use std::fmt; // Import `fmt`

// A structure holding two numbers. `Debug` will be derived so the results can
// be contrasted with `Display`.
#[derive(Debug)]
struct MinMax(i64, i64);

// Implement `Display` for `MinMax`.
impl fmt::Display for MinMax {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        // Use `self.number` to refer to each positional data point.
        write!(f, "({}, {})", self.0, self.1)
    }
}
```

> wrong number of type arguments: expected 2, found 0

because the result has 2 arguments

**Comment by mdinger** [comment]
This [example](http://rustbyexample.com/hello/print/print_display.html) works for me on their page. I'm not sure what you're referring to.

**Comment by jcbritobr** [comment]
For me it dosnt work. I got  the error message  above.   Im using 1.16 version .

**Comment by mdinger** [comment]
So the page doesn't work or your home computer doesn't work with that example?

**Comment by mdinger** [comment]
Your code works says the [playpen](https://is.gd/HOSCCd). You aren't giving enough details for us to give you any useful help.

**Comment by jcbritobr** [comment]
@mdinger, the code above, on this page: [http://rustbyexample.com/hello/print/print_display.html](http://rustbyexample.com/hello/print/print_display.html) dont work on win 10. The return type **Result**
 is wrong. The function **fmt(&self, f: &mut fmt::Formatter)** returns 2 arguments. Result<(), Error>. 

The error messa that i received from compiler was: wrong number of type arguments: expected 2, found 0.

I tested now in linux ubuntu 64 bit and the code worked. There is a problem in windows 10 64 bit version.

**Comment by jcbritobr** [comment]
The entire error message:

> error[E0243]: wrong number of type arguments: expected 2, found 0
>   --> main.rs:10:42
>    |
> 10 |      fn fmt(&self, f: &mut Formatter) -> Result {
>    |                                          ^^^^^^ expected 2 type arguments
> 
> error: aborting due to previous error

**Comment by steveklabnik** [comment]
@jcbritobr I am on Windows 10, and clicking "run" works for me. Given that the website calls out to the same playpen regardless of OS means that I'm not sure what you're doing.

**Comment by jcbritobr** [comment]
I found the error. It was the Result import missing


```
use std::fmt::{Display, Formatter, Error};

#[derive(Copy, Clone, Debug)]
struct IntPoint {
    x: i32,
    y: i32,
}

impl Display for IntPoint {
     fn fmt(&self, f: &mut Formatter) -> Result {
         write!(f, "< x: {} y: {} >", self.x, self.y)
     }
}

fn main() {
    let pointa = IntPoint{x:100, y:200};
    println!("Testing structure intpoint {}", pointa );
}
```

must use use std::fmt::{**Result**, Display, Formatter, Error};

**Comment by jcbritobr** [comment]
The error message is too obscure and dont show that strucure was missing: rror[E0243]: wrong number of type arguments: expected 2, found 0.

I'will close now this issue.
Thank you all.
