### ISSUE TITLE
Stop using deprecated "-Z" rustc-flag to reduce Travis Spam

### ISSUE THREAD

**Issue by juleskers** [rust-lang/rust-by-example#862]
I just checked the [Travis logs](https://travis-ci.org/rust-lang/rust-by-example/jobs/218880436) because my PR didn't build, and was greeted, among others, with 266 copies of
> warning: the option `Z` is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details

The warning references RustC issue [#31847](https://github.com/rust-lang/rust/issues/31847), which says we shouldn't pass unstable debug flags to stable compilers.

The rust-by-example [makefile](https://github.com/rust-lang/rust-by-example/blob/master/Makefile#L5) specifies `-Z no-trans`, I presume for speed reasons?
Is this something that should maybe be reconsidered?

**Comment by steveklabnik** [comment]
> 

The rust-by-example makefile specifies -Z no-trans, I presume for speed reasons?
Is this something that should maybe be reconsidered?

yes, it should be `cargo check` now instead.

In genearl all of the RBE build stuff is very out of date :/

**Comment by titanous** [comment]
I think this was fixed by #872.

**Comment by juleskers** [comment]
Jup, it was! Thanks for paying attention!
