### ISSUE TITLE
Display an error when AJAX request to play.rust-lang.org fails

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust-by-example#873]
When I go to any rustbyexample.com page (ex: https://rustbyexample.com/hello.html but I got the same behavior on other pages) in Firefox and click the run button, the "Running..." text appears but no output ever shows up.

In the network tab in developer tools, I don't see any requests being made.

In the console tab, on page load I see a warning about the mathjax CDN, a ReferenceError that mathjax is not defined.

When I click the Run button, I see this error in the console tab:

```
TypeError: message is null  editor.js:201:1
	handleResult https://rustbyexample.com/gitbook/plugins/gitbook-plugin-rust-playpen/editor.js:201:1
	runProgram/req.onerror https://rustbyexample.com/gitbook/plugins/gitbook-plugin-rust-playpen/editor.js:189:5
```

Chrome works fine. Let me know if there's any more info that would be helpful ❤️

**Comment by steveklabnik** [comment]
What platform? Firefox on Windows here works.

**Comment by mdinger** [comment]
Is this still not working? It works for me in firefox win 10. I get the same mathjax error and the page still works correctly.

**Comment by carols10cents** [comment]
Yup, just reproduced this in firefox 53.0.3 on macos.

<img width="1275" alt="screen shot 2017-06-09 at 11 06 26 am" src="https://user-images.githubusercontent.com/193874/26981647-c9a7e93e-4d03-11e7-8728-e980e3d6debd.png">

**Comment by mdinger** [comment]
I get those same mathjax errors. I don't get that type error which is where I would suspect the problem lies. I would assume you're having problems with [this](https://github.com/rust-lang/rust-by-example/blob/master/node_modules/gitbook-plugin-rust-playpen/book/editor.js#L160) and the status code is getting set to null because of some problem. Did you test it with a new profile?

**Comment by carols10cents** [comment]
Argh. It was me. I'm using EFF's Privacy Badger extension, and it was blocking the requests to play.rust-lang.org. Sorry!!!!!!

**Comment by carols10cents** [comment]
ACTUALLY I'm reopening this. It'd be nicer if we could catch this and display an error in page when the request fails for any reason (the user might now be offline, for example).

**Comment by steveklabnik** [comment]
We've ported this to mdBook, so everything here has totally changed. I believe that this is fixed, but am not 100% sure; if you're still seeing this, please re-open over there!
