### ISSUE TITLE
std/vec: More examples related to iterating over vectors

### ISSUE THREAD

**Issue by mrshu** [rust-lang/rust-by-example#874]
While reading through the page on [std::vec::Vec](https://rustbyexample.com/std/vec.html), I kind of missed a section on how can one iterate over them. While I understand that there is a separate page on [iterators and all sorts of their uses](https://rustbyexample.com/trait/iter.html) which would cover this to some extend, I believe it would be better to have a few examples on iteration directly in the article on `std::vec::Vec`.

Despite everything written in [CONTRIBUTING.md](https://github.com/rust-lang/rust-by-example/blob/master/CONTRIBUTING.md), I went ahead and put together a few examples in here: https://github.com/mrshu/rust-by-example/blob/9bceceb5dc4fcebd5571a1b2d5784bd441584844/examples/std/vec/vec.rs#L30-L49

If there was any interest in adding them in (with any changes that may be requested), I'd happily send a PR.

Thanks!

**Comment by steveklabnik** [comment]
@mrshu sorry for the long response here! Those example look good to me, please send in a PR!

**Comment by mrshu** [comment]
Thanks @steveklabnik -- no worries at all!

Here is the PR: #906
