### ISSUE TITLE
add the PDFs as releases on GitHub

### ISSUE THREAD

**Issue by simbo1905** [rust-lang/rust-by-example#879]
I would like to read this on a plane. Trying to generate the PDF on my macbook didn't work out. What would be really helpful would be to release a PDF under the releases tab on GitHub. That way folks on a plane can get their rust by example on. Thanks!

**Comment by steveklabnik** [comment]
Now that we've ported to mdbook, this is a duplicate of https://github.com/azerupi/mdBook/issues/88
