### ISSUE TITLE
1.2.3: Not clear on what to do?

### ISSUE THREAD

**Issue by MGageMorgan** [rust-lang/rust-by-example#881]
I'm not clear on the purpose of 1.2.3, but I got as far as getting the ```Display``` trait implemented and RGB mostly implemented. Thing is, past this it tries to get you to take the RGB values, spit them out as 6-digit hexes (like CSS) and I have no clue how to make them all have 6 digits. How do I make each converted value have at least two characters, and more importantly, what is the purpose of this chapter? What is new that wasn't explained in the others, explanation-wise? I could have sworn format! and write! had already been introduced.

The code below:

```rust
use std::fmt::{self, Formatter, Display};

struct City {
    name: &'static str,
    // Latitude
    lat: f32,
    // Longitude
    lon: f32,
}

impl Display for City {
    // `f` is a buffer, this method must write the formatted string into it
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        let lat_c = if self.lat >= 0.0 { 'N' } else { 'S' };
        let lon_c = if self.lon >= 0.0 { 'E' } else { 'W' };

        // `write!` is like `format!`, but it will write the formatted string
        // into a buffer (the first argument)
        write!(f, "{}: {:.3}°{} {:.3}°{}",
               self.name, self.lat.abs(), lat_c, self.lon.abs(), lon_c)
    }
}

#[derive(Debug)]
struct Color {
    red: u8,
    green: u8,
    blue: u8,
}

impl Display for Color {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        let r = format!("{:X}", self.red);
        let g = format!("{:X}", self.green);
        let b = format!("{:X}", self.blue);

        let gf = format!("{:02}", g);

        write!(f, "RGB ({}, {}, {}) 0x{}{}{}", self.red, self.green, self.blue, r, g, b)
    }
}


fn main() {
    for city in [
        City { name: "Dublin", lat: 53.347778, lon: -6.259722 },
        City { name: "Oslo", lat: 59.95, lon: 10.75 },
        City { name: "Vancouver", lat: 49.25, lon: -123.1 },
    ].iter() {
        println!("{}", *city);
    }
    for color in [
        Color { red: 128, green: 255, blue: 90 },
        Color { red: 0, green: 3, blue: 254 },
        Color { red: 0, green: 0, blue: 0 },
    ].iter() {
        // Switch this to use {} once you've added an implementation
        // for fmt::Display
        println!("{}", *color)
    }
}
```
will print out:

```
RGB (128, 255, 90) 0x80FF5A
RGB (0, 3, 254) 0x03FE
RGB (0, 0, 0) 0x000
```

but the "Activity" box below says it needs to print out:

```
RGB (128, 255, 90) 0x80FF5A
RGB (0, 3, 254) 0x0003FE
RGB (0, 0, 0) 0x000000
```

Please help, because I've checked out the two hints and don't get how they are relevant past ```{:X}``` and I don't have a clue what to do with ```{:02}```. I'm banking on the fact this is the right place for this.

**Comment by mdinger** [comment]
It's a bit complicated. The intent is to show that other formatting options exist other than what was shown before with debug and display. It might be unclear but that is the basic point. The other chapters were also developed independently from this chapter and so the flow and overlap might be a bit odd. It was kept because there wasn't anything deemed wrong with it and more examples aren't necessarily bad.

```rust
format!("{:02X}", foo)
```

You're looking for something like [this](https://play.rust-lang.org/?gist=e7f8eb845225416827a4ba4552388b1e&version=stable) (also included briefly above). Basic idea is that you use [this](https://doc.rust-lang.org/std/fmt/#syntax) to understand the basic structure of the string. If you can give it the correct format spec, it should work. You need to know how you want it formatted which is defined [here](https://doc.rust-lang.org/std/fmt/#formatting-traits). The zero is that it is zero padded. The number is how many digits. If you have some idea of what you're looking for, you can kinda figure it out from looking at that syntax but it isn't necessarily obvious.

**Comment by mdinger** [comment]
If you want quick answers to questions, your best bet is hop on [IRC](https://www.rust-lang.org/en-US/community.html) (see getting started). People are very friendly and usually answer your question within 5 minutes.

**Comment by MGageMorgan** [comment]
Okay, thanks! Will check out the links and attempt to solve it. Also I will keep the IRC in mind and redirect future questions there. 




Cheers!


M. Gage Morgan


----


Christoffen OSWorks LLC co-founder, CEO, and lead architect. 




/**


* Just note that my opinion will 


* NEVER reflect my company, which I 


* hope to keep neutral in terms of 


* public relations with other entities.


**/







On Mon, Jul 17, 2017 at 10:59 PM -0400, "mdinger" <notifications@github.com> wrote:












If you want quick answers to questions, your best bet is hop on IRC (see getting started). People are very friendly and usually answer your question within 5 minutes.

**Comment by Williamonia** [comment]
This should do the job
`write!(f, "RGB ({}, {}, {}) 0x{:0>2}{:0>2}{:0>2}", self.red, self.green, self.blue, r, g, b)`

**Comment by haomingw** [comment]
`write!(f, "RGB ({}, {}, {}) 0x{0:02X}{1:02X}{2:02X}", self.red, self.green, self.blue)`
should do the job

**Comment by aydafield22** [comment]
hi all, Can any body help me explain why `format!("{:0>2}", arg)` instead of `format!("{:0>3}", arg)`? 
thank you.

**Comment by Wirpple** [comment]
`impl Display for Color {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        write!(f, "RGB{:?} 0x{:02X}{:02X}{:02X}",
               (self.red, self.green, self.blue), 
               self.red, self.green, self.blue)
    }
}
`

**Comment by Wirpple** [comment]
` write!(f, "RGB{:?} 0x{:02X}{:02X}{:02X}",
               (self.red, self.green, self.blue), 
               self.red, self.green, self.blue)`

**Comment by xahodo** [comment]
Once I saw this I had this as a solution:
```
        let r = self.red as u32;
        let g = self.green as u32;
        let b = self.blue as u32;
        let rgb: u32 = (r << 16)+(g << 8)+b;
        write!(f, "RGB: ({}, {}, {}) {:06X}",
               r, g, b, rgb)
```
Perhaps it's a bit convoluted, but it works. I could have simmered this down a _lot_, but at a cost of readability.
