### ISSUE TITLE
error in https://rustbyexample.com/std/vec.html

### ISSUE THREAD

**Issue by oskarz1234** [rust-lang/rust-by-example#885]
error is like so:
_Compiling playground v0.0.1 (file:///playground)
error[E0596]: cannot borrow immutable local variable `collected_iterator` as mutable
  --> src/main.rs:16:5
**let collected_iterator: Vec<i32> = (0..10).collect();**
------------------ consider changing this to `mut collected_iterator`
...
16 |     collected_iterator.push(0);
error: aborting due to previous error(s)
error: Could not compile `playground`.
To learn more, run the command again with --verbose._

you should update it.

**Comment by xftroxgpx** [comment]
[That](https://rustbyexample.com/std/vec.html) example has some clues about this
```
// Error! Immutable vectors can't grow
collected_iterator.push(0);
// FIXME ^ Comment out this line
```

What do you think should be done?

**Comment by steveklabnik** [comment]
Yes, this is intended to not work, and for you to fix it.
