### ISSUE TITLE
please bring website up to date with the git sources

### ISSUE THREAD

**Issue by xftroxgpx** [rust-lang/rust-by-example#886]
(or, a question: when is the website going to get updated to reflect the git sources?)

because for example [this link about operator precedence](https://doc.rust-lang.org/reference.html#operator-precedence) is already corrected (11 days ago) in the git sources but not yet on [website](https://rustbyexample.com/primitives/literals.html) and I was researching the correct one with the hope of submitting a PR, then by the time I figure out which file should receive the change I find it's already [fixed](https://github.com/rust-lang/rust-by-example/blob/master/examples/primitives/literals/input.md) :D 

I know I could run this locally but for some reason I don't want to pollute my env. by installing `npm`. But then again, maybe it's worth it so I'll do it anyway:)

**Comment by steveklabnik** [comment]
Hm, it's supposed to automatically.

**Comment by xftroxgpx** [comment]
It's been 14 days. It's still not updated :) 

To check, click the `in Rust` link found in the sentence `The operators available and their precedence in Rust are similar to other C-like languages.` on this page https://rustbyexample.com/primitives/literals.html
It shouldn't load the `The Rust Reference has moved` webpage, it should load [this](https://doc.rust-lang.org/reference/expressions.html#operator-precedence) instead.

**Comment by steveklabnik** [comment]
Hmmmm https://travis-ci.org/rust-lang/rust-by-example/jobs/264551431#L1333-L1334

**Comment by steveklabnik** [comment]
I merged what should have been a fix but now it doesn't build on travis at all :/

**Comment by steveklabnik** [comment]
Well, the merge to master did; I dunno why but it seems to be working now 👍

**Comment by xftroxgpx** [comment]
Thanks for fixing this! Much appreciated.
Cheers!
