### ISSUE TITLE
Mention that crate_type attribute is ignored when using Cargo

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-by-example#890]
<https://rustbyexample.com/attribute/crate.html> is the first search hit when I look for information on the `crate_type` attribute. Unfortunately, that site fails to mention that the attribute has *no effect whatsoever* when using Cargo.

Given that this means the attribute is hardly ever useful, I think this is worth mentioning.

**Comment by steveklabnik** [comment]
Absolutely! This is related to https://github.com/rust-lang/rust-by-example/issues/215

I'm happy to mentor anyone who wants to improve this!
