### ISSUE TITLE
Destructuring (match destructuring) page is confusing

### ISSUE THREAD

**Issue by stianeklund** [rust-lang/rust-by-example#891]
The part that would cover destructuring is seems like it's missing content: https://rustbyexample.com/flow_control/match/destructuring.html

The page should be updated so that it's clear that it's a section heading.

@steveklabnik is happy to mentor anyone who wants to fix this issue!

**Comment by steveklabnik** [comment]
It's not; it's meant as a jumping off point for the next sections.

The wording could probably be improved to indicate this.

**Comment by stianeklund** [comment]
@steveklabnik Ah, I had a difficult time finding any good showcases for destructuring. Where can I find more info on this? ☺️

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by steveklabnik** [comment]
If you go to the next sections, like 

* https://rustbyexample.com/flow_control/match/destructuring/destructure_tuple.html
* https://rustbyexample.com/flow_control/match/destructuring/destructure_enum.html

etc, they go through a number of things

**Comment by stianeklund** [comment]
@steveklabnik Ok thank you. I was looking for destructuring structs, but I reckon it's the same as with enums.
