### ISSUE TITLE
Can't use copy / ctrl +c 

### ISSUE THREAD

**Issue by nihiluis** [rust-lang/rust-by-example#892]
I can't copy code on rustbyexample.com.

I'm using Arch Linux, AwesomeWM, Firefox.

Works on bad browser like Chromium.

**Comment by steveklabnik** [comment]
Works for me on Firefox, but on Windows, not Arch.

**Comment by steveklabnik** [comment]
We've now ported to mdBook, so all of this has changed. I'm going to close this as "working", as I don't believe mdbook has the same issues, but if it still persists, please let me know!

**Comment by nihiluis** [comment]
 (paste output from copy)

not for me.

**Comment by steveklabnik** [comment]
Can you file an issue upstream please? https://github.com/azerupi/mdBook/issues/new
