### ISSUE TITLE
Add optional parameter idiom (`Into<Option>`) to function documentation

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#894]
If idioms fit within the purpose of rust-by-example, I think this would be useful to add.

[Inspiratio](http://www.suspectsemantics.com/blog/2016/11/29/the-into-trick/).

**Comment by epage** [comment]
btw willing to write this up if there is interest and this is the right home for it.

**Comment by steveklabnik** [comment]
Hey @epage ! This technique is a bit controversial, so I don't think it's appropriate. Thank you for the suggestion though!
