### ISSUE TITLE
Add strategies for handling iterators of Results to Error chapter

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#895]
When I was first learning Rust, it was unclear how to handle this.  Sometimes the information is buried in the trait implementations but that requires you to know to look in there. 

[Inspiration](http://xion.io/post/code/rust-iter-patterns.html).

**Comment by epage** [comment]
btw willing to write this up if there is interest and this is the right home for it.

**Comment by steveklabnik** [comment]
This sounds like a good idea to me!
