### ISSUE TITLE
Update try! section to use ?

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rust-by-example#896]
https://rustbyexample.com/error/multiple_error_types/enter_try.html

# 16.4.2 Introducing `try!`

I would suggest that this section be updated to use `?`, since that is the common idiomatic Rust way to return an error early now.

Edit: Now that I look, RustByExample has a lot of sections where it is using `try!`, so probably best to hit them all at once for uniformity.

**Comment by steveklabnik** [comment]
Yup!

**Comment by steveklabnik** [comment]
Closed by https://github.com/rust-lang/rust-by-example/pull/912#pullrequestreview-63724054 🎊
