### ISSUE TITLE
Add example of pulling a result out of an Option into Error chapter

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#901]
I've found that I frequently need to `opt.map_or(Ok(None), |r| r.map(Some))?;` but I always forget that little invocation.  I could play around with the documentation to reinvent it but that takes a bit of time.

**Comment by epage** [comment]
btw willing to write this up if there is interest.

**Comment by steveklabnik** [comment]
Huh, interesting, I've never needed to do that.
