### ISSUE TITLE
Improve the flow of the error chapter

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#902]
Currently, the error chapter is

- panic
- option
- result
- multiple error types but only really talks about option/result as a segue into `try!` but not explaining why `try!` is relevant
- Defining one
- other uses of `try!`: aka what should be in (4)
- Boxing

Seems like the flow should be:

- panic
- option
- result
  -  defining an error type
- `try!`
- Multiple error types
  - option to result
  - `Option<Result<_>>` to `Result<Option<_>>` (see #901)
  - Boxing
  - `From`/`.into()`
  - `try!` for automatic `.into()`
- Iterating on Results (see #895)

**Comment by epage** [comment]
I'm willing to write this up but wanted to first brainstorm the approach here since it will mess up the flow of the narrative and that'll need to be re-evaluated.

**Comment by epage** [comment]
I feel like at some point, the chapter should highlight that `expect` since that seems to be encouraged in place of `unwrap` when we think it should always be safe to `unwrap`.

**Comment by steveklabnik** [comment]
Yeah, this sounds good to me!

**Comment by epage** [comment]
Fixed by #921  (unsure why github didn't auto-close this).
