### ISSUE TITLE
Please add a contributor style guide

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#908]
Open questions I have as a contributor
1. I think the purpose / structure of RBE is unclear
  - I always assumed it served as a reference syntax and idiom examples
  - In editing the error chapter for #902, I'm getting the impression that it is meant as a learning-rust book.  I found that the error sections showed non-idiomatic code and assumed you would progress through the chapter to see what they get replaced by.  I'm hoping that I can resolve both with my PR, so the answer isn't blocking me.
    - e.g. "Defining an error type" doesn't mention the `Error` trait
    - e.g. Result<_, String> is used
2. After #903, I found that there were some foot noting practices that would have been nice for me to do for my new section.  Are there other best practices for people writing or editing sections?
3. What is the role of crates?  When defining an error, should I make a foot note pointing people to `error-chain`.  I assume anything more would be left for the cookbook.

**Comment by steveklabnik** [comment]
Hey @epage ! These are great questions. I'm tagging this as "discussion", once we work out what to say, adding them to https://github.com/rust-lang/rust-by-example/blob/master/CONTRIBUTING.md would be great 👍 

> I think the purpose / structure of RBE is unclear

Purpose no, structure, for sure! Some history here: RBE was originally created by one person, and then donated to the Rust project. It's had a bunch of random contributions for years, so there hasn't been much work done on sorting out "is this the right structure", "what exactly belongs here", etc. Thinking through some of the bigger-picture stuff would be great!

More below on your sub-points:

>    I always assumed it served as a reference syntax and idiom examples
>    In editing the error chapter for #902, I'm getting the impression that it is meant as a learning-rust book. 

It is intended as a way to learn Rust, yes. 

> I found that the error sections showed non-idiomatic code and assumed you would progress through the chapter to see what they get replaced by. I'm hoping that I can resolve both with my PR, so the answer isn't blocking me.

That'd be great! It'd also maybe good to be explicit about this earlier in the chapter, possibly? Like, I wonder if we can address this through wording.

>  After #903, I found that there were some foot noting practices that would have been nice for me to do for my new section. Are there other best practices for people writing or editing sections?

I don't believe so; or at least, the closest thing is https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#appendix-a-full-conventions-text , which is more focused on API docs generally, but has some broad conventions we'd follow here too.

> What is the role of crates? When defining an error, should I make a foot note pointing people to error-chain. I assume anything more would be left for the cookbook.

Yes, in general, references to the cookbook are okay, references to other things generally aren't.

**Comment by epage** [comment]
> Purpose no, structure, for sure!

As you suggested, I suspect there might be a wording issue then.  I checked both RBE's intro and the github project before opening this issue.  The best I can find is "Rust by Example (RBE) is a collection of runnable examples that illustrate various Rust concepts and standard libraries" which, to me, makes it sound like a reference rather than a tutorial which is contrary to what I saw in the error chapter, leading to my confusion.

> It is intended as a way to learn Rust, yes.

In that context, I feel like it might be overwhelming to throw in all of the "how do I do ..." things I was starting to do (like with #903) but I still feel like we need some home for this stuff.  I'm concerned about the silos of documentation that are being created and ensuring people are aware of which type of documentation they need at the moment.  I started contributing here to help towards consolidation rather than go off and right my own blog posts, adding more noise.

For core Rust, we have
- The Book, thank you btw
- RBE
- language docs
- stdlib docs
- website FAQ (just barely found out this had useful information for exiting developers)
- crates.io's cargo documentation
- Rust API guidelines
- [whatever other official stuff I missed](https://www.rust-lang.org/en-US/documentation.html)
- [Rust patterns](https://github.com/rust-unofficial/patterns) (unofficial) which are more of idioms than patterns imo
- [Idiomatic rust blog index](https://github.com/mre/idiomatic-rust) (unofficial)
- [Various blog posts on language, library, cargo, and CI](https://github.com/ctjhoa/rust-learning)

For crates, we have
- cookbook
- crate documentation
- 24 days of Rust and other similar blog posts in the community
- [Various other blog posts](https://github.com/ctjhoa/rust-learning)

> It'd also maybe good to be explicit about this earlier in the chapter, possibly? Like, I wonder if we can address this through wording.

I'm concerned about other people like me who [search](https://www.reddit.com/r/rust/comments/7041nk/rust_by_example_has_been_ported_to_mdbook_please/dn0p8wc/) for the section they want and move on.  We'd need to change people's expectations of the book and ensure they know to read more or that there is an alternative resource that meets their need.

**Comment by steveklabnik** [comment]
>  The best I can find is 

Yeah, sounds like we could do better here!

>  I'm concerned about the silos of documentation that are being created and ensuring people are aware of which type of documentation they need at the moment.

https://doc.rust-lang.org/, which is the primary page for docs, has a summary of all of the official documentation that's at a level of quality to ship.

**Comment by marioidival** [comment]
Old but gold, I'll close this issue
