### ISSUE TITLE
Error strategies section

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#924]
The error chapter gives the developer a lot of tools but doesn't compare when they might be used.

I'm imagining this at the end of the chapter.  My rough outline
- `unwrap` / `panic` for rapid prototyping or high-locality pre-condition tests (see partition approach to Iter Result)(
- `expect` / `panic` for pre-condition tests
- `Option`
  - optional value
  - obvious why the value doesn't exist (see Path.parent
  - Return value can be ignored
- `Result`
  - Result of an operation that must be handled by the caller
  - `Result<Box>` also for rapid prototyping

Related resources
- https://doc.rust-lang.org/std/macro.panic.html
- https://web.archive.org/web/20140717204300/http://doc.rust-lang.org/std/result/#result-and-option
- https://www.reddit.com/r/rust/comments/2j0k21/rust_option_vs_result/?st=j7wrnocn&sh=7869f07f

**Comment by jansol** [comment]
I'll draft something for this.
