### ISSUE TITLE
Methods for pulling data out of arrays

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#925]
The focus would mostly be to help with people getting the error
```
<anon>:3:25: 3:33 error: cannot move out of indexed content [E0507]
<anon>:3     let fullname = join(names[0], names[1]);
```

See [this blog post](http://xion.io/post/code/rust-move-out-of-container.html#rust-move-out-of-container) for the inspiration.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
