### ISSUE TITLE
Add implicit reference conversion to Strings section

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#926]
Talk about functions that can accept
- `&str`
- `String`
- `T: Into<String>`
- `T: AsRef<str>`
- `T: Into<Cow<'a, str>>` 

Based on
- http://hermanradtke.com/2015/05/06/creating-a-rust-function-that-accepts-string-or-str.html
- https://users.rust-lang.org/t/idiomatic-string-parmeter-types-str-vs-asref-str-vs-into-string/7934

**Comment by epage** [comment]
Not sure if this would be like #894 or just too much for this resource but I feel like this should be captured somewhere.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
