### ISSUE TITLE
Visibility section should link to Visibility in the Rust reference

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#927]
Until I read the RFC for changing visibility, I had no clue that `pub` can take a parameter.  It doesn't look like this is covered in the book and in RBE its buried with a single reference to `pub(crate)`.

A simple way of handling this would be to link to [visibility in the reference](https://doc.rust-lang.org/beta/reference/visibility-and-privacy.html#pubin-path-pubcrate-pubsuper-and-pubself), the only piece of documentation that addresses it that I could find.

**Comment by steveklabnik** [comment]
Yeah, it's a very new feature, and so its docs aren't as integrated as most things.

**Comment by hekrause** [comment]
Can it be that this can be closed because the [example](https://rustbyexample.com/mod/visibility.html) was updated in another pull request?

**Comment by steveklabnik** [comment]
I believe so. If I'm wrong, please let me know!

**Comment by epage** [comment]
I still feel like the different aspects of visibility are lost in a really large example.  It'd be nice if the introductory text called out what all is being showcased in the code or gave distinct, smaller examples for each one.

While nice, I'm fine with it staying as is if you all decide so.

**Comment by steveklabnik** [comment]
I'm generally happy to do any improvements, if you'd like to update it,
don't hesitate to send in a PR!
