### ISSUE TITLE
12.4 Bounds should mention multiple bounds syntax

### ISSUE THREAD

**Issue by ainar-g** [rust-lang/rust-by-example#938]
Recently I've been trying some Rust, and I needed to specify several trait bounds. I tried "T: A, B", but this obviously didn't work. Rust By Example was one of the first search suggestions, but there was not an example of multiple bounds. I've eventually found that you need to use "T: A + B", so that comma doesn't break things, but I think that many people will look this up, and it's better if the trait bounds chapter covers this.

**Comment by mdinger** [comment]
Like [multiple bounds](https://rustbyexample.com/generics/multi_bounds.html)?

**Comment by ainar-g** [comment]
@mdinger I guess I could argue that it shouldn't be a chapter of its own, but the fact is — I'm apparently blind. Thanks.
