### ISSUE TITLE
Add examples of multi-dimensional arrays

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust-by-example#944]
For example, what does `[[f32; 3]; 32]` does? How to use it? How to turn it into a `&[f32]` ? Show its memory layout.

Same for "dynamic" ones, e.g. `Vec<[f32; 3]>`, how to turn that into a `&[f32]` ? How to "collect" a `[[f32; 3]; 32]` into a `Vec<[f32; 3]>`, etc.

**Comment by faulesocke** [comment]
Any progress here?

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
