### ISSUE TITLE
Live code editor not working

### ISSUE THREAD

**Issue by FuujSama** [rust-lang/rust-by-example#963]
I've tried with chrome, opera and Firefox quantum. It simply works like normal, non-editable text. I can't change anything in the code. This is strange since it used to work wonderfully the last time I tried to use the website.   
I didn't see any other way to ask a question so this seemed like the only way to get a solution.

If it's of use, both the japanese and chinese websites are working fine.

**Comment by steveklabnik** [comment]
Do you have any plugins?

**Comment by FuujSama** [comment]
So, I ran the repository locally and it's working fine, it's just the website that doesn't work. I've ran the website with all plug ins disabled and nothing changed.  

The Web-Console shows the following errors:

```
Blocked loading mixed active content “http://fonts.gstatic.com/s/cabin/v12/yQOMOX5hR0-6LTD879t-PQ.woff2”
[Learn More]

mut.html
Blocked loading mixed active content “http://fonts.gstatic.com/s/cambay/v3/uXfMy7n4egUqCpK5wbBmsw.woff2”
[Learn More]

mut.html
Blocked loading mixed active content “http://mygotzone.com/wp-content/themes/mts_wordx/fonts/fontawesome-webfont.woff2?v=4.3.0”
[Learn More]

mut.html
Blocked loading mixed active content “http://fonts.gstatic.com/s/cambay/v3/9M3kjQTQkUz1UH-8XJ4q-FtXRa8TVwTICgirnJhmVJw.woff2”
[Learn More]
mut.html 
```

**Comment by lerugray** [comment]
I am also having this problem which is sad, if anyone can recommend another good interactive tutorial that would rule.

**Comment by MGageMorgan** [comment]
It doesn't work locally or online for me either, can confirm.

**Comment by steveklabnik** [comment]
What browsers are you using, @lerugray @MGageMorgan ?

**Comment by lerugray** [comment]
I was using Chrome at the time

**Comment by MGageMorgan** [comment]
@steveklabnik I tried both Chrome and Firefox 59 Nightly as of a couple hours ago. Neither work. Also tried both local copy and the website that is live right now. Neither work.

**Comment by tmagrino** [comment]
I'm having the same issue (checked using an incognito windows to try to ensure it wasn't an extension issue) on Chrome Version 63.0.3239.84 on Windows 10.
