### ISSUE TITLE
Example for making a trait object cloneable

### ISSUE THREAD

**Issue by epage** [rust-lang/rust-by-example#966]
I recently wanted to make a struct cloneable.  The struct contains trait objects.  It took a lot of trial and error of what I thought might work along with google searches before I came across an answer that I think works.

See https://stackoverflow.com/questions/30353462/how-to-clone-a-struct-storing-a-trait-object/30353928#30353928

I see this being common enough to earn being documented somewhere and not sure of a better place than RBE.  And if that isn't the best answer, then even more reason for it to get documented.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
