### ISSUE TITLE
meta/doc example command throws a dead code warning

### ISSUE THREAD

**Issue by sethbattin** [rust-lang/rust-by-example#970]
When trying the example at https://rustbyexample.com/meta/doc.html I received the following warning:

```
$ rustc person.rs --crate-type lib
warning: function is never used: `main`
  --> person.rs:38:1
   |
38 | fn main() {
   | ^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default
```

The second command runs fine (I copied the example code verbatim into `person.rs`):

```
$ rustdoc --test --extern doc="libdoc.rlib" person.rs

running 1 test
test person.rs - Person::new (line 18) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Other info:
On Windows 10 Linux subsystem:
```
$ rustc -V
rustc 1.22.1 (05e2e1c41 2017-11-22)
```

I assume there are two easy ways to fix this, either squashing warnings or removing `main`, so I'll try to figure out a patch.  But I've only been writing rust for about 30 minutes so no promises :)

**Comment by sethbattin** [comment]
I found an answer in https://rustbyexample.com/hello/print.html in the form of `#[allow(dead_code)]`

**Comment by marioidival** [comment]
I think it's best to remove the main function, for consistency, because this chapter talk about documentation and the example show how to create a lib. What you think @QuietMisdreavus ?

**Comment by QuietMisdreavus** [comment]
I agree; the best solution would be to remove `fn main` and treat the example as a library to begin with. You can't run tests on binary crates anyway - having a main function there is just confusing.

(On a mostly unrelated note, you could get rid of the `--crate-type lib` on the `rustc` command by adding a `#![crate_type="lib"]` to the sample, right next to the `#![crate_name]` attribute. That would also cement the example as not needing `fn main` in the first place.)

**Comment by sethbattin** [comment]
I read back to see how that fits into the chapter.  Because it's about doc comments (and not compiler arguments), I would agree that it would be an improvement to remove the unrelated cruft related to being a library.  For that matter, I think I recall this was the first page that shows libraries as a thing.  Which was intriguing for my first-time studying, but obviously distracted me from the doc block bits.  :)

Rather than that last paragraph, I would be more interested in how and where I could see the outcome of the docs.  Regardless of libraryhood.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
