### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang/rust-by-example#990]
I was trying out my [mdbook-linkcheck] backend/plugin for `mdbook` with the Rust By Example book and it actually worked :tada: It found a couple links where the user had accidentally linked to `*.md` instead of `*.html`, as well as one where it seems the page was moved.

The tool's output:

```
There were 4 broken links

cargo/test.md#4: "meta/test.html" doesn't exist
macros/syntax.md#6: Found "macros/designators.md", did you mean "macros/designators.html"?
macros/syntax.md#7: Found "macros/overload.md", did you mean "macros/overload.html"?
macros/syntax.md#8: Found "macros/repeat.md", did you mean "macros/repeat.html"?
```

[mdbook-linkcheck]: https://github.com/Michael-F-Bryan/mdbook-linkcheck

**Comment by projektir** [comment]
I have just [fixed](https://github.com/rust-lang/rust-by-example/pull/989) these and others because it was breaking rust-lang/rust#46194.
